### PR TITLE
Porting ruby-core test suite changes

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Ruby-core team commit changes in our code directly to their repository.

## What is your fix for the problem, implemented in this PR?

Port those changes.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by hsbt** [comment]
@deivid-rodriguez Thanks for this ❤️ 

Did you track the recent [changes](https://github.com/ruby/ruby/commits/master/spec/bundler
) by @znz ? 

It fixed the out-of-place build of ruby-core repository. I'm not sure it fixed by https://github.com/rubygems/rubygems/pull/4327 yet.

**Comment by deivid-rodriguez** [comment]
Yes, I noticed all those changes and decided to remove all the hacks since they are hard to maintain and they don't buy us much. Next time we sync those changes by @znz will be overwritten, but the code will no longer cause any issues for ruby-core since it's gone.

I have  a question for @nobu regarding 79490fa79854770e5bc325145f385b54fc426e7c. I just noticed a leftover temporary directory left at the root of the repo after running tests with this change, is it expected?

**Comment by nobu** [comment]
No, I wanted all temporary directories to be removed, but just one directory is created to write a `gemrc` file  **after** `teardown`, and I don't know how it runs.
Seems no finalizer, `at_exit`, `END {}`.

**Comment by deivid-rodriguez** [comment]
Until we figure it out, can we create this temporary folder inside `tmp/` so that, since `tmp/` is gitignored, the leftovers don't show up as untracked changes?

**Comment by nobu** [comment]
Of course it doesn’t matter for me, as far as these directories get cleared eventually.

**Comment by nobu** [comment]
JFYI, this is the branch I tried once.
https://github.com/nobu/rubygems/tree/temporary-index-directories

**Comment by deivid-rodriguez** [comment]
Thanks @nobu, I'll have a look :+1:.

**Comment by deivid-rodriguez** [comment]
@nobu I pushed a new version that shouldn't leave any test folders around and I think it should work fine for ruby-core too. I'll merge it after CI.

**Comment by deivid-rodriguez** [comment]
I created a PR in the ruby repo to check CI against this branch and it failed, but it passes on my machine locally so I'm not sure what's going on. Any ideas?

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
I confirmed that this PR is breaking the ruby-core CI. I'll investigate why it broke and why our "ruby-core simulation" CI didn't catch it.

**Comment by deivid-rodriguez** [comment]
I think I get it now. Ruby-core runs rubygems tests in parallel (we should do that too, by the way). The way this PR is setup (where `tmp/` is cleaned up after each test), tests in one thread will mess up the directory layout for other tests in other threads. Will fix.

**Comment by deivid-rodriguez** [comment]
@nobu I think there's something work the the processing of the parallel test workers. With the broken code, `make -j2 -s test-all TESTS=rubygems` still reports a zero exit code.

**Comment by nobu** [comment]
There are so many "No such file or directory" on temporary directories, which seem caused by some races.

**Comment by deivid-rodriguez** [comment]
> There are so many "No such file or directory" on temporary directories, which seem caused by some races.

Yes, I already have a fix for this, I'm just trying to make sure our catches it next time something like this happens, and I found that `make -j2 -s test-all TESTS=rubygems` still returns a zero exit code even when all those errors happen.

**Comment by deivid-rodriguez** [comment]
Oh, I think I understand now. If workers fail, ruby-core retries to run sequentially and that succeeds, so the issue is not detected.

`make -j2 -s test-all TESTS="rubygems --no-retry"` does what I want :+1:.

**Comment by deivid-rodriguez** [comment]
Yes, that did the trick. Our CI should be able to catch a similar issue in the future.

**Comment by nobu** [comment]
A question: in 3e522bac65d8c12b90949c09b5f61466ae682153, 
> since the current directory is changed by our tests, tests can fail.

I can't get this point.
What does "changed" mean?
First I thought the case `Dir.tmpdir` returns a relative path and not accessible after `Dir.chdir`, but the result should have been absolute always.

**Comment by deivid-rodriguez** [comment]
As far as I understand, `Dir.chdir` is not thread safe, and rubygems tests do that at the moment. When I introduced that commit, I was having issues with `Dir.tmpdir` silently not respecting `ENV["TMPDIR"]` (https://bugs.ruby-lang.org/issues/16975) and falling back to the pwd. When that happened the path of generated files would be unpredictable and some of our tests that make assertions  on the number of parts in those paths (for example the test I changed in this PR) would fail.

**Comment by deivid-rodriguez** [comment]
It should be ready now and I also checked that it passes ruby-core CI at https://github.com/ruby/ruby/pull/4143.

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Thanks @simi!!

**Comment by nobu** [comment]
Still a garbage is left.

```sh
$ ruby tool/sync_default_gems.rb rubygems
Sync rubygems/rubygems
$ rm -fr tmp
$ make test-all TESTS='rubygems --no-retry' > /dev/null
Skipping Gem::PackageTask tests.  rake not found.
$ ls tmp/
test_rubygems_20210204-76044-xpvcqw/
$ find tmp -type f -print -exec cat {} \;
tmp/test_rubygems_20210204-76044-xpvcqw/userhome/.config/gem/gemrc
---
:backtrace: false
:bulk_threshold: 1000
:sources: []
:update_sources: true
:verbose: true
:concurrent_downloads: 8
http_proxy:
```

**Comment by nobu** [comment]
Seems writing to different (the previous?) `user_home` path.

**Comment by deivid-rodriguez** [comment]
#4344 should fix it! Rubygems abuses memoization :man_shrugging:

**Comment by nobu** [comment]
Thanks, it work perfectly.

**Comment by nobu** [comment]
> When that happened the path of generated files would be unpredictable and some of our tests that make assertions on the number of parts in those paths (for example the test I changed in this PR) would fail.

Thank you for the clarification.
So it is ok without `@tmp` now?

**Comment by deivid-rodriguez** [comment]
I'm not sure but is it a problem?

**Comment by nobu** [comment]
Just I prefer temporary files/directories under `TMPDIR`, not to pollute the source directory.
I'll make another PR about this later, perhaps.

**Comment by deivid-rodriguez** [comment]
I actually prefer the current solution with a local `tmp/` folder. It makes things more self-contained and easier to debug, in my opinion.

**Pull request merged**
