### PR TITLE
Remove FIXME comment related to PathSupport

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Followup https://github.com/rubygems/rubygems/pull/2851

cc @simi 
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
