### PR TITLE
Prefer to use String#match

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

`String#match?` is faster 10% than `=~` .

see https://github.com/ruby/csv/pull/30
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Can I close this one? I don't think we need this.

**Comment by hsbt** [comment]
@deivid-rodriguez I added the motivation about this.

**Comment by deivid-rodriguez** [comment]
Yeah, I mean, I'm good with this but is there a specific code path that gets much faster with this change and that justifies introducing compatibility code for this instead of waiting until we drop ruby 2.3 support? I mean there's a lot of micro optimizations we could introduce like.. anything from [rubocop-performance](https://github.com/rubocop-hq/rubocop-performance) or [https://github.com/DamirSvrtan/fasterer](fasterer), but... why this specific one and not others?

Also, regarding this particular change, I think `String#ends_with?` might be faster and supports ruby 2.3.

**Comment by olleolleolle** [comment]
@deivid-rodriguez [String#end_with?](https://rubyapi.org/2.3/o/string#method-i-end_with-3F) would be useful to check "suffixes", but in this string, it's all of the String. From the \A to the \z.

Would it help to drag out the pattern into a constant? `/\A[0-7]*\z/`

**Comment by deivid-rodriguez** [comment]
Right, I misread the code, thank you!

Then forget about my `end_with?` suggestion.

My first concern is still valid, I don't see a reason for this particular optimization given the compatibility code we need to add. I prefer to wait until we drop ruby 2.3 support.

**Comment by hsbt** [comment]
Closing favor from https://github.com/rubygems/rubygems/pull/3398/commits/ef2dcef07533163a5da2e3efd9faf6ee5aa4c3cc

**Comment by hsbt** [comment]
ref. https://github.com/rubygems/rubygems/pull/3398

**Pull request closed without merging**
