### PR TITLE
remove util/stringio.rb, readd stringio

### PR DESCRIPTION
**Pull request by pjump**
the in-ruby emulation of stringio makes Gem::gunzip almost 300 times slower
(on ruby 2.2.2)
as compared to using standard libary's stringio

Gem.gunzip(File.read('specs.4.8.gz')) takes about 16 seconds with 
rubygems/util/stringio.rb
and about 50ms without it

### CODE REVIEW

**Comment by pjump** [comment]
I understand this is basically a revert of bb3f55dd7ddd750b3b59c31ea532a8f34b165ee9, but I don't get the point of "removing a depenency on stringio". Strinio is in the standard library doesn't that mean it should be always available?

**Comment by evanphx** [comment]
Clearly I should have written a longer commit message. As I recall, I was doing some basic dependency reduction, as you can see we need barely any of StringIO so I just pruned it out.

The reason StringIO is so much faster is that it uses a proper buffer underneath where as StringSink just uses String#+= which creates a lot of churn. StringSink could be made to use a buffer and would thusly be a lot faster.

I guess it's a question of if we care about Rubygems pulling in StringIO as a dependency or not.

**Comment by evanphx** [comment]
@drbrain Could you weigh in?

**Comment by segiddins** [comment]
@evanphx wouldn't it only need to pull it in when zipping/unzipping?

**Comment by raggi** [comment]
It looks like the performance issues of the reader can be fixed by using a position integer instead of performing these allocations. We should probably add the EOFError semantics anyway, to save this breaking iff zlib's expectations of the API become more "strict", given that it's documentation says "works like IO"

**Comment by raggi** [comment]
``` diff
diff --git a/lib/rubygems/util/stringio.rb b/lib/rubygems/util/stringio.rb
index 2ea6961..e4b9462 100644
--- a/lib/rubygems/util/stringio.rb
+++ b/lib/rubygems/util/stringio.rb
@@ -18,16 +18,16 @@ end
 class Gem::StringSource
   def initialize(str)
     @string = str.dup
+    @pos = 0
   end

   def read(count=nil)
-    if count
-      @string.slice!(0,count)
-    else
-      s = @string
-      @string = ""
-      s
-    end
+    raise EOFError unless @string
+    count ||= @string.length
+    s = @string[@pos,count]
+    @pos += count
+    @string = nil if @pos >= @string.length
+    s
   end

   alias_method :readpartial, :read
```

Should work. Please bench.

**Comment by pjump** [comment]
Nice work, @raggi . That definitely should be faster than mutating the string. But I think the right thing to do here is simply use the standard library. StringIO is C code on YARV -- there's no way ruby can beat C code, and there's hardly any reason not to depend on a standard library module.

**Comment by raggi** [comment]
@pjump I'd guess this makes it easier for ruby implementations to bootstrap w/ rubygems. Given the stdlib slowly moving modules to rubygems, it's possible stringio could become such a package one day. Anyway, I'm sure the others will decide based on their thoughts in those regards, I have no dogs in this race.

**Comment by drbrain** [comment]
It seems we require stringio [in RemoteFetcher](https://github.com/rubygems/rubygems/blob/5c7bfb5c05202b4db971dd672d88a42298a0d84e/lib/rubygems/remote_fetcher.rb#L70) so I have no objection

**Pull request merged**
