### PR TITLE
Improve TarHeader#calculate_checksum

### PR DESCRIPTION
**Pull request by Maumagnaguagno**
String#unpack("C*") is equivalent to String#bytes and Array#inject {|a,b| a + b } is equivalent to Array#sum.
This is a minor enhancement in terms of speed and readability.

## Benchmark

This benchmark uses header data from related [tests](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_package_tar_header.rb):

```ruby
PACK_FORMAT = "a100" + # name
              "a8"   + # mode
              "a8"   + # uid
              "a8"   + # gid
              "a12"  + # size
              "a12"  + # mtime
              "a7a"  + # chksum
              "a"    + # typeflag
              "a100" + # linkname
              "a6"   + # magic
              "a2"   + # version
              "a32"  + # uname
              "a32"  + # gname
              "a8"   + # devmajor
              "a8"   + # devminor
              "a155"   # prefix

def header(checksum)
  header = [
    "x",
    oct(0644, 7),
    oct(1000, 7),
    oct(10000, 7),
    oct(100, 11),
    oct(12345, 11),
    checksum,
    " ",
    "0",
    "link",
    "ustar",
    oct("00", 2),
    "user",
    "group",
    oct(1, 7),
    oct(2, 7),
    "y"
  ]
  header = header.pack PACK_FORMAT
  header << ("\0" * ((512 - header.size) % 512))
end

def oct(num, len)
  "%0#{len}o" % num
end

h = header(' ' * 8)
p a = h.unpack("C*").inject {|a, b| a + b }
p b = h.bytes.sum
p oct(a,6)
p oct(b,6)

require 'benchmark'
n = 100_000
Benchmark.bm do |benchmark|
  benchmark.report("old checksum") do
    n.times do
      h.unpack("C*").inject {|a, b| a + b }
    end
  end
  benchmark.report("new checksum") do
    n.times do
      h.bytes.sum
    end
  end
end
```

The result is ~8 times faster for 100_000 runs with Ruby 3.0.5p211.
```
5431
5431
"012467"
"012467"
       user     system      total        real
old checksum  3.966327   0.003138   3.969465 (  3.971703)
new checksum  0.496551   0.000001   0.496552 (  0.496906)
```

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write tests => **tests already exist**
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by Maumagnaguagno** [comment]
Should I replace the checksum from **test/rubygems/package/tar_test_case.rb** too?https://github.com/rubygems/rubygems/blob/9af6eae5ec90139469e908c80920ddcec71af89a/test/rubygems/package/tar_test_case.rb#L69-L72

**Comment by simi** [comment]
> Makes sense and it's easier to read. Is there a test that verifies this result already?

Are you looking for this https://github.com/rubygems/rubygems/blob/6e8260d717df2026a6a2b181fb2881109d4c8710/test/rubygems/test_gem_package_tar_header.rb#L137-L143?

**Comment by martinemde** [comment]
Oh, I see your comment about the test. I think you could replace calc_checksum too. I think the implementation is identical.

**Review by deivid-rodriguez — APPROVED** [review]
Thank you @Maumagnaguagno!

**Comment by nobu** [comment]
`header.sum(-1)` would be faster.

**Pull request merged**
