### PR TITLE
At least explain what to do instead of a LoadError

### PR DESCRIPTION
**Pull request by indirect**

### CODE REVIEW

**Comment by andremedeiros** [comment]
```Error while loading the hoe gem.
Please install it by running the following:

$ [sudo] gem install hoe
```

How's that?

**Comment by indirect** [comment]
:+1:

**Comment by djberg96** [comment]
Eh, this seems like excessive handholding to me. I mean, if you're smart enough to clone the repo and run the rake command, you know what that error means.

**Comment by djberg96** [comment]
That said, I'll defer to Ryan. It's his gem. :)

**Comment by indirect** [comment]
@djberg96 that is _definitely_ not true. I've run workshops helping Ruby developers start contributing to open source, and this is exactly the kind of "excessive handholding" that means the difference between someone contributing to your project and someone not contributing.

**Pull request merged**
