### PR TITLE
Remove Syck traces

### PR DESCRIPTION
**Pull request by voxik**
Syck can't be used as YAML engine since Ruby 2.2 and most of the support was removed already. This is attempt to remove the remaining traces. Let's see what happens.

### CODE REVIEW

**Comment by voxik** [comment]
Hm, right. I have not executed test suite and there are a few test cases testing specifically the syck behavior.

**Comment by deivid-rodriguez** [comment]
I think this is essentially a dup of https://github.com/rubygems/rubygems/pull/3797?

**Comment by voxik** [comment]
You are right :see_no_evil:

**Comment by voxik** [comment]
I think we differ only here:

https://github.com/rubygems/rubygems/pull/3797/files#diff-dd90140a6483cfb50fbbc3268f0d77984cd96e17792201e53bb3c0dc7ec435f9L627

Closing this now. Sorry for the nose.

**Comment by deivid-rodriguez** [comment]
No problem! :+1:

**Pull request closed without merging**
