### PR TITLE
Update bundler-1.16.6

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by colby-swandale** [comment]
did i break something in this release?

**Comment by segiddins** [comment]
Looks like a test just needs to handle not being in a git repo, or something?

**Comment by hsbt** [comment]
@segiddins Yes, But Bundler-1.16.4 with RubyGems master passes the same example. Do we have some regression with Bundler-1.16.5 or 1.16.6?

**Comment by indirect** [comment]
This is not a regression, but it's a change in the way that Bundler handles printing version numbers when Bundler itself is not inside a git repo. We can update the test 👍

**Comment by indirect** [comment]
@hsbt @colby-swandale I fixed it! https://github.com/bundler/bundler/pull/6737 After we backport the commit to `1-16-stable`, I think it's fine to update the submodule to point to that commit, rather than doing an entire Bundler release just for a fix that only works when Bundler is a submodule in RubyGems.

**Comment by hsbt** [comment]
@indirect I agreed your suggestion. I will update submodule after updating to `1-16-stable` branch in bundler and release rubygems 2.7.8.

**Comment by hsbt** [comment]
@indirect @colby-swandale Still failing with `1-16-stable` branch. I can release RG 2.7.8 with Bundler 1.16.6, But I hope to resolve this failure because it's also failing with Bundler 1.17.0 or 2.0.0.

**Comment by colby-swandale** [comment]
Sorry for this to take so long @hsbt i will make this my number 1 issue to resolve.

**Comment by colby-swandale** [comment]
I'm a bit confused as to what's happening here. The test is passing on my local machine and looking into the report on travis, it seems to be reporting for a different commit https://github.com/rubygems/rubygems/commit/c6bdddd5b6dddaa82939056c8253ac2723ecd1d1

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
