### PR TITLE
[RubyGems] Make deprecation message for paths= more helpful

### LINKED ISSUE #1551: "Array values in the parameter are deprecated" warning not enough helpful ?
Hello

My current problem is when I'm running my rails server (rails console, rails server) I get the warning added by @tenderlove in https://github.com/rubygems/rubygems/commit/a6b69e94232166dda441bbb69b64cf90562eebfd . The problem is the answer doesn't help me a lot to fix it. I get
```
Array values in the parameter are deprecated. Please use a String or nil.
An Array was passed in from bin/rails:3:in `load'
```

How can I get more infos to be able to fix this warning?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.2
$ rails --version
Rails 4.2.5.2
```

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Closes #1551.

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends
- [ ] [Squash commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by benoittgt** [comment]
One question quite out of thread. How can I try locally different output for the warning like the one you did. My rubygems is installed by rvm. I've check the [contributing.rdoc](https://github.com/rubygems/rubygems/blob/master/CONTRIBUTING.rdoc) without seeing the proper answer with rvm. Should I git clone, `rake newb` then change a shell path to tell that my rvm is now on the fresh git clone one ?

Thanks in advance

**Comment by segiddins** [comment]
From the contributing docs: `ruby -Ilib bin/gem install` (or use `RUBYOPT`)

**Comment by benoittgt** [comment]
Sadly it fails.

```shell
$ rake -v newb                                                                                                           [18:40:53]
Parsing sources...
 16% [29/174]  lib/rubygems/commands/setup_command.rb
RDoc::Parser::Ruby failure around line 313 of
lib/rubygems/commands/setup_command.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/bti/.rvm/rubies/ruby-2.3.0/bin/ruby -c lib/rubygems/commands/setup_command.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `singleton' for #<RDoc::Parser::Ruby:0x007fd1c32c13b0>
Did you mean?  singleton_class

rake aborted!
NoMethodError: undefined method `singleton' for #<RDoc::Parser::Ruby:0x007fd1c32c13b0>
```

I would like to help but I can't for the moment. :disappointed:

**Comment by segiddins** [comment]
@indirect r?

**Comment by duckinator** [comment]
LGTM. (Aside: GitHub is saying the Windows build is still pending, but https://ci.appveyor.com/project/rubygems/rubygems/build/109 shows it passed.)

@homu r+

**Comment by benoittgt** [comment]
Thanks @segiddins and @duckinator

**Pull request merged**
