### PR TITLE
add Gemfiles gemspec as a vendored path, fix #1204, fix #1033

### LINKED ISSUE #1033: can not gem i -g on non existing gem
Using rubygems abf89e04954b8a2ddfb6948d0860111990a6efa2
```bash
gem -v
2.4.2
```
with `.gemspec`:
```ruby
Gem::Specification.new do |spec|
  spec.name        = 'long-nonexisting-gem-name'
  spec.version     = '1.0.0'
  spec.add_dependency('session')
end
```
with `Gemfile`:
```ruby
#ruby=2.0.0
source "https://rubygems.org"
gemspec
```
running `gem i -g` I get:
```bash
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: user requested 'long-nonexisting-gem-name (= 1.0.0)'
```
and after `bundle install` (to get `Gemfile.lock`),  `gem i -g` I gives:
```bash
ERROR:  While executing gem ... (Gem::GemNotFoundException)
    unable to find ./long-nonexisting-gem-name.gemspec for gem long-nonexisting-gem-name
```
and finally after
```bash
mv .gemspec ./long-nonexisting-gem-name.gemspec
```
`gem i -g` I gives:
```ruby
ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?): ?gems=session (>= 0)
```

### LINKED ISSUE #1204: installing gems via Gemfile gemspec
exactly the same steps as in https://github.com/rubygems/rubygems/issues/1141 but there is new error (https://github.com/rubygems/rubygems/issues/1141#issuecomment-71127935):

> Unable to resolve dependency: user requested 'asciidoctor-doctest (= 1.5.2.dev)'

### PR DESCRIPTION
**Pull request by mpapis**

### CODE REVIEW

**Comment by indirect** [comment]
This change breaks the tests for the gemspec method. Please fix the build!

**Comment by mpapis** [comment]
fixed and simplified tests: `36 additions` and `45 deletions`.

**Comment by krainboltgreene** [comment]
This looks like a pure feature addition, yeah?

**Comment by mpapis** [comment]
@krainboltgreene it's a bugfix, as described in https://github.com/rubygems/rubygems/issues/1204#issuecomment-86722876 - the feature to load gems from Gemfile via gemspec was already in, it was broken when the version in gemspec was different then in the loaded index.

**Comment by krainboltgreene** [comment]
Roger, thanks! I really was just trying to see if this amounted to a major version change.

**Comment by mpapis** [comment]
thanks :)

**Pull request merged**
