### PR TITLE
Add MacOS to CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

We're not testing bundler against MacOS in CI.

By adding it, we achieve several things:

* It can help us catch MacOS specific issues.
* It aligns bundler specs with rubygems which already run on MacOS.
* It allows bundler developers using MacOS to have a green suite.
* It can reduce friction with ruby-core by catching CI issues that will be detected later by them otherwise.

## What is your fix for the problem, implemented in this PR?

My fix is to add MacOS to bundler's CI.

Note that on initial runs some specs failed that test compatibility features that should've been removed a long time ago failed. Just to get to an initial green point I tentatively removed those, but we can discuss more about that before merging this.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by djberg96** [comment]
We use Travis, yes? I think their matrix says it's supported, but it always bombed when I actually tried to use the thing. Not saying this is a bad idea, just something to keep in mind.

**Comment by deivid-rodriguez** [comment]
No, we use Github Actions. I've heard and seen MacOS work inconsistently on Github Actions (see https://github.com/actions/virtual-environments/issues/841), but we already use it for rubygems and it works mostly fine, so I guess we can try.

**Comment by simi** [comment]
@deivid-rodriguez is the only problem now in different output of an error?

```diff
-Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from http://127.0.0.1:21454/ due to underlying error <Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:21454 (Connection refused - connect(2) for "127.0.0.1" port 21454) (http://127.0.0.1:21454/specs.4.8.gz)>
+Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from http://127.0.0.1:21454/ due to underlying error <timed out (http://127.0.0.1:21454/specs.4.8.gz)>
```

**Comment by deivid-rodriguez** [comment]
Weird, I rebased it to see how it's going now.

**Comment by deivid-rodriguez** [comment]
@simi Finally resolved the remaining issues and this is now green!

**Pull request merged**
