### PR TITLE
Added template files to vendoerd bundler.

### LINKED ISSUE #2062: Vendored Bundler fails running `bundle gem` due to missing template files
I'm having the following problem:

I want to scaffold a new Ruby Gem by running `bundle gem foo --verbose` but the command fails with the following error message:

```
$ bundle gem foo --verbose
Running `bundle gem foo --verbose` with bundler 1.16.0
Creating gem 'foo'...
MIT License enabled in config
Code of conduct enabled in config
Could not find "newgem/Gemfile.tt" in any of your source paths. Your current source paths are: 
/Users/sebroeder/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/templates
```

Checking manually confirms that there is indeed no `newgem/Gemfile.tt` in the mentioned path:

```
tree /Users/sebroeder/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/templates
/Users/sebroeder/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/templates
└── gems.rb
```

If you compare this with https://github.com/bundler/bundler/tree/1-16-stable/lib/bundler/templates, it seems like there are files missing from the Bundler gem that is vendored with RubyGems.  

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

This is on a clean installation, with only the default gems installed:

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (default: 1.16.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.4)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.5)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
rubygems-update (2.7.1)
test-unit (3.2.3)
xmlrpc (0.2.1)
```

Here are my current environment details:

```
$ gem env version
2.7.1
```

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.1
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/sebroeder/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /Users/sebroeder/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /Users/sebroeder/.rbenv/versions/2.4.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/sebroeder/.rbenv/versions/2.4.2/bin
  - SPEC CACHE DIRECTORY: /Users/sebroeder/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/sebroeder/.rbenv/versions/2.4.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /Users/sebroeder/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
     - /Users/sebroeder/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/sebroeder/.rbenv/versions/2.4.2/bin
     - /usr/local/Cellar/rbenv/1.1.1/libexec
     - /Users/sebroeder/.rbenv/shims
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by hsbt**
Fixes #2062

# Description:

Current installer ignored *.tt or non-extension files. I added `bundler/templates/**/*` files when installing vendoered bundler.

### CODE REVIEW

**Comment by envygeeks** [comment]
@segiddins can we get a review so this can be released soon? This took out down `jekyll/docker` today and stalled several peoples infrastructures, because of that we had to refuse to install anything RubyGems or Bundler related and given RubyGems has had a few security issues this year we don't feel safe doing that for very long.

**Comment by indirect** [comment]
@envygeeks this is free software, and you’re getting way more than what you’re paying for. demanding free work faster because you are inconvenienced is not cool, and this is at least your second warning. cut it out.

@hsbt thank you! this looks good 👍🏻

@bundlerbot r+

**Comment by envygeeks** [comment]
I never demanded anything, read it again, I passively asked if he could REVIEW IT. Not if he could fix it, I didn't even demand anything, stop making stuff up. And Cut what out? Asking for quick resolutions to infrastructures being taken out, and me taking the blame for others bugs? Or to stop donating to RubyTogether through clients?  You are a very aggressive person, and I can see that your Code of Conduct is nothing but a game.

**Comment by hsbt** [comment]
I'm not sure why test fails with current master... Should we ignore these matrix?

**Comment by hsbt** [comment]
@bundlerbot retry

**Comment by JoshCheek** [comment]
The new version worked for me: https://vimeo.com/241787686

(note: HEAD was @ 889e25128ea6dbe66d9280f342a6549ad029f2cd)

**Comment by hsbt** [comment]
@JoshCheek Thanks to your confirmation. I'll release 2.7.2 after triaging other issues.

**Comment by mgathu1** [comment]
@hsbt and the team,

Thanks for having fixed this. Your efforts and time are much appreciated. This bug had affected my rails build on gitlab CI and I could not figure it out.

Thanks :)

**Comment by vovimayhem** [comment]
@hsbt You rock dude!!!!

**Comment by hsbt** [comment]
Hi all, I just released rubygems-2.7.2 and confirm to work `bundle gem` command with it version.

Please try it 🙏

**Pull request merged**
