### PR TITLE
[SafeYAML] Avoid warning when Gem::Deprecate.skip is set

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

This will allow Bundler to suppress the warnings, so we can get the tests passing again

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by duckinator** [comment]
It'll just fail if I r+ it right now bc it relies on the Bundler PR in order to complete the fix, but this looks good to me.

**Comment by olleolleolle** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot retry

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
