### PR TITLE
[Resolver] Update to Molinillo 0.4.0

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
Any reason this can't be merged?

**Comment by indirect** [comment]
Merge conflicts? But I'll merge it if you rebase.

**Comment by indirect** [comment]
I was tricked by iOctocat.

**Comment by hsbt** [comment]
@segiddins I'm not familiar with Molinillo resolver. Please describe what changes  between old version and new version at next time.

**Comment by segiddins** [comment]
@hsbt no relevant changes, just performance improvements as described in the molinillo changelog

**Comment by drbrain** [comment]
[Molinillo ChangeLog for 0.4.0](https://github.com/CocoaPods/Molinillo/blob/master/CHANGELOG.md#040-2015-07-27)

**Comment by segiddins** [comment]
Looks like merging this broke a test on 1.8.7. Will investigate when I get time, sorry :(

**Pull request merged**
