### PR TITLE
Use docker for ruby master

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

RVM is too heavy for us. I try to use the docker environment in GitHub Actions.
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@hsbt how RVM is to heavy to us compared to Docker?

**Comment by deivid-rodriguez** [comment]
I agree using docker is better. It doesn't require workarounds like the ones I added in #2957, and we don't need to download RVM, install it, install ruby-head, and enable rvm. With docker with have ruby's master branch ready to use.

**Comment by deivid-rodriguez** [comment]
Rebased and improved :)

**Comment by deivid-rodriguez** [comment]
Rebased and improved :)

**Comment by deivid-rodriguez** [comment]
I'm going to squash and merge this PR now :+1:

**Comment by deivid-rodriguez** [comment]
@bundlerbot merge

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
@bundlerbot retry

**Comment by deivid-rodriguez** [comment]
@bundlerbot retry

**Comment by deivid-rodriguez** [comment]
I found the culprit, I had not removed the github check we're moving away from the RVM workflow, that was the reason why bors was timing out (since the workflow had been removed, the check was never being received).

Fixed that so I'll try again.

@bundlerbot retry

**Comment by deivid-rodriguez** [comment]
Yay! :tada:

**Pull request merged**
