### PR TITLE
Add deprecate command method

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:

This PR adds a `deprecate_command` method to deprecate RubyGems commands.

### Example
```ruby            
class Gem::Commands::QueryCommand
  extend Gem::Deprecate

  deprecate_command(2019, 12)

  def execute
    gem_names = Array(options[:name])

    if !args.empty?
      gem_names = options[:exact] ? args.map{|arg| /\A#{Regexp.escape(arg)}\Z/ } : args.map{|arg| /#{arg}/i }
    end

    terminate_interaction(check_installed_gems(gem_names)) if check_installed_gems?

    gem_names.each { |n| show_gems(n) }
  end
 ...
end
```

```shell
$ gem query
ebsocket-driver (0.7.1, 0.7.0, 0.6.5)
websocket-extensions (0.1.4, 0.1.3)
will_paginate (3.0.12)
xml-simple (1.1.5)
xmlrpc (0.3.0)
xpath (3.2.0, 2.1.0)
yajl-ruby (1.4.1)
yard (0.9.20, 0.8.7.6)
yell (2.2.0)
zeitwerk (2.1.10, 2.1.9, 2.1.8, 2.1.6, 2.1.2)
zlib (default: 1.0.0)

NOTE: query command is deprecated. It will be removed on or after 2019-12-01.
```

______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
Bundler specs failing 🤔 

@deivid-rodriguez @hsbt @duckinator what you think of adding this method in general?

**Comment by duckinator** [comment]
@bronzdoc I'm in favor of this being added, if there's commands that need to be deprecated. And I imagine there are, since the RubyGems codebase is 10+ years old.

**Comment by bronzdoc** [comment]
```
Summary:
    Query gem information in local or remote repositories

  Description:
    The query command is the basis for the list and search commands.

    You should really use the list and search commands instead.  This command
    is too hard to use.

  Defaults:
    --local --name-matches // --no-details --versions --no-installed
```

I'm thinking of the `query command` I wonder for how long have we been telling people to not to use it?

**Comment by duckinator** [comment]
Yeah, that seems worth deprecating, so I'd say it's worth adding `deprecate_command`.

**Comment by deivid-rodriguez** [comment]
Me too, I like the idea of `deprecate_command`. Haven't looked at the implementation though.

**Comment by hsbt** [comment]
@bronzdoc https://github.com/rubygems/rubygems/pull/2935/checks?check_run_id=239916853 is issue of GitHub Actions. It exceeded 6h of execution limit.

**Comment by bronzdoc** [comment]
@deivid-rodriguez @duckinator @hsbt what you think of of the implementation of this method? do you approve?

**Comment by duckinator** [comment]
@bronzdoc this looks good to me. :+1:

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
