### PR TITLE
Hurrying is bad

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Made a mistake in #3822. I'll try this one before merging it.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by djberg96** [comment]
@deivid-rodriguez There was a glitch in the matrix?

**Comment by deivid-rodriguez** [comment]
What do you mean?

**Comment by djberg96** [comment]
@deivid-rodriguez I was just making a little joke. :)

**Comment by deivid-rodriguez** [comment]
My mistake was the `matrix.ruby` is undefined in this workflow, since it has no matrix.

**Comment by deivid-rodriguez** [comment]
Ah lol :xD

**Comment by deivid-rodriguez** [comment]
Sorry, not used to some English expression :sweat_smile:

**Comment by deivid-rodriguez** [comment]
It sounds like we'll have to fix https://github.com/release-drafter/release-drafter/issues/564 if we want to use this :(

**Comment by deivid-rodriguez** [comment]
Made several tests and this seems to be working

In addition to what we already have, I added a task to modify the changelog according including the body of the draft release, and commit back the edits. For now, I'm not pushing anything until I validate changes are correct.

Only thing I wasn't able to test is the change in the configuration because the configuration seems to always be picked up from the default branch. So I'll merge this and see how it goes.

**Comment by jetersen** [comment]
@deivid-rodriguez See https://github.com/release-drafter/release-drafter/issues/564#issuecomment-1013866753 for a solution to release-drafter 😅

**Comment by deivid-rodriguez** [comment]
Great, I'll keep it in mind next time I try release-drafter. Thank you for your work ❤️.

**Pull request merged**
