### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**
## Make sure the following tasks are checked

- [ ] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [ ] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by deivid-rodriguez — APPROVED** [review]
Thank you @jbampton!

**Comment by deivid-rodriguez** [comment]
This is just a a change to a spec, so no need to backport it or include it in the changelog.

**Comment by hsbt** [comment]
I always applied typofix on ruby/ruby repository repeatedly Because a member of ruby core team fixes the miss-spelling every day. see https://github.com/ruby/ruby/commit/63849a1cd98c7ae3a7d6af3f69814f01dfae25ea

Is there strong reason why don't backport this?

**Comment by deivid-rodriguez** [comment]
I understand. No, there's no strong reason, we can backport all typo fixes from now on :+1:.

**Comment by hsbt** [comment]
Thanks ❤️

**Pull request merged**
