### PR TITLE
[Travis] Also build auto

### PR DESCRIPTION
**Pull request by segiddins**
@indirect sorry about this one!

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@indirect just updated the PR to ensure we install rake 10

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r-

**Comment by segiddins** [comment]
@homu r+

**Comment by indirect** [comment]
God dammit, everything is a disaster.

**Pull request merged**
