### PR TITLE
Fix rubygems dev env

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:

This will fix the rake error when running `rake test` on ruby version < 2.5
```
File does not exist: bundler

rake aborted!
Command failed with status (1)
```
the reason the error was happening is that `lib/rubygems/test_case.rb` is requiring bundler even on ruby version < 2.5 and  the `rake test`  task only include `bundler/lib` when ruby is >= 2.5  

Also made the `setup` task to be dependent of the `bundler:checkout` task so the bundler submodule is initialized properly on setup.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
this is failing in ruby 2.3.6 :scream_cat:

**Comment by hsbt** [comment]
I can reproduce your issue. When we have the environment without bundler, `rake test` was failed.

Should we apply this patch?

```
diff --git Rakefile Rakefile
index 07f0f799e3..292d5da63e 100644
--- Rakefile
+++ Rakefile
@@ -53,7 +53,7 @@ Rake::TestTask.new do |t|
   t.ruby_opts << '-rdevkit' if Gem.win_platform?
 
   t.libs << "test"
-  t.libs << "bundler/lib" if RUBY_VERSION >= "2.5"
+  t.libs << "bundler/lib"
   t.test_files = FileList['test/**/test_*.rb']
 end
```

**Comment by segiddins** [comment]
I think @hsbt’s patch is the right approach, versus disabling Bundler entirely

**Comment by bronzdoc** [comment]
I updated the PR, thanks for the review @hsbt @segiddins !

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
