### PR TITLE
Fix `gem install` crashing on gemspec with nil required_ruby_version

### PR DESCRIPTION
**Pull request by pbernays**
## What was the end-user or developer problem that led to this PR?

Installing a gem from GemFury in ruby 3.0.0 fails with ```undefined method `satisfied_by?' for nil:NilClass```

An inspection of the gemspec showed both `required_ruby_version` and `required_rubygems_version` were set to nil.

## What is your fix for the problem, implemented in this PR?

Took the fix for `required_rubygems_version` a step further and applied it to `required_ruby_version`

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by deivid-rodriguez — COMMENTED** [review]
Interesting. When I looked at this, I understood that `required_ruby_version` was present since the initial version of the spec, so this couldn't happen. After I second look, I still believe that's true, but even if that's the case, it seems like gems with this field set to `nil` still crept in, also confirmed by commits like this: https://github.com/rubygems/rubygems/commit/1b700ea30490e1376e2fb640b16bc7c216c6f6c3. So thanks for fixing this!

Could you make the following changes:

* Make a separate test analogous to the other one, instead of extending it.
* Add an already decompressed test file to keep it consistent with the previous test.
* Change the comment to mention that some marshalled specs where generated with this field set to `nil` instead of mentioning the `Gem::Specification` API version.

**Comment by deivid-rodriguez** [comment]
Oh, and you also need to run `rake update_manifest` to get the new test file added to the package.

**Comment by pbernays** [comment]
Not a problem. Since the test file is uncompressed, should I drop the `.rz` extension or would you prefer I leave as is?

**Comment by pbernays** [comment]
Ah, nvm. I see rubocop failing because it picks up the marshalled `.gemspec`. Will adjust the filenames.

**Review by deivid-rodriguez — APPROVED** [review]
Thank you!

**Pull request merged**
