### PR TITLE
Vendor latest `thor` with fixes for latest `did_you_mean` deprecations

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Ruby-core now includes a version of `did_you_mean` that prints some deprecation warnings for us, breaking that CI.

## What is your fix for the problem, implemented in this PR?

Fix the deprecations. If CI passes I will upstream the changes to `thor`.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Not sure if `DidYouMean.correct_error` is a new feature of something that was always possible. CI will tell, I guess.

**Comment by deivid-rodriguez** [comment]
@yuki24 Does https://github.com/rubygems/rubygems/pull/5202/commits/107477149e32e9b14e92b49d7e812da05633cb08 look correct to you?

**Comment by deivid-rodriguez** [comment]
Upstream PR is here: https://github.com/rails/thor/pull/761/.

**Comment by yuki24** [comment]
Thanks @deivid-rodriguez for taking care of this. Yes 1074771 looks great to me.

**Comment by deivid-rodriguez** [comment]
Alright, I'll merge this then, thank you @yuki24!!

**Pull request merged**
