### PR TITLE
Don't cleanup paths from gems already activated from `$LOAD_PATH`

### LINKED ISSUE #5016: URI constants & core dump. Problem with Bundler, Ruby, RubyGems, or ruby-install?
### Describe the problem as clearly as you can

So I noticed that Bundler is screwed up with URI reporting tons of re-initialized constant issues:

```
...
/home/user/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/mailto.rb:24: warning: already initialized constant URI::MailTo::COMPONENT
/home/user/.gem/ruby/3.0.2/gems/uri-0.11.0/lib/uri/mailto.rb:24: warning: previous definition of COMPONENT was here
/home/user/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/mailto.rb:52: warning: already initialized constant URI::MailTo::HEADER_REGEXP
/home/user/.gem/ruby/3.0.2/gems/uri-0.11.0/lib/uri/mailto.rb:52: warning: previous definition of HEADER_REGEXP was here
/home/user/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/mailto.rb:55: warning: already initialized constant URI::MailTo::EMAIL_REGEXP
/home/user/.gem/ruby/3.0.2/gems/uri-0.11.0/lib/uri/mailto.rb:55: warning: previous definition of EMAIL_REGEXP was here
```

I also get a core dump sometimes: [ruby_coredump.txt](https://github.com/rubygems/rubygems/files/7416421/ruby_coredump.txt).

### Did you try upgrading rubygems & bundler?

First, I tried just re-installing all of the infected Gems (URI, etc.), as well as Bundler.

Finally, I just trashed everything and re-installed Ruby completely.

### Post steps to reproduce the problem

First, here's the version of everything I'm using:
- `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]`
- `Bundler version 2.2.29`
- `gem -v => 3.2.22`
- `ruby-install: 0.8.3`
- `chruby: 0.3.9`

So I realize that ruby-install/chruby might be the issue, I deleted everything and re-installed these tools. Then I deleted all ~/.rubies and ~/.gem and did a fresh Ruby install of the latest version (v3.0.2):
- `ruby-install --latest ruby`
- `gem update`

Now, if you just use IRB by itself, there is no issue:

```
$ irb
irb(main):001:0> require 'uri'
```

But now go to any project, even a simple project, and try that. I made a new project using `bundle gem testme`:

```
$ bundle gem testme
$ cd testme

# Fix .gemspec file (remove TODOs).

$ bundle install
$ bundle update
$ bundle exec irb
irb(main):001:0> require 'uri'
/home/user/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/version.rb:3: warning: already initialized constant URI::VERSION_CODE
/home/user/.gem/ruby/3.0.2/gems/uri-0.11.0/lib/uri/version.rb:3: warning: previous definition of VERSION_CODE was here
/home/user/.rubies/ruby-3.0.2/lib/ruby/3.0.0/uri/version.rb:4: warning: already initialized constant URI::VERSION
/home/user/.gem/ruby/3.0.2/gems/uri-0.11.0/lib/uri/version.rb:4: warning: previous definition of VERSION was here
...
```

Now you can see the warnings.

To get the core dump is a bit more difficult, it requires using URI and parsing it, and maybe also using nokogiri?

If you want to get the core dump, you can download my project (quite huge) to see it:

```
$ git clone https://github.com/esotericpig/nhkore.git
$ cd nhkore
$ bundle install
$ bundle exec rake update_core
# Just type "n" for each option, and then has core dump.
```

Now, if I remove `require 'bundler/setup'` from my main `nhkore.rb` and run `rake update_core` then I never get a core dump. Note here that if I remove `require 'bundler/setup'` and then run `bundle exec rake update_core` then I still get a core dump.

So I only get issues if I use bundle/bundler. I never get issues when just using Ruby.

Because the core dump points to .so files, it seems easy to say a bad Ruby or a bad system, but it works completely fine without Bundler. It just doesn't work with Bundler. And just for good measure, I completely updated my system and a did a full system restart.

So I'm not sure if this is where Bundler just doesn't work with the newest version of Ruby or what's going on. I apologize also because wasn't sure where to post this issue. Thanks.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.2.29
  Platforms   ruby, x86_64-linux
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux]
  Full Path   /home/user/.rubies/ruby-3.0.2/bin/ruby
  Config Dir  /home/user/.rubies/ruby-3.0.2/etc
RubyGems      3.2.22
  Gem Home    /home/user/.gem/ruby/3.0.2
  Gem Path    /home/user/.gem/ruby/3.0.2:/home/user/.rubies/ruby-3.0.2/lib/ruby/gems/3.0.0
  User Home   /home/user
  User Path   /home/user/.gem/ruby/3.0.0
  Bin Dir     /home/user/.gem/ruby/3.0.2/bin
Tools         
  Git         2.31.1
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9

## Bundler Build Metadata

Built At          2021-10-08
Git SHA           4440b035ef
Released Version  true

### Gemfile

# encoding: UTF-8
# frozen_string_literal: true

source 'https://rubygems.org'

gemspec
```

### LINKED ISSUE #5108: StringIO in Passenger Issue Gem-Based
I'm having a problems.

My current problem is **readable/writable files & resulting Passenger fault**

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ x] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.32
  - RUBY VERSION: 2.7.4 (2021-07-07 patchlevel 191) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/rich/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/rich/.rbenv/versions/2.7.4/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/rich/.rbenv/versions/2.7.4/bin
  - SPEC CACHE DIRECTORY: /Users/rich/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/rich/.rbenv/versions/2.7.4/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-21
  - GEM PATHS:
     - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0
     - /Users/rich/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/rich/.rbenv/versions/2.7.4/bin
     - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
     - /Users/rich/.rbenv/shims
     - /opt/homebrew/opt/postgresql@12/bin
     - /Users/rich/.rbenv/shims
     - /Users/rich/RF/RFS/Sourcer
     - /users/rich/RF/RFS/Dev
     - /Users/rich/.rbenv/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
```

Mac Mini M1 using MacOS Monterey 12.0.1

`Passenger` is giving me an error after an update to my system, which updates `gems` and `homebrew`.

```
Error: The application encountered the following error: superclass mismatch for class StringIO (TypeError)
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/2.7.0/openssl/config.rb:14:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/2.7.0/openssl/config.rb:14:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/2.7.0/openssl.rb:18:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/2.7.0/openssl.rb:18:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/cookie.rb:3:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/cookie.rb:3:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1809:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1809:in `<class:Base>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:909:in `<module:Sinatra>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:22:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:26:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:26:in `<module:Sinatra>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:1:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra.rb:1:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra.rb:1:in `<top (required)>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:60:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:60:in `block (2 levels) in require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:55:in `each'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:55:in `block in require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:44:in `each'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:44:in `require'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/bundler.rb:175:in `require'
    /Users/rich/Sites/HQ/app.rb:4:in `<top (required)>'
    config.ru:4:in `require'
    config.ru:4:in `block in <main>'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
    /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:101:in `eval'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /opt/homebrew/Cellar/passenger/6.0.12/libexec/src/helper-scripts/rack-preloader.rb:29:in `<main>'
```

I've already discussed this with the `Passenger` people.  https://github.com/phusion/passenger/issues/2395

Also `ruby-build`.  https://github.com/rbenv/ruby-build/issues/1826

The above error dictates `Passenger` has run into an app problem.  It's just `ruby` and `gems` inside.  `Bundler` throws this error report:

```
>> 15:46:52 rich@HQ3 hq ➜ bundle doctor
The Gemfile's dependencies are satisfied
Files exist in the Bundler home that are not readable/writable by the current user. These files are:
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/.autotest
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/History.rdoc
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/Manifest.txt
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/README.rdoc
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/Rakefile
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/design_rationale.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/hoe/minitest.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/assertions.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/autorun.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/benchmark.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/expectations.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/hell.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/mock.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/parallel.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/pride.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/pride_plugin.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/spec.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest/unit.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/lib/minitest.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/metametameta.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_assertions.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_benchmark.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_mock.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_reporter.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_spec.rb
 - /Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/minitest-5.14.4/test/minitest/test_minitest_test.rb
The following gems are missing OS dependencies:
 * date: /usr/lib/libSystem.B.dylib
 * nokogiri: /usr/lib/libSystem.B.dylib
 * nokogiri: /usr/lib/liblzma.5.dylib
 * nokogiri: /usr/lib/libobjc.A.dylib
 * pg: /usr/lib/libSystem.B.dylib
 * racc: /usr/lib/libSystem.B.dylib
 ```

So `bundle install` shows `gems` it can't handle as well as missing libraries.  So is it that some `gems` need rebuilding for **Apple Silicon**?  There are so many parties involved, I don't know who to ask.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

If a default gem is required before `bundler/setup` is required, and also after, there's a chance that two different versions will get activated:

* The one that gets required before `bundler/setup` will use rubygems' require and thus be the latest version installed.
* The one that gets required after `bundler/setup` will use ruby's require and thus will be the default version installed.

This will cause at redefinition warnings, or even worse, runtime errors or segfaults.

## What is your fix for the problem, implemented in this PR?

The reason this happens is that bundler, before adding all the paths for all dependencies in the Gemfile to the `$LOAD_PATH`, first cleans up paths from gems already present in the `$LOAD_PATH`. However, if paths from gems are already present there, that probably means those gems have already been required and as a result, removing those paths from the `$LOAD_PATH` will cause more harm than good.

I want to experiment with no longer doing this cleanup, so that we fix redefinition warnings caused by default gems and consistently use whatever version was required in the first place.

This solution was first suggested by @mvz at https://github.com/ruby/pathname/issues/12#issuecomment-946605635.

Closes #5108.
Closes #5016.
Closes https://github.com/ruby/pathname/issues/12.
Closes https://github.com/ruby/pathname/issues/14.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Actually @mvz's suggestion was more conservative and was to avoid removing paths from gems already activated, and could be implemented by something like this I think:

```diff
diff --git a/bundler/lib/bundler/shared_helpers.rb b/bundler/lib/bundler/shared_helpers.rb
index 405ade95dd..41d2adf08d 100644
--- a/bundler/lib/bundler/shared_helpers.rb
+++ b/bundler/lib/bundler/shared_helpers.rb
@@ -318,7 +318,8 @@ def clean_load_path
       loaded_gem_paths = Bundler.rubygems.loaded_gem_paths
 
       $LOAD_PATH.reject! do |p|
-        next if resolve_path(p).start_with?(bundler_lib)
+        resolved_path = resolve_path(p)
+        next if resolved_path.start_with?(bundler_lib) || $LOADED_FEATURES.any? {|lf| lf.start_with?(resolved_path) }
         loaded_gem_paths.delete(p)
       end
       $LOAD_PATH.uniq!
```

But I don't think we need to mess up with cleaning the `$LOAD_PATH` at all?

**Comment by deivid-rodriguez** [comment]
Alright, I decided to go with the more conservative approach in the end. This should fix all redefinition issues when new versions of default gems are released.

**Comment by deivid-rodriguez** [comment]
This has been confirmed to fix issues at https://github.com/ruby/pathname/issues/12 and I also confirmed it fixes #5016 manually, so merging.

**Comment by mvz** [comment]
Thanks, @deivid-rodriguez!

**Comment by deivid-rodriguez** [comment]
No problem!

**Pull request merged**
