### PR TITLE
Fix metadata requirements being bypassed when custom gem servers are used

### LINKED ISSUE #5251: When using gem servers not implementing Compact Index endpoints, bundler may end up installing variants incompatible with the running ruby version
### Describe the problem as clearly as you can

This is just a placeholder ticket that I will fill up as we know more about the issue. It was first reported at https://github.com/sparklemotion/nokogiri/issues/2397.

### Did you try upgrading rubygems & bundler?

Yes, people running into this are still running into this with the lates versions of bundler & rubygems.

### Post steps to reproduce the problem

The closest we have so far to a repro is [this comment](https://github.com/sparklemotion/nokogiri/issues/2397#issuecomment-1002820961).

### Which command did you run?

`bundle install` on Ruby 3.1, on a `Gemfile` sourcing `nokogiri` from a gem custom source not implementing the Compact Index API.

### What were you expecting to happen?

A compatible version of nokogiri is installed.

### What actually happened?

An incompatible version of nokogiri is installed.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Sometimes, when using custom gem servers, some gems may end up being installed that are not compatible with the running ruby or rubygems version.

## What is your fix for the problem, implemented in this PR?

My fix to download the full gemspec from the marshaled index when we need to check metadata requirements for gem sources not implementing the compact index API, so that resolution is still correct.

Fixes #5251.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@simi I think this branch should fix the issue you were having! Can you try it?

**Comment by simi** [comment]
@deivid-rodriguez I'm on it.

**Comment by simi** [comment]
I can confirm this works.

testing case

```dockerfile
FROM ruby:3.1.0

# Gemfile updated manually from Ruby 3.0.1 to 3.1.0
RUN echo "source 'http://latest-private-geminabox-server'\n\
\n\
ruby '3.1.0'\n\
\n\
gem 'nokogiri', '1.12.5'\n" > Gemfile

# old lock from 3.0.1
RUN echo "GEM\n\
  remote: http://latest-private-geminabox-server/\n\
  specs:\n\
    mini_portile2 (2.6.1)\n\
    nokogiri (1.12.5)\n\
      mini_portile2 (~> 2.6.1)\n\
      racc (~> 1.4)\n\
    racc (1.6.0)\n\
\n\
DEPENDENCIES\n\
  nokogiri (= 1.12.5)\n\
\n\
RUBY VERSION\n\
   ruby 3.0.1p64\n\
\n\
BUNDLED WITH\n\
   2.2.32\n" > Gemfile.lock

RUN bundle update --bundler
RUN cat Gemfile.lock
RUN ruby -rnokogiri -e "puts Nokogiri"
```

fails with (invalid platform gem is installed)

```
...
Step 4/6 : RUN bundle update --bundler                                                                                                                                                        
 ---> Running in ce86f62c745b                                                                                                                                                                 
Fetching gem metadata from http://gems.fuga.com:9292/....                                                                                                                                     
Resolving dependencies...                                                                                                                                                                     
Using bundler 2.3.3                                                                                                                                                                           
Using racc 1.6.0                                                                                                                                                                              
Fetching nokogiri 1.12.5 (x86_64-linux)                                                                                                                                                       
Installing nokogiri 1.12.5 (x86_64-linux)                                                                                                                                                     
Bundle updated!                               
...
Step 6/6 : RUN ruby -rnokogiri -e "puts Nokogiri"                                             
 ---> Running in cf479e79978a 
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/extension.rb:4:in `<top (required)>'
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri.rb:11:in `require_relative'                                                                                     
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri.rb:11:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'                                                                              
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'                                                                                        
/usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/extension.rb:7:in `require_relative': cannot load such file -- /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogi
ri/3.1/nokogiri (LoadError)                                                                   
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri.rb:11:in `require_relative'
        from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri.rb:11:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- nokogiri (LoadError)
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
The command '/bin/sh -c ruby -rnokogiri -e "puts Nokogiri"' returned a non-zero code: 1       
```

Adding this before `RUN bundle update --bundler` line fixes this problem by installing proper ruby platform gem.

```
RUN git clone git://github.com/rubygems/rubygems --branch fix-metadata-bypassed --depth=1 && cd rubygems/bundler && gem build bundler.gemspec && gem install bundler-2.4.0.dev.gem 
```

**Comment by deivid-rodriguez** [comment]
Awesome, may I merge this then?

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Thank you! 💪

**Comment by deivid-rodriguez** [comment]
@flavorjones Do you think we should release this immediately? As far as I understand, once nokogiri releases precompiled gems supporting ruby 3.1, this will be no longer hit, but I can make a release now including this, to "stop the bleeding" until that happens. It seems pretty bad to me that we may allow incompatible gems to be installed 😬.

**Comment by flavorjones** [comment]
@deivid-rodriguez Thanks for asking. I don't feel like it's an urgent hair-on-fire problem, and hopefully Nokogiri will ship today or tomorrow.

**Pull request merged**
