### PR TITLE
Backport r58741 from ruby/ruby repository

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

I cherry-picked fd leak fix for Windows from ruby core repository. 

Original commit is here: https://github.com/ruby/ruby/commit/66b54b1a4ae9f3d38c47e23ecec6a40c07a80c21
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
@hsbt please don't open a separate PR to both master and the stable branch -- commits are manually cherry-picked back when a patch release is made, ensuring the commit on the release branch has a reference to the authoritative commit (on master)

**Comment by hsbt** [comment]
> please don't open a separate PR to both master and the stable branch

I see. But I'm not sure how backport to stable(2.6) branch. Can I direct push cherry-picking commits to stable branch? Should I notify these commits to you?

**Comment by segiddins** [comment]
I pick them out when making patch releases, at the time of release

**Comment by hsbt** [comment]
Make sense. Please ping me when it's time of stable release.

**Pull request closed without merging**
