### PR TITLE
Better CI job names

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Our CI configuration uses exact versions. This helps us with the determinism of our CI, making it less dependent on external changes, following the principle that CI should fail if and only if the code inside a PR breaks something.

However, since exact versions are used to build job names, that means every time we bump the tested versions, the job names change and we have to change our protected branch configuration to enforce the checks with the new names.

## What is your fix for the problem, implemented in this PR?

With these changes I expect to keep the best of both worlds: CI determinism, and stable and descriptive job names.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by simi — APPROVED** [review]
> However, since exact versions are used to build job names, that means every time we bump the tested versions, the job names change and we have to change our protected branch configuration to enforce the checks with the new names.

If I understand it well, this is the reason why this PR hangs for jobs to wait, which will never happen since they are renamed now. Let's :pray: after merge last settings tweak will be needed because of this.

**Comment by deivid-rodriguez** [comment]
Yes, in order to make this PR get a green state, I'll have to go to the protected branches configuration and change all of the required checks to be the new ones.

But this is the last time we'll have to do this! :tada:

**Comment by deivid-rodriguez** [comment]
imagen

:tada: :tada: :tada: :tada: :tada: :tada:

**Comment by deivid-rodriguez** [comment]
I'll go ahead now, uncheck a bunch of checkboxes, then check a bunch of checkboxes and then merge :)

**Comment by deivid-rodriguez** [comment]
Oh wow, I changed the windows bundler workflow to use exact versions, since it was the only workflow not using them and... I got a segfault :open_mouth:.

**Comment by deivid-rodriguez** [comment]
Not sure what happened there, I suspect a bad tools cache in the github actions environment. I'm going to ignore it since I don't think it will come up again.

**Pull request merged**
