### PR TITLE
[DOC] Remove (newly unneeded) remarks about aliases

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Rdoc now notes aliases.

### CODE REVIEW

**Comment by simi** [comment]
:wave: @BurdetteLamar. Thanks for the PR. Is there any reason to pull in only this change? `fileutils` are vendored and could be updated using `rake vendor:fileutils`. It will pull in version specified in Rake file (currently `v1.7.0`). For example this change is also missing https://github.com/ruby/fileutils/commit/8af16ba57c4e68a7ee40e665c4b09fadbf9acc5e compared to current fileutils master.

Would it make sense to wait for new release of fileutils and then pull in all changes?

**Comment by BurdetteLamar** [comment]
> 👋 @BurdetteLamar. Thanks for the PR. Is there any reason to pull in only this change? `fileutils` are vendored and could be updated using `rake vendor:fileutils`. It will pull in version specified in Rake file (currently `v1.7.0`). For example this change is also missing [ruby/fileutils@8af16ba](https://github.com/ruby/fileutils/commit/8af16ba57c4e68a7ee40e665c4b09fadbf9acc5e) compared to current fileutils master.
> 
> Would it make sense to wait for new release of fileutils and then pull in all changes?

Agnostic on that.  Whatever y'all think best.

**Comment by deivid-rodriguez** [comment]
Unless there's an immediate benefit of pulling from master now (which we have done many times and it would be fine too), I think we can update this PR next time fileutils is released and pull everything.

Thanks for this @BurdetteLamar, by the way! :)

**Comment by BurdetteLamar** [comment]
> Unless there's an immediate benefit of pulling from master now (which we have done many times and it would be fine too), I think we can update this PR next time fileutils is released and pull everything.
> 
> Thanks for this @BurdetteLamar, by the way! :)

Works for me!

**Pull request closed without merging**
