### PR TITLE
Permission options

### PR DESCRIPTION
**Pull request by nobu**
# Description:
Add :dir_mode, :prog_mode, and :data_mode options to Gem.install.

These options would be useful to support same options of `rbinstall.rb`.
______________

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@nobu Is not the patch below necessary, too?

```
diff --git lib/rubygems/installer.rb lib/rubygems/installer.rb
index 0c58c29ac9..b46ab0e71f 100644
--- lib/rubygems/installer.rb
+++ lib/rubygems/installer.rb
@@ -110,6 +110,10 @@ class Gem::Installer
   class FakePackage
     attr_accessor :spec
 
+    attr_accessor :dir_mode
+    attr_accessor :prog_mode
+    attr_accessor :data_mode
+
     def initialize(spec)
       @spec = spec
     end
```

**Comment by duckinator** [comment]
@nobu once tests pass, this looks good to me! I think the test failures should be resolved by @hsbt's suggestion.

**Comment by hsbt** [comment]
@nobu Some tests on appveyor was fsiling status: https://ci.appveyor.com/project/segiddins/rubygems/build/1278/job/l0enm8one677pah7

Can you investigate and fix them?

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
