### PR TITLE
Revert deprecation of deprecate method for now.

### PR DESCRIPTION
**Pull request by simi**
follow-up of #3530, https://github.com/rubygems/rubygems/pull/3530#discussion_r411419721

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I'll let @bronzdoc merge this to make sure that he's inline with our plan :+1:.

**Comment by bronzdoc** [comment]
What's the plan? 

@deivid-rodriguez can you elaborate on https://github.com/rubygems/rubygems/pull/3530#discussion_r412015428?

**Comment by deivid-rodriguez** [comment]
The plan is to leave things unchanged our users for now until we have a better alternative. The comment you linked to is just a rough idea that needs to be properly explored.

**Comment by bronzdoc** [comment]
I don't see an easier way than this right now, but ok let's think about it a little more before affecting the end users...

I'll try to come up with something.

**Comment by deivid-rodriguez** [comment]
I opened #3539 to follow up.

**Pull request merged**
