### PR TITLE
Warn on similar to known rubygem sources

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Migrated from https://github.com/rubygems/bundler/pull/7647

/cc @kddeisz

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by kddeisz** [comment]
Ahh sorry didn't realize it was over here now. I've added this and more functionality into the gem here: https://github.com/kddeisz/gemfilelint. I'd be happy to put all of this into bundler, just wasn't sure how it would be received. Let me know what y'all think.

**Comment by hsbt** [comment]
@kddeisz 👍 

I will close this. When you hope to integrate it to bundler, Please file the new pull-request. Thanks.

**Comment by deivid-rodriguez** [comment]
@hsbt Was closing this correct? Your message sounds to me that you wanted to close the PR in the original repository, so that it's migrated to the new repo, but this PR is already migrated :thinking:.

**Comment by hsbt** [comment]
Ah, my intention are:

* This PR is only transferring, not continue to work.
* https://github.com/kddeisz/gemfilelint is good to me. I have no motivation to migrate it to bundler.
* But @kddeisz still hope to migrate it to bundler, I did suggest to create the new PR because this pr is not modified by contributor.

**Comment by deivid-rodriguez** [comment]
I understand now :+1:.

**Comment by kddeisz** [comment]
Thanks @hsbt!

**Pull request closed without merging**
