### PR TITLE
Revert cadb66 and deprecate specification autorequire 

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
See: https://github.com/rubygems/rubygems/pull/2832
______________
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by duckinator** [comment]
@bronzdoc looks like this is failing because of the new deprecation notes.

**Comment by hsbt** [comment]
We should remove to refer `autorequire` on bundler at first.

@bronzdoc Can you update this pull request only revert cadb66 and create the new pull-request with deprecation warning? Maybe, removing `autorequire` of bundler is difficult.

**Comment by bronzdoc** [comment]
Will do @hsbt

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
