### PR TITLE
[Requirement] Memoize to_s, as_list, hash

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Makes using requirements as hash keys faster, as well as `Requirement#==`, though I'm not sure if this is worth it

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by djberg96** [comment]
Looks reasonable to me.

**Comment by segiddins** [comment]
@indirect said he'd try this on a very large gemfile to see the performance impact

**Comment by segiddins** [comment]
Anyone opposed to shipping this?

**Comment by indirect** [comment]
In my testing, across 20 runs total, with a Gemfile containing ~500 gems: `bundle exec ruby -e 0` takes ~850ms with this PR, and takes ~800ms without this PR.

**Comment by segiddins** [comment]
:( guess we should close this then

**Comment by indirect** [comment]
Give me another hour, I want to try a more reliable benchmark.

**Comment by indirect** [comment]
So I did some slightly more sound benchmarking using `readygo`, and it looks like the difference is solidly reproducible, albeit a tiny bit smaller than I thought: 810-815ms without this patch, and 850-860ms with this patch.

**Comment by duckinator** [comment]
This code in this PR has been untouched for half a year, the comments have had no activity for months, and the last comment said it made performance worse, so I'm closing it.

**Pull request closed without merging**
