### PR TITLE
Use SHA256 in test certificates

### PR DESCRIPTION
**Pull request by jackorp**
## What was the end-user or developer problem that led to this PR?

CentOS 9 Stream / RHEL 9 (Fedora will follow as well) are disabling SHA1 digest in default allowed crypto configuration. Most operations with certificates (such as signing content with them) fail. Operations with SHA1 also fail in the test suite ran as part of the whole Ruby test suite.

Fixes https://github.com/rubygems/rubygems/issues/5454

## What is your fix for the problem, implemented in this PR?

Regenerate certificates using SHA256, using `util/create_certs.rb` with SHA256 as the hash instead of SHA1.

I have corrected most failures that cropped up as a result of regenerated certificates, but there are 2 tests that still fail because they are using SHA1:
`TestGemPackage#test_build_auto_signed_encrypted_key` and `TestGemPackage#test_build_signed_encrypted_key`

They are using a certificate and key that I am not sure where they are generated (or how): `test/rubygems/data/gem-public_cert.pem` and `gem-private_key.pem`

I'll try to add these certificates to the `util/create_certs.rb` tool.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes (We are fixing tests themselves here)
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by jackorp** [comment]
Set as draft to have preview of the work, and I'd like to update certs also for the `TestGemPackage#test_build_signed_encrypted_key`

**Comment by deivid-rodriguez** [comment]
This fixes #5454 right, @jackorp? Thanks!

@simi Do you have time to review this? I saw that you self-assigned that issue, and also I've seen you working on other OpenSSL things around, so maybe you have better context.

**Comment by jackorp** [comment]
Yes, it fixes that issue. I have run builds to confirm this, and those builds passed.

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Thanks so much @jackorp!

**Pull request merged**
