### PR TITLE
Add error message when trying to open a default gem

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:

closes https://github.com/rubygems/rubygems/issues/2281

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
I'm not sure why the windows builds are failing :confused:

**Comment by hsbt** [comment]
@bronzdoc appveyor has an environmental problem. We can merge pull request without appveyor result.

**Comment by MSP-Greg** [comment]
@bronzdoc @hsbt

> appveyor has an environmental problem

They're aware of it.  I helped a bit with a PS script to get things updated.  I believe they'll be updating everything to 2.7.7 along with minitest, rake, and test-unit.

Greg

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
