### PR TITLE
Make `--default` and `--install-dir` options to `gem install` play nice together

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

These options are probably not really used in real life together, but I happened to need them while writing a spec for a bundler issue fix. In particular, for https://github.com/rubygems/rubygems/issues/3757.

## What was the end-user or developer problem that led to this PR?d

The problem is that when `--default` and `--install-dir` options are given to `gem install`, the default specification file should be installed to the `specifications/default` folder in `install-dir`, not to the one in the default gem directory.

## What is your fix for the problem, implemented in this PR?

The fix seemed really simple, but due to the cumbersome setup of rubygems tests, it broke a lot of tests, so I had to refactor rubygems test setup to play nice with the change. More information is given in the individual commits.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
Basically it seems good. I will check the behavior changes of the default gems installation.

**Comment by deivid-rodriguez** [comment]
@hsbt Did you have time to look at this? I don't think it should affect any realworld behavior since it's a very niche combination of flags. In any case, if it would affect I believe it's too fix a bug so it's fine.

But great to double check of course :+1:.

**Comment by hsbt** [comment]
Sorry, I'm working on RubyKaigi takeout 2020 as stuff in this week. I'll review this after that 🙇

**Comment by deivid-rodriguez** [comment]
Sure, thanks! And keep up the good work :muscle:.

**Comment by deivid-rodriguez** [comment]
@hsbt friendly ping :)

**Review by hsbt — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Thanks so much @hsbt!

**Pull request merged**
