### PR TITLE
Use TEST_SSL env var on CIs instead of TRAVIS env var.

### PR DESCRIPTION
**Pull request by simi**
followup of https://github.com/rubygems/rubygems/pull/1590#issuecomment-213495005

### CODE REVIEW

**Comment by simi** [comment]
UGH, Appveyor is failing. I'll inspect.

**Comment by djberg96** [comment]
@simi, I see some odd warnings when running this on my 8.1 VM, but the tests passed anyway.

```
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rubygems_plugin: Invalid a
rgument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rubygems_plugin.rb: Invali
d argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rubygems_plugin.so: Invali
d argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rubygems_plugin: Invalid a
rgument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rubygems_plugin.rb: Invali
d argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rubygems_plugin.so: Invali
d argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rubygems_plugin: Invalid argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rubygems_plugin.rb: Invalid argument

C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rubygems_plugin.so: Invalid argument

Gem::Indexer tests are being skipped.  Install builder gem.
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rdoc/discover: Invalid arg
ument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rdoc/discover.rb: Invalid
argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/bigdecimal-1.2.6/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/bigdecimal-1.2.6/rdoc/discover.so: Invalid
argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rdoc/discover: Invalid arg
ument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rdoc/discover.rb: Invalid
argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/io-console-0.4.3/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/io-console-0.4.3/rdoc/discover.so: Invalid
argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rdoc/discover: Invalid argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rdoc/discover.rb: Invalid argument
C:/Users/Daniel/Repositories/rubygems-djberg96/lib/rubygems/basic_specification.rb:270: warning: do_stat: C:/Ruby22/lib/ruby/gems/
2.2.0/gems/psych-2.0.8/C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/psych-2.0.8/rdoc/discover.so: Invalid argument
Run options: --seed 44369
```

**Comment by djberg96** [comment]
There's clearly something horribly wrong with those paths. It's like two full paths have been squished together.

**Comment by simi** [comment]
@djberg96 do you think those warnings and errors are caused by my change?

**Comment by djberg96** [comment]
@simi No, I'm seeing that stuff on master, with or without the TEST_SSL env variable set.

**Comment by djberg96** [comment]
@simi I think it's an issue with the Rakefile. I gutted it, and replaced it with just this:
```
require 'rake'
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.test_files = FileList['test/rubygems/test*']
  t.libs << 'util'
  t.libs << 'test'
end
```
And those warnings all went away. I haven't investigated further and will be out for a while, but I would look at the Rakefile to see what might be causing the issue.

**Comment by simi** [comment]
I was about to inspect Rakefile in next iteration since it looks like really messy and it will be nice to keep it clean as much as it is possible.

**Comment by simi** [comment]
@djberg96 do you see https://ci.appveyor.com/project/simi/rubygems/build/3? My change is probably breaking build, but I have no idea what's the reason. Let me inspect and fix.

**Pull request closed without merging**
