### PR TITLE
Follow up to addition of head build slack notifications

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

This is a followup to #3573.

* I'm adding some missing `if: always()` because some steps need to run unconditionally.
* Also doing some trickery so that initial artifacts are uploaded.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Initial artifacts have been uploaded. Now I'm going to test the notification once on push.

**Comment by deivid-rodriguez** [comment]
I'm going nuts with this :rofl:. @bronzdoc Have you added the `SLACK_WEBHOOK_URL` secret?

**Comment by bronzdoc** [comment]
@deivid-rodriguez lol yes

**Comment by deivid-rodriguez** [comment]
@bronzdoc There's one remaining issue here that I couldn't figure out where the initial artifact download wouldn't find any artifacts, while a previous upload had been successful. I'm not sure what's going on, but maybe it will be fixed once the task is run on the default bracnh :man_shrugging:.

So I'm going to merge this to try.

Something else I decided to change is to only notify when status changes from "passing" to "broken" because the opposite case (from "broken" to "passing") should be verified from the PR that fixes it, so I think it's not necessary.

**Comment by bronzdoc** [comment]
Lets try this

**Comment by deivid-rodriguez** [comment]
Ok, so unfortunately, I misunderstood how Github Actions artifacts work, and it turns out we can't use them for this.

Artifacts are used to shared data between jobs in the same workflow, not between different workflows, which is what we're trying to do here :(

To do what we want to achieve here we can:

* Use an external service, like s3.
* Use github API to check the latest status: https://developer.github.com/v3/actions/workflow-runs/#list-workflow-runs-for-a-repository.

I'll revert these changes for now and reopen the associated ticket.

**Comment by deivid-rodriguez** [comment]
Made a bit of digging into the API. I think we can get the last status with something like:

```
curl -S "https://api.github.com/repos/rubygems/rubygems/actions/runs?event=schedule&branch=master" |jq '.workflow_runs | map(select(.workflow_id == 716807)) | .[0].conclusion'
```

Samething for `bundler` but changing the id.

**Pull request merged**
