### PR TITLE
Add raw spec method to gem package

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Move `get_metadata` method in `unpack_command.rb` to `Gem::Package`
Then rename it to `raw_spec`, since the old `get_metadata` method returned more than metadata...
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by simi** [comment]
@bronzdoc are you on run to remove `TODO`s from code?

**Comment by bronzdoc** [comment]
> @bronzdoc are you on run to remove TODOs from code?
 Yes @simi

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Pull request merged**
