### PR TITLE
set rubocop to ignore Molinillo and set target ruby version to 2.2

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

This PR is fixing a couple of issues in Rubocop that is preventing PRs from being merged.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@colby-swandale I found the issue, see #2356.

**Comment by deivid-rodriguez** [comment]
Actually the PR can be merged right away since the issue has been fixed on master. Your awesome bot should be able to handle this without further intervention, I think.

**Comment by hsbt** [comment]
@deivid-rodriguez I agreed with your comment. But the all of contributors got the error of Travis CI until the issue has been fixed. It reduces developer experiences.

**Comment by MSP-Greg** [comment]
@hsbt @deivid-rodriguez

> Actually the PR can be merged right away since the issue has been fixed on master.

Just ran it on master locally, with & without rake.  This issue does appear to have been fixed., as in `320 files inspected, no offenses detected`.  There are 20 Molinillo files..

The tests for this were ran 14 hours ago, there has since been two commits re rubocop, both passing.

**Comment by indirect** [comment]
Let's give it a try. @bundlerbot r+

**Comment by colby-swandale** [comment]
🎉

**Comment by deivid-rodriguez** [comment]
> Let's give it a try.

Hehe, that's what I meant, bundlerbot rocks!

**Pull request merged**
