### PR TITLE
add PR welcome message

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

I've been meaning to do this for a while now. I want to introduce a welcome bot for new contributors. Instead of having the node app that i built a while go, it will instead be run by [probot](https://probot.github.io/apps/welcome/).

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by colby-swandale** [comment]
Note that i have not installed the app yet, i'll install it after this PR is merged.

**Comment by colby-swandale** [comment]
I wouldn't replace the PR template with this, but i defs think it's worth improving the template as well.

**Comment by bronzdoc** [comment]
I just think the `Tasks:` part is useless other than that i'm ok.

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
