### PR TITLE
Version numbers may be two-digits.

### PR DESCRIPTION
**Pull request by unak**
# Description:

Version numbers may be two-digits.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends
- [ ] [Squash commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
In theory they can be, but I don't believe there have been any multi-digit ruby versions yet?

**Comment by segiddins** [comment]
Either way, :+1:

**Comment by unak** [comment]
@segiddins You will be able to get the first muiti-digit version ruby within a day :-)

**Comment by segiddins** [comment]
@unak :sob: thanks for the PR

@homu r+

**Pull request merged**
