### PR TITLE
Have "gem update --system" pass through the --silent flag.

### PR DESCRIPTION
**Pull request by duckinator**
# Description:

Attempt at fixing #2907.

## What was the end-user or developer problem that led to this PR?

`gem update --system --silent` did not work.

## What is your fix for the problem, implemented in this PR?

If `gem update --system` gets `--silent`, pass it through to `setup.rb`.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by duckinator** [comment]
I'm not sure how to test this, even manually, so I haven't confirmed this works.

cc @deivid-rodriguez @MSP-Greg

**Comment by MSP-Greg** [comment]
> I'm not sure how to test this, even manually

Apply the patch to your current RG install, then `gem update --system --silent`.

It works, and it's really silent, as in nothing.  I have not looked at the code, something might be helpful, as in:
```
Bundler 2.1.4 installed
RubyGems 3.1.4 installed
RubyGems installed the following executables:
        C:/Greg/Ruby25-x64/bin/gem
        C:/Greg/Ruby25-x64/bin/bundle
```

But, one can always see that by not using `--silent`, so not important...  Thanks.

**Comment by MSP-Greg** [comment]
This is off-topic, but instead of all the standard output that is essentially a change log, might that just be replaced with a link/URI?  Just output the info shown above and the link...

**Comment by duckinator** [comment]
@MSP-Greg I would like something between the changelog-dump and silence, too, but yeah that's a separate issue.

**Comment by bronzdoc** [comment]
@duckinator you might want to add a test in `test_gem_commands_update_command.rb`, alot of the examples there set the `system` flag so as David mentioned is a matter of test for an empty output.

Thanks so much for this ❤️

**Comment by duckinator** [comment]
I think this is ready now. :+1:

**Pull request merged**
