### PR TITLE
Take into account just git tracked files in update_manifest rake task

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Ignore untracked files in `rake update_manifest`
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by simi** [comment]
_just to notice there's typo in first commit message_

**Comment by bronzdoc** [comment]
@deivid-rodriguez what you think?

**Comment by deivid-rodriguez** [comment]
I think this task is overcomplicated, because we're essentially keeping a list of git exclusions in two different places, `.gitignore`, and the `exclude` array. What about something like this?

```diff
diff --git a/Rakefile b/Rakefile
index a054dc8ec..a69bbb3aa 100644
--- a/Rakefile
+++ b/Rakefile
@@ -374,15 +374,12 @@ end
 desc "Update the manifest to reflect what's on disk"
 task :update_manifest do
   files = []
-  require 'find'
-  untracked_files = `git ls-files --others --exclude-standard`
-  exclude = %r[/\/tmp\/|\/pkg\/|CVS|\.DS_Store|\/doc\/|\/coverage\/|\.svn|\.git|TAGS|extconf.h|\.bundle$|\.o$|\.log$/|\./bundler/(?!lib|man|exe|[^/]+\.md|bundler.gemspec)]ox
-
-  untracked_files = untracked_files.split("\n").map {|file| "./#{file}"}
+  exclude = %r[\.git|\./bundler/(?!lib|man|exe|[^/]+\.md|bundler.gemspec)]ox
+  tracked_files = `git ls-files --recurse-submodules`.split("\n").map {|f| "./#{f}" }
 
-  Find.find(".") do |path|
+  tracked_files.each do |path|
     next unless File.file?(path)
-    next if path =~ exclude || untracked_files.include?(path)
+    next if path =~ exclude
     files << path[2..-1]
   end
   File.open('Manifest.txt', 'w') {|f| f.puts(files.sort) }
```

**Comment by bronzdoc** [comment]
@deivid-rodriguez done, thanks for the feedback

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
