### PR TITLE
Add Ruby Together CTA, rearrange README a bit

### PR DESCRIPTION
**Pull request by mrb**
# Description:

Adds a CTA to the Ruby Together site. /c @indirect 

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Please use `.md` instead of markdown, and you'll need to change the manifest for the rename

**Comment by mrb** [comment]
@segiddins :+1: Done!

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by indirect** [comment]
oh, right. @homu r+

**Pull request merged**
