### PR TITLE
Support running with frozen string literals

### LINKED ISSUE #1406: Ensure compatibility with frozen string literals
I can't even require `rbconfig` yet, but we should still track making sure this works, eventually

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1406.

Used https://github.com/Invoca/magic_frozen_string_literal to add the comments, then fixed everything by hand

### CODE REVIEW

**Comment by hsbt** [comment]
It should be use `# frozen_string_literal: false` at the first step.

**Comment by segiddins** [comment]
@hsbt I'm unsure what you mean? it should now work with frozen string literals

**Comment by indirect** [comment]
@segiddins this fails on every ruby above 1.8.7, could you investigate?

**Comment by hsbt** [comment]
Note: Ruby core team added `frozen_string_literal: false` to all ruby files in Ruby 2.3.0.

I'm ok that rubygems will handle `frozen_string_literal: true` with Ruby 2.3 includes travis build suceed.

**Comment by krainboltgreene** [comment]
I am unable to reproduce the errors on 2.3.z or 2.1.z and I have no idea why they would happen. I re-ran the build on travis, we'll see if that "fixes" the issue.

**Comment by segiddins** [comment]
I'll look back into this when I get back home

**Comment by segiddins** [comment]
This should now pass

**Comment by indirect** [comment]
womp womp

**Comment by segiddins** [comment]
Maybe now?

**Comment by segiddins** [comment]
@indirect / @copiousfreetime this is now passing, so I'd _love_ to get this in ;)

**Comment by copiousfreetime** [comment]
All passing, then works for me.

**Pull request merged**
