### PR TITLE
Improve human readable fallback version of CLI help messages

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Generating the txt version of man pages with `groff` is inconvenient for contributors since:

* It generates inconsisten output accross `groff` versions.
* It generates a lot of unnecessary whitespace changes when unrelated content changes, making diffs harder to read.

These pages are only built to be able to provide a human readable version of man pages as a fallback when `man` is not available.

But we can use the original `.ronn` sources for that.

This PR implements that, and I actually find the new output more readable, so I'm going to sell this as a documentation improvement :smile:.

#### Before:

```
BUNDLE-OPEN(1)							BUNDLE-OPEN(1)



NAME
       bundle-open - Opens the source directory for a gem in your bundle

SYNOPSIS
       bundle open [GEM]

DESCRIPTION
       Opens the source directory of the provided GEM in your editor.

       For  this to work the EDITOR or BUNDLER_EDITOR environment variable has
       to be set.

       Example:



	   bundle open 'rack'



       Will open the source directory for the 'rack' gem in your bundle.



				 August 2020			BUNDLE-OPEN(1)
```

#### After:

```
$ bundle open --help
bundle-open(1) -- Opens the source directory for a gem in your bundle
=====================================================================

## SYNOPSIS

`bundle open` [GEM]

## DESCRIPTION

Opens the source directory of the provided GEM in your editor.

For this to work the `EDITOR` or `BUNDLER_EDITOR` environment variable has to
be set.

Example:

    bundle open 'rack'

Will open the source directory for the 'rack' gem in your bundle.
```

Closes https://github.com/rubygems/rubygems/issues/3918.
Closes https://github.com/rubygems/rubygems/issues/3193 as a side effect from removing txt versions of man pages.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
CI failure should get fixed by https://github.com/ruby/ruby/pull/3497.

**Comment by deivid-rodriguez** [comment]
ruby-core fix was merged. I'll retry CI in 24h to make sure that github actions' ruby-head has picked up the fix.

**Comment by deivid-rodriguez** [comment]
PR rebased. Will merge after CI passes since I can only see upsides and it's a hard PR to keep up to date with the default branch.

**Comment by eregon** [comment]
Thank you!

**Pull request merged**
