### PR TITLE
Remove long ago deprecated methods

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Use our `deprecate` helper so that we don't forget to kill this code in the next major release (thanks to #2673). The diff is simple, view it without whitespace changes though.

Or maybe I should just go ahead and kill all this code now... :thinking:.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@deivid-rodriguez I would vote to remove it, since we in 3.0.0 already and the deprecations warnings are for `12/2018`

**Comment by deivid-rodriguez** [comment]
Yeah, let's just kill this.

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
