### PR TITLE
Backport ruby core changes

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Picked from http://github.com/ruby/ruby . It updates the fragile tests on our CI service that is https://rubyci.org

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
I don't understand 7cb5316. It only adds a top level require, so it seems unrelated to the commit message "Show documents when completion". Is that backport correct?

**Comment by deivid-rodriguez** [comment]
Thanks for keeping rubygems in sync with the changes from ruby-core, by the way! :heart:

**Comment by hsbt** [comment]
> so it seems unrelated to the commit message "Show documents when completion".

You are right. I got its detail from @aycabta. He encountered an issue related to https://bugs.ruby-lang.org/issues/14747.

**Comment by deivid-rodriguez** [comment]
Thanks for clarifying, no problem! Hopefully confused git archaeologists will end up finding this PR :smiley:

**Pull request merged**
