### PR TITLE
Backport Ruby core changes for RubyGems

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

I have some changes in ruby core repo for rubygems. this PR includes the revert changes for [XDG support](https://github.com/rubygems/rubygems/issues/3618). Other changes are ready to merge for the current master branch.

@deivid-rodriguez If you are working #3618, I separate https://github.com/rubygems/rubygems/commit/8e8596919fd047fe7a8aab2c2aeab64fcbef63cd to https://github.com/rubygems/rubygems/commit/77ee36bbb2135c191ece291cee4d5c294cb5c4b1 from this PR, and will submit new PR from them.

We should fix these changes before releasing RG 3.2.0.
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
🤔 Why the latest commit was failing with https://github.com/rubygems/rubygems/runs/760068816 after `rake update_manifest`?

**Comment by deivid-rodriguez** [comment]
@hsbt I agree we should fix this before the release. I'll work on it ASAP.

**Comment by deivid-rodriguez** [comment]
> :thinking: Why the latest commit was failing with https://github.com/rubygems/rubygems/runs/760068816 after rake update_manifest?

@hsbt I believe this is a bug. I fixed it in #3710.

**Comment by deivid-rodriguez** [comment]
I'm going to split out the reverts and merge the other changes :+1:.

**Comment by deivid-rodriguez** [comment]
I also removed the last two commits (https://github.com/ruby/ruby/commit/a6f85899144607606c114e95104fa7e8ec8d95d9 and https://github.com/ruby/ruby/commit/967ae6278f8429dc268f8d3252de048eba86fe29), since they were reverts of each other.

**Comment by deivid-rodriguez** [comment]
Going in!

**Comment by hsbt** [comment]
Thanks!

**Pull request merged**
