### PR TITLE
[Specification] Also reset specs_by_name when setting all

### PR DESCRIPTION
**Pull request by segiddins**
\c @tenderlove @indirect

### CODE REVIEW

**Comment by indirect** [comment]
Thanks! Hopefully this will mean that we can release a new version of Bundler soon that will work with the next version of RubyGems...

**Comment by tenderlove** [comment]
Next time can we squash out commits that are essentially reverted before merging?

**Comment by indirect** [comment]
Oh; yeah, sounds good. Thanks!

**Comment by drbrain** [comment]
Also, please ask for tests before merging or add them after merging.  Otherwise it is prone to break undetectably in the future.

**Comment by indirect** [comment]
@drbrain ok. I merged this PR based on it fixing tests in Bundler while keeping the RG tests green, but I'll try to add tests directly to RubyGems in the future.

**Comment by taliesins** [comment]
I think it should rather changed to
`@@stubs_by_name = specs.nil? ? {} : specs.group_by(&:name)`

**Pull request merged**
