### PR TITLE
Prepare to release RubyGems 3.2.34 and Bundler 2.2.34

### PR DESCRIPTION
**Pull request by hsbt**
I'll release them for Ruby 3.0.x

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@hsbt Also we got a request to backport https://github.com/rubygems/rubygems/pull/5044 to Ruby 3.0. See https://bugs.ruby-lang.org/issues/18755, in case you want to take the chance and include that too.

**Comment by hsbt** [comment]
@deivid-rodriguez Thanks for your remind!

**Comment by simi** [comment]
Would it be possible to wait for release this before comments at https://github.com/rubygems/rubygems/pull/6025 are resolved (since this includes that change)?

**Comment by hsbt** [comment]
@simi I revert https://github.com/rubygems/rubygems/pull/6025 from this PR. I only forcus to show `gem server` warning and dependency update like thor.

**Review by simi — APPROVED** [review]

**Comment by hsbt** [comment]
I'm confirming to backport #5154 at https://bugs.ruby-lang.org/issues/18755.

**Comment by deivid-rodriguez** [comment]
Nice work @hsbt, thank you!

**Pull request merged**
