### PR TITLE
Remove extension directory before installing

### PR DESCRIPTION
**Pull request by copiousfreetime**
# Description:

This is a fix for #1192. 

When a gem is installed, before installing, rubyge currently removes the the files from the `gems` and `specifications` but fails to remove the files from `extensions`. This fixes that.
______________

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [x] Get code review from coworkers / friends
- [x] [Squash commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Looks good, just needs a test

**Comment by copiousfreetime** [comment]
@segiddins I'd be sitting here figuring out how to write the test before sent this PR and was blocked, until your requirement showed up :-). Thought about how to explain the problems writing this test, and what do you know, cardboard programmer to the rescue!

**Comment by segiddins** [comment]
That works! I was going to suggest an extension that just consists of the time at which is was installed (we've used that in bundler for tests before)

**Comment by segiddins** [comment]
:+1:

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
