### PR TITLE
Prefer require_relative

### PR DESCRIPTION
**Pull request by marcandre**
There are over 300 calls to `require` that could be more efficient with `require_relative`. If I'm not mistaken, current `rubygems` supports only Ruby 2.2+, so this is a free speed gain.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hi @marcandre, thanks for this! This was proposed in https://github.com/rubygems/rubygems/issues/2373, but rejected by @hsbt because he wanted a benchmark to prove the speed gain.

I tried to write one so that he will accept this. You can pass an integer argument to the script that sets the LOAD_PATH size. The higher the argument, the greater the speed gain.

```ruby
require "fileutils"
require "benchmark/ips"

def load_path(n)
  $LOAD_PATH.replace([])

  (1..n.to_i).map do |dir|
    $LOAD_PATH << dir.to_s
  end

  Dir.mkdir(n)
  FileUtils.touch("#{n}/a.rb")
end

n = ARGV[0]

load_path(n)

Benchmark.ips do |x|
  x.report("require with LOAD_PATH of size #{n}:") { require "a" }
  x.report("require_relative with LOAD_PATH of size #{n}:") { require_relative "#{n}/a" }
  x.compare!
end

File.delete("#{n}/a.rb")
Dir.rmdir(n)
```

**Comment by marcandre** [comment]
One thing is for sure, `require_relative` can only be faster than `require` 😆!

It's also better styling by being more explicit: makes `require`s of other gems stand out compared to files of rubygems itself.

**Comment by deivid-rodriguez** [comment]
Absolutely, I would enable this just for style! But both of the times this was proposed performance was mentioned so I want to make sure it's accepted anyways :)

**Comment by MSP-Greg** [comment]
@deivid-rodriguez @marcandre 

Thanks for this, and the benchmark.  Working with Windows CI as much as I do, I've seen a wide variance In test times.  Probably partly due to shared i/o on a drive.  This will certainly help...

**Comment by deivid-rodriguez** [comment]
Wow, @amatsuda, thanks. I was completely unaware of these issues. Let's wait then, yeah.

**Comment by MSP-Greg** [comment]
I'm not familiar with rvm, but I'm wondering about use cases where this would be an issue.

RG Is similar to a std-lib, in that normal installs or updates are always within the lib folder.  Gems (Rails) are different.

I haven't been in the bundler code for quite a while, but I rarely see code loading parts of RG.  A Gem class method or maybe some of the command files...

There maybe issues with some CI scenarios.

**Comment by marcandre** [comment]
Oh, I see. So any path that might be `require`d (from another gem/app) should not be also `require_relative` until Ruby 2.5+.

Since it's hard to know for which files this might be the case, probably best to wait then 😿

**Pull request closed without merging**
