### PR TITLE
Prepare rubygems 3.2.33 and bundler 2.2.33

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Get another round of releases out.

### CODE REVIEW

**Review by simi — APPROVED** [review]
:pray: for the CI

**Comment by deivid-rodriguez** [comment]
I set it as draft because we may add one more PR to it.

**Comment by deivid-rodriguez** [comment]
It's good as is after a second thought. Merging!

**Review by AtAlppha — COMMENTED** [review]
.changelog.yml

**Review by AtAlppha — COMMENTED** [review]
- [ ]

**Pull request merged**
