### PR TITLE
Fix check for missing spec in check_for_unmet_dependencies

### PR DESCRIPTION
**Pull request by Eusebius1920**
## What was the end-user or developer problem that led to this PR?

See #5422

## What is your fix for the problem, implemented in this PR?

Add a check that catches the condition and handles it properly, see https://github.com/rubygems/rubygems/issues/5422#issuecomment-1106434053

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by Eusebius1920** [comment]
- [x]  code linting should be fine (rubocop does not complain)
- [x] fixed / enhanced existing tests to comply with changes

- [ ] Running the test-suite locally atm, but I already can see some Failures

**Comment by sadfuzzy** [comment]
could this be merged?

**Comment by deivid-rodriguez** [comment]
Hi!

We never followed up on this because the original issue was no longer reproducible, although improving the error message in case the problem comes up again won't hurt.

What problem are you having?

**Comment by deivid-rodriguez** [comment]
Actually I'm pretty sure that with recent changes in our we materialize specs, this can no longer be triggered. So I'm going to close this with a big thanks to @Eusebius1920 for starting this work and helping figuring out root causes.

@sadfuzzy Please open a ticket with whatever issue you're having and we can figure it out from there!

Thanks both!!

**Pull request closed without merging**
