### PR TITLE
Don't change ruby process CWD when building extensions

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

This leads to simpler code because we don't need to maintain a mutex to ensure thread safety.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by eregon** [comment]
This looks great!
It should enable to build C extensions in parallel which could lead to very nice speedups for large Gemfiles.

**Comment by deivid-rodriguez** [comment]
I had forgotten about this. I rebased it!

**Review by eregon — APPROVED** [review]
Looks good to me!

**Comment by deivid-rodriguez** [comment]
Let's do it!

**Pull request merged**
