### PR TITLE
Use faster macos-13 in CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Slow CI.

## What is your fix for the problem, implemented in this PR?

Checking if this speeds up macOS.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
macos-13 is definitely faster than macos-12. Trying macos-arm-oss now.

**Comment by martinemde** [comment]
Seems like this version of mac os stays queued much longer.

**Comment by deivid-rodriguez** [comment]
Yep, we should stick with macos-13!

**Comment by MSP-Greg** [comment]
> Seems like this version of mac os stays queued much longer.

Friday afternoon US is often slow across all platforms.  Also, I think macOS also has lower concurrency limits for most GitHub 'membership' plans.  Or, in Puma, often waiting on macOS CI.  We've got 16 macOS jobs.

**Comment by deivid-rodriguez** [comment]
macOS has trouble installing graphviz for deprecated `bundle viz` specs. I went ahead and started skipping those on macOS. I think ubuntu is enough to avoid regressions there, it's code that hardly ever regresses or gets any updates.

**Review by martinemde — APPROVED** [review]

**Pull request merged**
