### PR TITLE
move CONTRIBUTING.rdoc and POLICIES.rdoc documents to markdown

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

I would like to propose that we move CONTRIBUTING.rdoc and POLICIES.rdoc to Markdown. It has become a heavily used syntax for rich text formatting that is supported by the biggest code editors like Atom/VS Code & Jetbrains (And Github natively supports it).

I think this is a good change because this would lower the barrier of entry for people that want to make a change to these documents in the future.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by colby-swandale** [comment]
I've updated this to also move UPGRADING.rdoc to markdown as well

**Comment by hsbt** [comment]
I agreed to migrate markdown. 

Can you change with https://github.com/rubygems/rubygems/blob/master/rubygems-update.gemspec#L21 ?

**Comment by deivid-rodriguez** [comment]
Loving this myself too! :+1:

**Comment by colby-swandale** [comment]
@hsbt ah yes, thank you for reminding me!

**Comment by hsbt** [comment]
@colby-swandale Can you rebase this pull request?

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
