### PR TITLE
Fix invalid config file handling with Psych

### PR DESCRIPTION
**Pull request by agis-**
This is a series of changes that:

1) fix the relevant test to actually test that we properly handle config files with invalid YAML, and therefore fail (since we don't)
2) fix RubyGems to actually handle such files

### CODE REVIEW

**Comment by agis-** [comment]
@indirect Btw, this came up after https://github.com/bundler/bundler/pull/4076.

**Comment by segiddins** [comment]
@homu r+

**Comment by indirect** [comment]
@segiddins this is rubygems :)

**Comment by segiddins** [comment]
@indirect whoops:)

**Pull request merged**
