### PR TITLE
Assume ruby.exe to be available as defined by the environment

### PR DESCRIPTION
**Pull request by slackfan**
The behavior introduced with pull request #942 when creating the windows
batch file of a ruby gem has the downside that it is no longer easy
possible to use a different (J)Ruby installation but the same %GEM_HOME%
directory.  This is for example needed when distributing all gems
available in a %GEM_HOME% directory accross various installations which
may have different Ruby installations.

The proposed changes tries to fix the mentioned flaws by utilizing set
environment variables. It keeps the existing behavior if no environment
variable is set but uses the environment variables if set.

### CODE REVIEW

**Comment by segiddins** [comment]
I'm having trouble understanding exactly what this PR is fixing, particularly since there are no tests.

**Comment by slackfan** [comment]
Hi, 

I try to provide an example: 
```
%GEM_HOME% -> C:\gem_home
%RUBY_HOME% -> C:\Ruby193
```

When packaging and installing a gem _foobar_ the file `%GEM_HOME%\bin\foobar.bat` looks like this: 

```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\Ruby193\bin\jruby.exe" "C:\gem_home\bin\foobar" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\Ruby193\bin\jruby.exe" "%~dpn0" %* 
```

__The problem with that is__: 
As soon as you move/change the runtime behind `%RUBY_HOME%` the bat file no more works because the path to the Ruby runtime is hard wired. For example if you reconfigure `%RUBY_HOME%` to _C:\Ruby223_ the executable of the runtime in _C:\Ruby193_ is still used. 

My use case of this is that I ship a complete GEM_HOME and RUBY_HOME directory within a MSI file so I have only very poor control where this finally ends up. 

The code change I propose is to utilize the environment variable `%RUBY_HOME%` when installing the gem into `%GEM_HOME%`. 
This is written the way the old behavior is kept if there is no `%RUBY_HOME%` variable so we do not introduce any new dependency here. The file `%GEM_HOME%\bin\foobar.bat` looks finally like this: 

```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"%RUBY_HOME%\bin\jruby.exe" "C:\gem_home\bin\foobar" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"%RUBY_HOME%\bin\jruby.exe" "%~dpn0" %* 
```

__Further note__: 

This code change also does not negate PR #942 which improved the very first layout of the bat file. This was
 ```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"ruby.exe" "C:\gem_home\bin\foobar" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"ruby.exe" "%~dpn0" %* 
```
and had the pitfall that `%Path%` was used. If you had a different Ruby runtime in Path prior the one `%RUBY_HOME%` points to, you also had a variation of the problem I try to solve now (finally). 


Does this make sense? I am not sure how to write a test for this as this defines the way the ruby code itself is called. Maybe that's why there is none so far.

**Comment by slackfan** [comment]
What can I do to increase the chances that this is merged?

**Comment by djberg96** [comment]
Makes sense to me, but we should try to come up with a way to test it.

**Comment by slackfan** [comment]
I am not sure why the latest Travis CI failed. Looks like something unrelated. Can somebody please have a look? I do not know how to trigger another test :/

**Comment by krainboltgreene** [comment]
I'm pretty good with this @indirect, but I don't have a windows machine to test this on, so what do you want to do?

**Comment by indirect** [comment]
@krainboltgreene I remember that once upon a time putting `#!/usr/bin/env ruby` in gem binstubs fucked things up pretty badly on unix, so I am wary of doing the same thing on windows. IIRC there is an option already that lets you set any shebang you want, and we tell anyone who wants `env ruby` on unix to use that option.

**Comment by slackfan** [comment]
Hi, the proposed change imho does not work like _env_ on unix like OSes. It just utilizes a user configuration only *if* set correctly. I am not aware of a working(?) option to configure the path to the ruby interpreter on Windows. Can you please give me a hint where to look for this? The method which creates the *.bat file on Windows at least does not allow to pass anything which allows modification of the interpreter.

**Comment by indirect** [comment]
I was not saying the option existed on Windows, just explaining the option that exists on Unix. I don't like that this change depends on a magic env var, and would prefer a version of this change that relies on an option passed to `gem install` (maybe installs on Windows can honor the `--shebang` option?), and allows the option to be set in .gemrc.

**Comment by slackfan** [comment]
Ah, thank you, that was a misunderstanding then. Using `gem install` would not fix my issue as we still would end up with something hard coded where I need a bit of flexibility (the environment variable). But sure, you are right, having the shebang option considered on Windows would be valuable as well.

**Comment by indirect** [comment]
Using the shebang option, you would be able to create binstubs that respect your environment variable, right?

**Comment by slackfan** [comment]
Only if it would allow to pass environment variables as "placeholders". How to proceed now? Is the proposed change declined or still ok?

**Comment by indirect** [comment]
The shebang option should accept any string (at least, it does on Unix). If Windows gains shebang support, I believe that would solve this problem in a flexible but more easily maintainable way.

**Comment by copiousfreetime** [comment]
@indirect @djberg96 any further feedback on this are we going forward with this or decling?

**Comment by djberg96** [comment]
I can understand the reluctance to rely on an environment variable, though I believe the shebang will work on cygwin.

I think the closest analogue to using the shebang on Windows is to set the file association, though ideally that would mean being able to set it either globally or per gem.

Either way, I'm tempted to say that this should be a plugin, if possible.

**Comment by MSP-Greg** [comment]
@slackfan

I noticed this in the open PR list, and it's subject (Windows bin stubs) is addressed in PR #2119.  If you feel that PR overlaps with this one, feel free to comment here or there.

Thanks, Greg

**Comment by slackfan** [comment]
Thanks Greg! I'll close this one as it got talked down and will vote for your approach. Btw, my workaround for now is simply to not use the Ruby binary stubs in Windows as they continued to be unusable for the most common windows deployment use case within the last 2.5 years.

**Pull request closed without merging**
