### PR TITLE
Fix TestCase#have_git? on Windows - test_case.rb

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

RG testing determines if 'git' exists by file existence.  Fix for Windows.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Can you quote the git instance variable inside the commit message? Otherwise we're mentioning the git organization.

**Comment by deivid-rodriguez** [comment]
Thanks!

@bundlerbot merge

**Comment by MSP-Greg** [comment]
bors stuck/frozen ?

**Comment by deivid-rodriguez** [comment]
@bundlerbot retry

**Comment by MSP-Greg** [comment]
Should I close this and re-submit (create a new PR)?

**Comment by bronzdoc** [comment]
@bundlerbot merge

**Comment by deivid-rodriguez** [comment]
@bundlerbot merge

**Comment by deivid-rodriguez** [comment]
@bundlerbot retry

**Comment by deivid-rodriguez** [comment]
Closing in favor of #3098, to try to get rid of `@bundlerbot` issues.

**Pull request closed without merging**
