### PR TITLE
Bundlerbot with gh actions

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

I'll investigate fixing our bors-ng config in this PR, using feedback @notriddle left in https://github.com/rubygems/rubygems/issues/2920.

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
It sounds like it's working :)

**Comment by deivid-rodriguez** [comment]
@bundlerbot try

**Comment by deivid-rodriguez** [comment]
@bundlerbot try

**Comment by deivid-rodriguez** [comment]
@bundlerbot try

**Comment by deivid-rodriguez** [comment]
This seems to be working, so setting it as ready!

**Comment by hsbt** [comment]
Great! Thanks a lot.

@bundlerbot r+

**Pull request merged**
