### PR TITLE
Add validate_cert_chain to specification policy

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
closes https://github.com/rubygems/rubygems/issues/2498

Warn if no cert chain is provided and link the user to the guides on how to set up a cert chain and signing key in their gemspec
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
Windows failure is not related to this PR, see https://github.com/rubygems/rubygems/pull/2486

**Comment by bronzdoc** [comment]
Ah bundler is complaining about the new warnings....

**Comment by djberg96** [comment]
Looks good to me!

Is there a way to disable/skip this warning for bundler?

**Comment by bronzdoc** [comment]
I'll write a patch to bundler to fix the test failures

**Comment by djberg96** [comment]
@bronzdoc Got a link to the bundler patch?

**Comment by bronzdoc** [comment]
@djberg96 yes https://github.com/bundler/bundler/pull/6831
Still need to work out some things...

**Comment by bronzdoc** [comment]
Once https://github.com/bundler/bundler/pull/6998 is merged i think we can move forward with this one

**Comment by djberg96** [comment]
:(

**Pull request closed without merging**
