### PR TITLE
Improve user-facing messages by consistent casing of Ruby/RubyGems

### PR DESCRIPTION
**Pull request by jslabovitz**
# Description:

It was bothering me to see the message "Clean Up Complete" capitalized like that, which was inconsistent from most other RubyGems messages. So I fixed that issue, and also found a few handfuls of other instances where either case or spacing was inconsistent. Note this is all in user-facing messages -- I tried hard to avoid touching anything that generated code, or tests.

### CODE REVIEW

**Comment by bronzdoc** [comment]
Hi @jslabovitz thanks for contributing to Rubygems.

We have specs that test for exactly matching output, so tests should be modified also.

**Comment by jslabovitz** [comment]
Ah, ok. I'll work on the tests.

**Comment by jslabovitz** [comment]
The tests related to my changes should succeed now. You might want to know that even without my initial code changes, 'rake test' fails on my system (10 failing tests). Looks like there's a bunch of assumptions about paths that are maybe too specific.

**Comment by bronzdoc** [comment]
:+1:

**Comment by segiddins** [comment]
Thanks!
@homu r+

**Pull request merged**
