### PR TITLE
Add ISSUES.md

### PR DESCRIPTION
**Pull request by duckinator**
# Description:

This adds an ISSUES.md file, which explains the various labels used by this repo.

I know it doesn't explain _all_ of them, but I figured doing that would be even more overwhelming for folks than not having the file at all. I think I got all of the ones that are consistently used.

# Tasks:

- [x] Describe the problem / feature
- [x] Write <s>code</s> <ins>documentation</ins> to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by duckinator** [comment]
Maybe this should be called LABELS.md and have a separate ISSUES.md that discusses how to manage and triage issues for RubyGems?

Will wait for feedback before doing that.

**Comment by lynnco** [comment]
You'll want to remove the duplicate info from https://github.com/rubygems/rubygems/blob/master/CONTRIBUTING.rdoc !

**Comment by segiddins** [comment]
Manifest needs to be updated

**Comment by duckinator** [comment]
Closing because this is basically duplicate information from CONTRIBUTING.rdoc, which I didn't realize covered labels.

**Pull request closed without merging**
