### PR TITLE
Update the list of SPDX licence identifiers

### PR DESCRIPTION
**Pull request by segiddins**
Update the list of SPDX identifiers by running `ruby util/generate_spdx_license_list.rb`, also updating that script so it generates rubocop-approved code.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by hsbt — APPROVED** [review]
Nice catch 👍

**Comment by simi** [comment]
:+1: Would be any automation in here welcomed? We can start with something simple like monthly reminder to regenerate list on Slack in maintainers channel.

**Comment by segiddins** [comment]
We could probably have an action re-run the script and open a PR if there's any diff?

**Comment by deivid-rodriguez** [comment]
It would make sense to me to run something like that on a periodic (monthly?) basis, yeah!

**Pull request merged**
