### PR TITLE
Fix typo in specs warning.

### PR DESCRIPTION
**Pull request by ruimiguelsantos**
# Description:

Fixes typos in unresolved specification warning (s/ambigious/ambiguous).

______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by djberg96** [comment]
These are some ambituous changes, I approve. ;)

**Comment by bronzdoc** [comment]
@bundlerbot retry

**Comment by hsbt** [comment]
@bundlerbot retry

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
