### PR TITLE
Figure out why we need to override `Gem::NameTuple.new`

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Just trying to figure out why this is needed because it's very non standard.

## Make sure the following tasks are checked

- [ ] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [ ] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by martinemde** [comment]
For old rubygems that don't to_s their platform arg (which we can't easily test here).

**Comment by martinemde** [comment]
Ok, I have a few more minutes to look at this.

Original PR is #7081.

Useful to know: [Gem::Platform also overrides `self.new` without problems](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/platform.rb#L64-L73).

If we didn't override new, we'd need to override initialize (which I had a lot of problems with when I first time, but we could try again) or override a few of the other instance methods.

We could also be better about removing the patch when it's not necessary. I'll test that approach by pushing to this branch.

**Comment by deivid-rodriguez** [comment]
> We could also be better about removing the patch when it's not necessary. I'll test that approach by pushing to this branch.

Yes, that's the approach we normally follow, feature detect if RubyGems is missing the feature/fix that needs patching (or hardcode the RubyGems version that first introduces it) and only apply it when necessary. I feel that also makes it easier to remember cleaning up when dropping support for old versions.

Also I think removing these patches should make some test fail? We test Bundler with old rubygems so some matrix entry should catch the issue?

**Comment by deivid-rodriguez** [comment]
Even if there's no end to end test that catches it, this is needed, so closing!

**Pull request closed without merging**
