### PR TITLE
Add Ruby 3.2 and 3.3 platforms to Gemfile DSL

### PR DESCRIPTION
**Pull request by composerinteralia**
## What was the end-user or developer problem that led to this PR?

Ruby 3.2 platforms are not yet supported in the Gemfile DSL:
 
```
gem "abc", platform: :ruby_32
```

## What is your fix for the problem, implemented in this PR?

Along the same lines as https://github.com/rubygems/rubygems/pull/5469, this adds support for Ruby 3.2 platforms.

## Make sure the following tasks are checked

- [X] Describe the problem / feature
- [X] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [X] Write code to solve the problem
- [X] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by composerinteralia** [comment]
Seeing https://github.com/rubygems/rubygems/pull/5469#issuecomment-1098428186, I played around with a test to catch this earlier in the future, and ended up with something like this:


```rb
    it "allows platforms matching the running Ruby version" do
      platform = "ruby_#{RbConfig::CONFIG["MAJOR"]}#{RbConfig::CONFIG["MINOR"]}"
      subject.gem("foo", :platform => platform)
    end
```

Do you think that is worth adding? Or is there a better way of getting at that?

**Comment by deivid-rodriguez** [comment]
Nice, I like it! It should make our daily CI against ruby-head fail, and then fixed after adding `:ruby_33`.

**Review by deivid-rodriguez — APPROVED** [review]
Approving the current changeset since it seems good to introduce right away, but feel free to also add the extra spec on this PR if you prefer!

**Comment by composerinteralia** [comment]
Confirmed the test fails on 3.3: https://github.com/rubygems/rubygems/actions/runs/4106956899/jobs/7085847793

I'll add those platforms and then this should be ready to go.

**Review by deivid-rodriguez — APPROVED** [review]
Thanks a bunch!

**Comment by composerinteralia** [comment]
https://github.com/rubygems/rubygems/actions/runs/4107455290/jobs/7086969404 looks like it succeeded, but is stuck 😕

**Comment by deivid-rodriguez** [comment]
Indeed, it seems like an actions glitch?

**Comment by composerinteralia** [comment]
This time https://github.com/rubygems/rubygems/actions/runs/4112632902/jobs/7097788892 got cancelled for some reason 😢 

I'll rebase to trigger this one more time 🤞🏻

**Comment by deivid-rodriguez** [comment]
Oh boy, sorry about that. Our CI has become a little bit unstable since adding Ruby 3.2 :(

**Comment by simi** [comment]
Finally 🟢 💪.

**Pull request merged**
