### PR TITLE
Allow specifying gem requirements via env variables

### PR DESCRIPTION
**Pull request by segiddins**
This is horribly hacky, but it takes care of https://github.com/rubygems/rubygems/pull/887#issuecomment-179363165

### CODE REVIEW

**Comment by segiddins** [comment]
^ @indirect you might be interested in this

**Comment by indirect** [comment]
I hope no one ever needs to set gem requirements for two gems with names that are the same when upcased. This looks like what we want, though!

**Comment by segiddins** [comment]
umm this had no tests and got no review... I'm not sure it should've been merged

**Comment by indirect** [comment]
Oops 😬 I reviewed the code, and remembered that it looked good, but forgot it didn't have tests. I am okay with this feature and this implementation of it, provided we add some tests. If there are objections, I'm okay with reverting.

**Comment by segiddins** [comment]
(I have time to test this penciled in for tomorrow morning)

**Comment by tenderlove** [comment]
Did this ever get a test?

**Comment by segiddins** [comment]
Yes @tenderlove there's an open PR for them

**Pull request merged**
