### PR TITLE
Rerecord VCR cassettes

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I like to do this once in a while to make sure the specs test a more up to date realworld.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by simi** [comment]
In theory we should do this after each change on API in rubygems.org and index.rubygems.org. Are there any other endpoints used?

**Comment by deivid-rodriguez** [comment]
Just the dependency endpoints are used. Still, even if no API changes, I think it's good to do it once in a while. As the space of released gems grows, the resolution problem usually becomes harder, so it doesn't hurt to check how problematic Gemfiles behave in the current realworld.

**Comment by simi** [comment]
@deivid-rodriguez sure, thanks for the info.

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Something quite interesting happened after merging #4081.

Now the response files generated by VCR are plain text, I think because now `net/http` takes care of decompressing the content, correct @eregon? Seems nice to me.

I'll make a followup PR to catch up with this change.

**Comment by eregon** [comment]
That makes sense as I think VCR monkey-patches Net::HTTP outer methods and so the whole decompression is all internal to Net::HTTP.

**Comment by deivid-rodriguez** [comment]
Yeah, I was thinking the same. We don't use the real VCR but a custom implementation of the same thing, but we monkeypatch `net/http` in a similar way I believe.

**Pull request merged**
