### PR TITLE
Use `caller_locations` instead of splitting `caller`

### PR DESCRIPTION
**Pull request by nobu**
## What was the end-user or developer problem that led to this PR?

Splitting `caller` is fragile, especially when paths contain a colon or space.

## What is your fix for the problem, implemented in this PR?

Use `caller_locations` method.
Also limit caller ranges not to make unnecessary backtraces.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Still interested @nobu? Can you rebase this?

**Comment by deivid-rodriguez** [comment]
I'll close since there was no further feedback. Feel free to rebase & reopen if still interested!

**Comment by nobu** [comment]
Sorry, I forgot for a long time, but rebased now.

**Comment by hsbt** [comment]
@nobu I couldn't reopen this because your branch used force-push. GitHub didn't support to update like that.

Can you submit another pull-request?

**Pull request closed without merging**
