### PR TITLE
Do not prompt for passphrase when key can be loaded without it

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
closes https://github.com/rubygems/rubygems/issues/2660

in https://github.com/rubygems/rubygems/pull/2380/files#diff-b1c96c3380adfe196cce915be6689f16R56 i introduced a custom prompt for a key passphrase to avoid  asking the passphrase twice when auto re-signing a cert in https://github.com/rubygems/rubygems/pull/2380/files#diff-b1c96c3380adfe196cce915be6689f16R147 
but that leads to the prompt being triggered even if a key has no passphrase as  https://github.com/rubygems/rubygems/issues/2660 described.

This PR reverts that... now if a key doesn't need a passphrase it will not be triggered as it used before, but at the cost of asking for the passphrase twice if a key needs to be re-signed.

I added another alert message in between prompts to try to make things clear and not confuse the user when asked for passphrase twice if the key needs to be resigned when building a gem re-signed

______________
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hei @bronzdoc, not exactly an expert on this part of rubygems, but I'll try to have a look at the PR in the next days. Thanks for fixing this! :+1:

**Comment by bronzdoc** [comment]
Ping @djberg96 😬

**Comment by djberg96** [comment]
👍

**Comment by deivid-rodriguez** [comment]
@p-mongo could you have a look at this PR? Does it look good to you? Does it work for you?

**Comment by p-mongo** [comment]
Happy to test this change, could you point me to documentation for how to test this PR in a way that does not destroy my existing Ruby installations please?

**Comment by bronzdoc** [comment]
@p-mongo you need to clone this repo, then switch to the `fix_signer_passphrase_prompt` branch.

Then i personally use this alias `dgem="ruby -I path/to/rubygems/lib path/to/rubygems/bin/gem"`

`$ dgem build ...`

**Comment by bronzdoc** [comment]
ping @p-mongo

**Comment by p-mongo** [comment]
@bronzdoc This PR works for me, thank you!

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
