### PR TITLE
[WIP] Bundler Merger

### PR DESCRIPTION
**Pull request by segiddins**
⚠️ DO NOT MERGE ⚠️

### CODE REVIEW

**Comment by drbrain** [comment]
What's the goal of this?

**Comment by indirect** [comment]
The short-term goal is to get the Bundler test suite running as part of RubyGems CI, so we can shorten the feedback loop when things change or break.

The long-term goal is the (eventual) eternally-discussed merger of the RubyGems and Bundler codebases, so we can stop reimplementing the same things over and over.

**Comment by drbrain** [comment]
Testing seems fine.

Dumping the source in with no plan in the hopes that a merge happens seems less than ideal.

**Comment by indirect** [comment]
@drbrain what? Where are you getting the idea that this is "dumping the source in with no plan in hopes that a merge happens"? We have a plan, and this is the first commit of a WIP pull request for a project that I expect to take weeks (or even months).

**Comment by drbrain** [comment]
Can you link me to the plan?  I haven't seen it go by in slack

**Comment by drbrain** [comment]
Discussed on slack, plan is our forever plan.

Sorry for causing frustration and consternation. 🙇🏻🙇🏻🙇🏻

**Comment by djberg96** [comment]
For those of us not on Slack...what's the plan?

**Comment by indirect** [comment]
I might be missing something, and I'm sure we'll need to adjust this as we go along, but here's the condensed and high level version:

1. Write glue code to run all of the RubyGems and Bundler tests against each commit to RubyGems and Bundler. (This is in progress, and is why the Bundler repo is current a submodule of RubyGems).
1. Get Bundler's 2.0 branch merged into the `master` branch.
1. Investigate areas of duplicated implementaitons, including at least sources, specification subclasses, gemfile evaluator, lockfile parser, lockfile emitter, and probably more.
1. Drop support for Ruby < 2.2 (maybe 2.3, depending on how long this takes?)
1. Combine development setup code into one thing.
1. Create tooling to release Bundler+RubyGems as a single shippable artifact.
1. Release a combined Bundler+RubyGems as version 3.0 of both.

Things We Will Do Eventually That Are Not Blockers For A Merged 3.0:

1. Refactor all duplicated implementations into single implementations.
1. Refactor CLI commands so we only have one backend.
1. Merge configuration systems (where that makes sense) so that you only need to set e.g. HTTP proxy for installing gems in one place.
1. Figure out what the fuck "platform" means (CPU architecture? OS distro? Vendor? Ruby engine? All of the above?) and add backwards-compatible support for it to gemspecs, gemfiles, and lockfiles.
1. Stop activating rubygems and bundler plugins just because they are installed, and switch to an opt-in configuration based system.
1. Remove support for multiple sources for `gem install`.
1. Other things I'm sure I'm not remembering right now.

**Comment by segiddins** [comment]
I kinda want to merge in this refactored testing work, so that we can at least make sure we don't break bundler for now. Thoughts?

**Comment by indirect** [comment]
Yeah, I would like to merge just the testing work. Can you open a new PR with just the tests, and we can merge that to start?

**Comment by segiddins** [comment]
@indirect all of this is just tests right now...

**Comment by indirect** [comment]
I know that this PR is just the tests so far, but I'd like to keep this PR open for merger things while merging a different PR named something like "Run Bundler tests in CI" 👍

**Comment by segiddins** [comment]
Done, testing moved to https://github.com/rubygems/rubygems/pull/1650

**Comment by segiddins** [comment]
Does any more work has to be done with regards to installing bundler as a default gem?

**Comment by segiddins** [comment]
So now RubyGems will use Bundler for Gem.use_gemdeps, dependent upon https://github.com/bundler/bundler/pull/4770

**Comment by shevegen** [comment]
Will there be backwards incompatible changes of the merge?

Reason I ask is in particular if this will force people to adapt their use cases and how they use software in the whole ruby ecosystem. To make this more specific - I presently use rubygems but not bundler and there may be others in similar situations, hence why I would like to know as early as possible how it might affect me. Not stating that I am against a merger, btw, I merely want to know beforehand if and how it may impact change in use of rubygems and the ecosystem.

**Pull request closed without merging**
