### PR TITLE
Keep consistency for the second option for add_option

### PR DESCRIPTION
**Pull request by tnir**
# Description:

Keep consistency for the second option for add_option.

`git grep 'add_option.*, "'` (the targets the PR fixes) vs. `git grep "add_option.*, '"` (the dominant notation)

______________

# Tasks:

- [x] Describe the problem / feature
- [n/a] Write tests
- [x] Write code to solve the problem
- [n/a] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I'm not very favorable to this kind of consistency updates because they don't ensure the consistency stays in the future. I would actually prefer to stick to a string literals style globally through rubocop and fix all offenses at once. Even if it generates a lot of churn, it fixes the issue once and for all.

**Comment by hsbt** [comment]
Thanks, But we will not merge inconsistency style changes. 

Note: I prefer to use double quotes with rubocop.

```
Style/StringLiterals:
  EnforcedStyle: double_quotes
```

**Comment by tnir** [comment]
@deivid-rodriguez Thanks.

@hsbt Got it. This project isn't using `Style/StringLiterals` cop yet? 😭

**Comment by tnir** [comment]
Okay, 1290 days after the discussion I just prepared #5731.

**Pull request closed without merging**
