### PR TITLE
Remove dependency installer deprecated methods

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:

Remove dependency installer deprecated methods
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bronzdoc Can you also remove `Gem::Deprecate` and its `require`?

**Comment by bronzdoc** [comment]
Done @hsbt

**Comment by hsbt** [comment]
Thanks!

@bundlerbot merge

**Comment by jeepdude1980** [comment]
Remove or your going down brow got everyone's user I'd copyed

**Pull request merged**
