### PR TITLE
Merge rubygems and bundler rubocop rules 

### PR DESCRIPTION
**Pull request by hsbt**
## What was the end-user or developer problem that led to this PR?

We have two rubocop rules between rubygems and bundler. We should move to merge them.

## What is your fix for the problem, implemented in this PR?

I merge `.rubocop_bundler.yml` into `.rubocop.yml` only non-effect cops at first in this PR. After that, I'll triage `rubocop_bundler.yml` cops and modify rubygems or bundler files step by step.

@deivid-rodriguez @simi Do you have any concerns about this merger plan?

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by hsbt** [comment]
`Layout/CaseIndentation` and `Layout/SpaceAroundOperators` are conflicts on rubygems/bundler. I aligned their cops in this time.

**Comment by deivid-rodriguez** [comment]
No concerns, and I like your plan.

**Comment by hsbt** [comment]
Thanks to quick response. I'll work Layout, Style, Naming and other cops.

**Comment by simi** [comment]
:muscle: getting rubygems and bundler closer one step at the time :muscle: 

Btw. I have still plan to add `Naming/MemoizedInstanceVariableName`, I'll postpone my PR until this is finished.

**Comment by hsbt** [comment]
I confirmed rule differences with the following way:

```ruby
>> master = (Psych.load_file(".rubocop.yml").keys + Psych.load_file(".rubocop_bundler.yml").keys).uniq
# swith to this branch
>> merge = Psych.load_file(".rubocop.yml").keys + Psych.load_file(".rubocop_bundler.yml").keys).uniq
>> merge - master
=> ["inherit_from"]
>> master - merge
=> []
```

There is no missing cops with this PR.

**Pull request merged**
