### PR TITLE
Enable `Style/AndOr` cop in RubyGems

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

In #4488 I need to backport the whole `Gem::Platform#===` method to Bundler, so that platform fixes work across more RubyGems versions. However, code style in RubyGems and Bundler differ a lot because RubyGems uses "English" logical operators. This makes it a bit harder to keep the duplicated code in sync.

In addition to that, I always found it very weird how RubyGems uses these operators rather than the symbolic ones for plain logical operations.

## What is your fix for the problem, implemented in this PR?

Enable `Style/AndOr` in RubyGems.

In theory the auto-correction of this cop is unsafe due to the different precedence, but this cop seems to have been battle tested a lot and the corrections are really smart. I will give it a manual review if this is accepted though (and if CI passes, of course).

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by simi** [comment]
Is there a plan to add it to https://github.com/rubygems/rubygems/blob/master/.git-blame-ignore-revs after merging?

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
> Is there a plan to add it to https://github.com/rubygems/rubygems/blob/master/.git-blame-ignore-revs after merging?

🤷‍♂️, I think we should set up a rule for this, otherwise we'll be discussing this too many times. I think a criteria for adding it would be:
* Style change
* Net change of the commit (additions + deletions) to be at least 1000.

**Comment by simi** [comment]
IMHO any "cosmetic" bulk change should be added to `.git-blame-ignore-revs`.

**Comment by deivid-rodriguez** [comment]
We just need to define "bulk" 😄

**Comment by deivid-rodriguez** [comment]
In my opinion, cosmetic changes in git history are fine, the problem is when they appear every single time you use `git blame` (and I'm not even bothered personally by that that much either, I just proposed `.git-blame-ignore-revs` to make a patch like the one to change quote styles more likely to be accepted).

**Comment by deivid-rodriguez** [comment]
Also, I think RuboCop cops with unsafe auto-corrections should never qualify as cosmetic. Imagine what it would be like to figure it out if this patch introduced a bug, and the commit was added to `.git-blame-ignore-revs` 😅.

**Review by indirect — APPROVED** [review]

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
Indeed this is not cosmetic change.

**Comment by deivid-rodriguez** [comment]
I reviewed the patch manually and made two modifications:

* The autocorrected code started mixing `not` with symbolic operators which felt weird and needed extra parenthesis to work. So I enabled the [`Style/Not` cop](https://docs.rubocop.org/rubocop/cops_style.html#stylenot) too.
* The autocorrected code was introducing many unnecessary parentheses, given that `==`, `===`, `>=`, and so on still have higher precedence than `&&` and `||`. So I removed them unnecessary parentheses, keeping the code closer to what it was.

This should be ready now from my side!

**Comment by hsbt** [comment]
👍

**Pull request merged**
