### PR TITLE
Fix rake path under vendor directory in order to allow space symbols …

### PR DESCRIPTION
**Pull request by valk**
Fix issue https://github.com/rubygems/rubygems/issues/1969

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by valk** [comment]
Hi @segiddins, I found a bug, closing, will reopen another pull-request with a fix and a test, thanks!

**Comment by valk** [comment]
@segiddins Do you know someone who can help me with tests? I mean the "fixed" fix is working and it's:
`
               rake_path = Gem.bin_path('rake', 'rake').to_s
               rake_path = '"' + rake_path + '"' if rake_path.include?(' ')
               "#{Gem.ruby} -rubygems #{rake_path}"
`
And it took me half a day to figure out how to compile and run etc (I'll just mention that I went thru all the non-intuitive and / or undocumented things like the need to `gem uninstall rake` and `rake package` even tried to add a Gemfile because of RVM etc.). So I don't wanna marry this project but would kindly help, but again I need some veteran here so we can take this forward.

**Comment by segiddins** [comment]
`gem install rake:10.5 && rake _10.5_` or `ruby -Ilib test/file/to_test.rb`

**Comment by valk** [comment]
Sorry, I meant I'm struggling how to write a test properly. Will something like this be enough?

```ruby
  # PROBABLY SHOULD DUPLICATE AN EXISTING TEST?
  # 
 def test_self_ruby_escaping_spaces_in_project_and_and_rake_paths
    orig_ruby = Gem.ruby
    orig_bindir = RbConfig::CONFIG['bindir']
    orig_ruby_install_name = RbConfig::CONFIG['ruby_install_name']
    orig_exe_ext = RbConfig::CONFIG['EXEEXT']

    RbConfig::CONFIG['bindir'] = "C:/Ruby 1.8/bin"
    RbConfig::CONFIG['ruby_install_name'] = "ruby"
    RbConfig::CONFIG['EXEEXT'] = ".exe"
    Gem.instance_variable_set("@ruby", nil)

    # SHOULD STUB SOMEHOW LIKE THIS OR ALSO TRY AND ADD RbConfig::CONFIG
    # 
    Gem.stub(:bin_path, 'C:/My Project/vendor/bundle/rake') do
      assert_equal "\"C:/Ruby 1.8/bin/ruby.exe\"", Gem.ruby
    end
  ensure
    Gem.instance_variable_set("@ruby", orig_ruby)
    RbConfig::CONFIG['bindir'] = orig_bindir
    RbConfig::CONFIG['ruby_install_name'] = orig_ruby_install_name
    RbConfig::CONFIG['EXEEXT'] = orig_exe_ext
  end

```

**Comment by segiddins** [comment]
This doesn't actually test your change -- I'd stub `Gem.bin_path`, expect `Gem::Ext::RakeBuilder.run` to be run with the escaped arguments, and then call `Gem::Ext::RakeBuilder.build`

**Comment by colby-swandale** [comment]
ping @valk. Is this still being worked on?

**Pull request closed without merging**
