### PR TITLE
[Util] Add scripts to help releasing

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Make my life easier

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by indirect** [comment]
👍

**Comment by segiddins** [comment]
@bundlerbot r+

**Comment by indirect** [comment]
@segiddins something broken in @bundlerbot right now 😒

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
