### PR TITLE
Add sort-by-latest-version to list [rebased]

### PR DESCRIPTION
**Pull request by krainboltgreene**
This is a rebase of #617

### CODE REVIEW

**Comment by segiddins** [comment]
This needs a spec

**Comment by drbrain** [comment]
Here's an example [test of behavior](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_commands_query_command.rb#L230-L251), here's an example [test of option parsing](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_version_option.rb#L15-L19) which would go in the [list command tests](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_commands_list_command.rb#L33).

**Comment by drbrain** [comment]
Also, is there any reason this is only on `gem list`? I think it should go in QueryCommand so `gem search` also gets it.

**Comment by segiddins** [comment]
@krainboltgreene this is still awaiting a spec & rebase

**Comment by krainboltgreene** [comment]
@segiddins I didn't write this.

**Comment by indirect** [comment]
@krainboltgreene since you originally rebased this, it looked like you were picking up the PR to get it finished and merged. If that's not true, that's fine, just let us know—given your previous comments on this PR, we thought it was yours.

**Comment by bronzdoc** [comment]
Is there interest in this PR to get it merged so i can pick it up? o can we close it?

**Comment by indirect** [comment]
@bronzdoc I would be okay with rebasing and merging or closing, your choice. 👍

**Comment by bronzdoc** [comment]
Closing since this feature has not been requested in almost 4 years

**Pull request closed without merging**
