### PR TITLE
Fix for large values in UID/GID fields in tar archives

### PR DESCRIPTION
**Pull request by conf**
# Description:
Fixes https://github.com/rubygems/rubygems/issues/2213.

Current check for octal values is too strict for some fields.
For example, on Windows workstations UID/GID values can be quite
large for domain members and cannot fit into 8 bytes when written
as octal values, so we need to allow 256-based values.

Both GNU tar and BSD tar implement this behavior, see
http://git.savannah.gnu.org/cgit/tar.git/tree/src/list.c#n861
and `tar_atol` implementation in
https://opensource.apple.com/source/libarchive/libarchive-41.20.1/libarchive/libarchive/archive_read_support_format_tar.c.auto.html
______________

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by conf** [comment]
@bronzdoc Thank you for a quick merge ❤️ ! Any idea when this gets released?

**Comment by jmartin-r7** [comment]
Adding another vote for getting this out in a release. 🙏

**Comment by hsbt** [comment]
Released 3.0.5 with this fix: https://blog.rubygems.org/2019/08/16/3.0.5-released.html

**Pull request merged**
