### PR TITLE
Bump rake version used by tests

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

None, just keeping things up to date and making them easier to update in the future.

## What is your fix for the problem, implemented in this PR?

Make it explicit that some tests depend on a specific version of rake being installed, and update that version.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by segiddins — APPROVED** [review]

**Comment by k0kubun** [comment]
This failed ruby/ruby's `make test-bundler-parallel` https://github.com/ruby/ruby/actions/runs/7184961196/job/19567221887, despite "ruby-core / Bundler under a ruby-core setup" passing here.

Do you have any idea how we can fix this?

**Comment by deivid-rodriguez** [comment]
Yeah! The automatic imported commit failed to import changes to `tool/bundler` files, so it's still using the old version. Those would need to be imported manually.

**Comment by deivid-rodriguez** [comment]
https://github.com/ruby/ruby/pull/9206 should fix it!

**Comment by k0kubun** [comment]
Thanks for the PR :+1:

> The automatic imported commit failed to import changes to tool/bundler files, so it's still using the old version. Those would need to be imported manually.

I just pushed https://github.com/ruby/ruby/commit/fd7decbf04f58438c04fa09fb325b16fbbec40c4, hoping it will not happen next time.

**Comment by deivid-rodriguez** [comment]
Yeah, I was just looking into that same fix! 👍

**Pull request merged**
