### PR TITLE
Windows Actions - export TMPDIR=$RUNNER_TEMP

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

1. Actions Windows CI currently uses VM's hosted on an 8 core system.  There is a hard drive (C:) and an SSD (D:).  ENV['TEMP'] & ENV["TMP'] both point to the hard drive.  From various Actions work/testing, the hard drive can be much slower than the SSD.

2. For legacy reasons, Windows supports what are referred to as 'long' and 'short' (8.3) file names.  ENV['TEMP'] & ENV["TMP'] use 'short' names.  Never having researched every possible method call in Ruby, I can't say for sure, but string comparisons could cause issues.

## What was the end-user or developer problem that led to this PR?

Odd issues with Windows Actions CI

## What is your fix for the problem, implemented in this PR?

For the 'temp path', I believe Ruby uses [ ENV['TMPDIR'], ENV["TEMP'], ENV["TMP'] ] to select the folder.  Set ENV['TMPDIR'] = ENV['RUNNER_TEMP'], which is a long file name on the SSD.
______________

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

I particularly liked the [screen grab](https://user-images.githubusercontent.com/2887858/78188599-cc3e1000-7470-11ea-9c35-6ed761429c75.png) in https://github.com/rubygems/rubygems/pull/3473#issuecomment-607500369, but I think https://github.com/rubygems/rubygems/pull/3488/checks?check_run_id=562758765 may be even better.

Especially considering that the two files changed in this PR were Window Actions yaml files...

**Comment by deivid-rodriguez** [comment]
@MSP-Greg I was very excited about making our Windows CI faster, but I don't see any speed up? :thinking:

**Comment by simi** [comment]
> For the 'temp path', I believe Ruby uses [ ENV['TMPDIR'], ENV["TEMP'], ENV["TMP'] ] to select the folder.

I was looking at the same recently. You're right (it is just in different order) https://github.com/ruby/ruby/blob/98f6c74b429f9e8afccb000da4a50920479dffd6/lib/tmpdir.rb#L23.

**Comment by deivid-rodriguez** [comment]
Where does the checked out code run?

I think that this shows no improvement, because it doesn't actually get used, since bundler specs reset it to the local `tmp/` folder:

https://github.com/rubygems/rubygems/blob/137aa0201ebc398b4f42fc3bda5944acf191a49e/bundler/spec/support/rubygems_ext.rb#L37

**Comment by MSP-Greg** [comment]
@simi Thanks.  I knew TMPDIR was first, didn't check the remaining two...

@deivid-rodriguez

1. I didn't say significant time savings.  There was a significant difference when downloading and extracting a large compressed file (containing several thousand files).  YMMV.  Disk I/O speed may or may not affect test times.

2. I didn't check if Bundler changes TMPDIR.  If it uses its own, never mind.

Closing.

**Comment by deivid-rodriguez** [comment]
I see, thanks.

**Pull request closed without merging**
