### PR TITLE
Fix bundler specs against Ruby 2.5

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Fixes a deadlock attempting to activate StringScanner in finish_resolve in activate_bin_path

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by drbrain** [comment]
@homu r+

**Comment by segiddins** [comment]
Doesn't seem to actually fix the failure >.<

@homu r-

**Comment by segiddins** [comment]
Fingers crossed this works

**Comment by segiddins** [comment]
Yup, this passes now!

**Comment by simi** [comment]
@segiddins do you know why this change is needed? It looks like a Ruby regression for me.

**Comment by segiddins** [comment]
@simi it's because the ruby standard library has had more parts turned into gems

**Comment by segiddins** [comment]
@drbrain r?

**Comment by segiddins** [comment]
Merging because this fixes the issue with the bundler/ruby-head test and no one has objected

@bundlerbot r+

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
