### PR TITLE
Backport ruby core

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Fixed the warnings with keyword separation feature of Ruby 2.7 and rondomly failed on GitHub Actions.
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
We need to wait a releasing bundler-2.1.0.pre.2.

**Comment by deivid-rodriguez** [comment]
I'll release 2.1.0.pre.2 today :+1:.

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot retry

**Pull request merged**
