### PR TITLE
Add GlobalSign Root CA - R3 cert and remove outdated certs

### PR DESCRIPTION
**Pull request by sonalkr132**
root CA of rubygems.org (and all subdomains) was updated from GlobalSign Organization Validation CA - SHA256 - G2 to GlobalSign Root CA - R3.
GlobalSignRootCA.pem was previously used to verify server cert if system certs could not verify rubygems.org cert.

## What was the end-user or developer problem that led to this PR?

Fixes when rubygem.org cert could not be verified by using system certs:
```
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)                                          
```
closes: #4099 

## What is your fix for the problem, implemented in this PR?

add GlobalSign R3 CA cert. used [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/remote_fetcher.rb#L88) to configure remove fetcher.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by hsbt — APPROVED** [review]

**Comment by hsbt** [comment]
@sonalkr132 Thanks! I will backport this to RG 2.7, 3.0 and 3.1.

**Comment by sonalkr132** [comment]
Thanks. Perhaps we should wait until @dwradcliffe confirms the removal of the old cert.
AddTrustExternalCARoot.pem was expired so it is fine to remove that. DigiCertHighAssuranceEVRootCA.pem is for cloudfront and I am positively sure that we don't have any CloudFront endpoints, however, a confirmation would be nice. It was added [more than seven years ago](https://github.com/rubygems/rubygems/blob/5ee6a59784b1736553e16fda374c18491bb66abe/lib/rubygems/ssl_certs/DigiCertHighAssuranceEVRootCA.pem).

**Comment by hsbt** [comment]
Ah, OK. I'm waiting to release the new versions of rubygems until approval from @dwradcliffe .

**Comment by indirect** [comment]
I can confirm that we previously used CloudFront as the S3 CDN, and we now use Fastly instead. It is ok to remove `DigiCertHighAssuranceEVRootCA.pem`. 👍🏻

**Comment by dwradcliffe** [comment]
I think there was still a cloudfront domain setup for legacy clients buts it’s probably time to stop supporting that.
👍🏻

**Pull request merged**
