### PR TITLE
Update my name in MAINTAINERS.md.

### PR DESCRIPTION
**Pull request by duckinator**
# Description:

Going forward, I'm going by the name Ellen Marie Marshall instead of Marie Markwell. This updates MAINTAINERS.md accordingly.

# Tasks:

- [x] Describe the problem / feature
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by simi** [comment]
*protip: You can use `[ci skip]` in commit message to not triggger CI tests for documentation changes.*

**Comment by indirect** [comment]
@simi Homu does not respect that, because the entire point of Homu is that developers are often wrong about what will break the build. :)

**Comment by simi** [comment]
@indirect ahh, ok. @duckinator sorry then. :sunny:

**Pull request merged**
