### PR TITLE
test_gem.rb - intermittent failure fix

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

Update assert_self_install_permissions method to hopefully stop intermittent failures

File.open -> File.write, move directory creation to top

# Tasks:

- [X] Describe the problem / feature
- [ ] Write tests
- [X] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
See PR #2568  aeb353f, PR #2605  e7ab095

Hopefully, third time's a charm...

**Comment by hsbt** [comment]
seems good. Thanks.

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by MSP-Greg** [comment]
@hsbt

A little off topic.  Seeing the 'allow failure' in trunk on Travis, I noticed that Travis CI is using Trusty/14.04, which uses OpenSSL 1.0.1 (EOL 2016-12?).  Are you ok with updating to Xenial/16.04 (OpenSSL 1.0.2)?

**Comment by hsbt** [comment]
@MSP-Greg It's welcomed if it resolves failure status of ruby-trunk on Travis.

**Comment by MSP-Greg** [comment]
Add 2.6.0 ?  If yes, both 'rubygems' & 'bundler'?

**Pull request merged**
