### PR TITLE
Use latest patch level Ruby releases in CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Not much, just making sure we're on latest.

## What is your fix for the problem, implemented in this PR?

Upgrade all the things.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by martinemde** [comment]
Windows builds besides 3.2 failed. I'm rerunning just to see if it's transient, but I'm not hopeful.

**Review by simi — APPROVED** [review]
no idea about the CI failures, but :+1: on update

**Comment by martinemde** [comment]
CI on windows is failing because `etc` is a default gem. Here's one of the errors:

```

**Comment by martinemde** [comment]
Aha, I think etc needs to be added to the exclusions. I'll push an update.

**Comment by martinemde** [comment]
I don't know if the change I pushed should specifically target windows since they are the only failing runs, or if my patch is fine excluding it always. It would seem to be a no-op on any other build since they were already passing.

**Comment by deivid-rodriguez** [comment]
Thanks for this. From https://github.com/rubygems/rubygems/actions/runs/6441869064/job/17492104237 I see that 3.2.2 was also passing?

Yes, I normally prefer to limit these exclusions to the environments are versions where the feature is not working, so that we can keep testing other combinations still work fine, and so that we can track how the feature evolves eventually remove the exclusion.

**Comment by martinemde** [comment]
> I see that 3.2.2 was also passing?
I tried to keep 3.2.2 in the tests. I tried to keep 3.2 in the tests. Did I mess up the conditional?

> Yes, I normally prefer to limit these exclusions to the environments are versions where the feature is not working

We could constrain to only windows (not sure why it only shows on windows)

**Comment by deivid-rodriguez** [comment]
Oh god, I actually read your message and assumed the exact content of your extra commit without even looking at it 😅. Yeah, the current patch is exactly what I meant, sorry about that.

**Comment by deivid-rodriguez** [comment]
> We could constrain to only windows (not sure why it only shows on windows)

Yep, that's my suggestion. Ruby On Windows adds some customisations through a `operating_system.rb` file that RubyGems loads when it's required. It could be that this file is now loading `etc` for some reason.

**Comment by martinemde** [comment]
Updated!

**Comment by deivid-rodriguez** [comment]
I can't approve my own PR but looks great!

**Review by simi — APPROVED** [review]
@deivid-rodriguez let's use my approval on your behalf :)

**Comment by martinemde** [comment]
Well you don't see this everyday (but I don't work with Ruby on Windows everyday):

```
       D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/injector.rb:90: [BUG] Segmentation fault
       ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
```

**Comment by deivid-rodriguez** [comment]
Never seen that before, and indeed rare to see Ruby segfault these days.

I'd say this may have been surfaced by the recent optimizations merged (maybe #6970?), since the [last build on master](https://github.com/rubygems/rubygems/actions/runs/6456478707/job/17526067804) also run into that, and also [a separate PR](https://github.com/rubygems/rubygems/actions/runs/6458388573/job/17532028630?pr=7042) is having issues with that spec.

**Pull request merged**
