### PR TITLE
Deterministic man txt pages

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Sometimes contributors get discrepancies in the generated txt man output, depending on the `groff` version being used, and that makes our man pages checks fail.

This PR tries to make the output more consistent.

As a side effect, it actually reads better.

References https://github.com/rubygems/rubygems/pull/3387#issuecomment-599261526.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by kevinburkemeter** [comment]
FYI, I'm using GNU groff on Mac and get this diff. Not clear why the escape sequences are being printed, it's frustrating.

```
-NAME
-       bundle-add - Add gem to the Gemfile and run bundle install
+1mNAME0m
+       1mbundle-add 22m- Add gem to the Gemfile and run bundle install

-SYNOPSIS
-       bundle     add     GEM_NAME     [--group=GROUP]     [--version=VERSION]
+1mSYNOPSIS0m
+       1mbundle     add     4m22mGEM_NAME24m     [--group=GROUP]     [--version=VERSION]
        [--source=SOURCE]   [--git=GIT]   [--branch=BRANCH]    [--skip-install]
        [--strict] [--optimistic]
```

**Comment by kevinburkemeter** [comment]
Also not sure whether that's coming from "col" or "groff" - I tried compiling "col" on my Mac from the linux-utils source to remove the diff and no dice.

**Comment by deivid-rodriguez** [comment]
Those look like color escape sequences, could you edit the `rake` task to pass the `-c` flag to `groff` (which according to my man page) and see if it helps?

**Comment by deivid-rodriguez** [comment]
That difference doesn't show up in https://github.com/rubygems/rubygems/pull/3387/files though, so I should assume this PR is fixing the whitespace discrepancies?

**Comment by kevinburkemeter** [comment]
I can get it closer to what you have by setting GROFF_NO_SGR=true in the environment before running. Still I'm confused by this diff. Maybe I need to pass an option that says don't hyphenate words.

```
-BUNDLE-ADD(1)							 BUNDLE-ADD(1)
+BUNDLE-ADD(1)                                                    BUNDLE-ADD(1)



@@ -6,13 +6,13 @@ NAME
        bundle-add - Add gem to the Gemfile and run bundle install

 SYNOPSIS
-       bundle	  add	  GEM_NAME     [--group=GROUP]	   [--version=VERSION]
-       [--source=SOURCE]   [--git=GIT]	 [--branch=BRANCH]    [--skip-install]
+       bundle     add     GEM_NAME     [--group=GROUP]     [--version=VERSION]
+       [--source=SOURCE]   [--git=GIT]   [--branch=BRANCH]    [--skip-install]
        [--strict] [--optimistic]

 DESCRIPTION
-       Adds  the  named  gem  to  the  Gemfile	and run bundle install. bundle
-       install can be avoided by using the flag --skip-install.
+       Adds  the  named  gem to the Gemfile and run bundle install. bundle in-
+       stall can be avoided by using the flag --skip-install.

        Example:

@@ -29,30 +29,30 @@ DESCRIPTION

 OPTIONS
        --version, -v
-	      Specify version requirements(s) for the added gem.
+              Specify version requirements(s) for the added gem.

        --group, -g
-	      Specify  the  group(s) for the added gem. Multiple groups should
-	      be separated by commas.
+              Specify  the  group(s) for the added gem. Multiple groups should
+              be separated by commas.

        --source, , -s
-	      Specify the source for the added gem.
+              Specify the source for the added gem.
```

**Comment by kevinburkemeter** [comment]
The difference comes because my program is replacing a tab with a space character, and the checked in output deletes the tab characters altogther.

**Comment by deivid-rodriguez** [comment]
> The difference comes because my program is replacing a tab with a space character, 

That is exactly what this PR is doing, so it should fix the problem in that case! :)

**Comment by kevinburkemeter** [comment]
OK. Now the only difference is my program is inserting hyphens and yours isn't. I can't see why that's happening. I asked https://stackoverflow.com/q/60712000/329700 in the hopes of finding an answer.

**Comment by kevinburkemeter** [comment]
Here's what I'm running

```
$ groff --version
GNU groff version 1.22.4
Copyright (C) 2018 Free Software Foundation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file
named COPYING.

called subprograms:

GNU grops (groff) version 1.22.4
GNU troff (groff) version 1.22.4
```

**Comment by kevinburkemeter** [comment]
Aha, it's entirely the difference between groff 1.22.3 (the default on Ubuntu) and 1.22.4. I compiled Groff 1.22.3 on my Mac and it's not generating a diff anymore.

**Comment by kevinburkemeter** [comment]
ok, LGTM

**Comment by kevinburkemeter** [comment]
oh, I still think it is a good idea to enable `--warnings` in ronn, this is so finicky that it seems better to be able to see things than to not see them.

**Comment by deivid-rodriguez** [comment]
Nice research! Thanks for documenting all that :purple_heart:.

> oh, I still think it is a good idea to enable --warnings in ronn, this is so finicky that it seems better to be able to see things than to not see them.

Yep, that's what I'm doing in this PR too. Previously they were ignored.

**Comment by kevinburkemeter** [comment]
I don't see it? looks like this line is unchanged

```ruby
          sh "bin/ronn --roff --pipe --date #{Time.now.strftime("%Y-%m-%d")} #{ronn} > #{roff}"
```

**Comment by deivid-rodriguez** [comment]
Oh, sorry, I meant in `groff` (what converts `.roff` to `.txt`), where I changed `-Wall` (ignore all warnings) to `-wall` (show all warnings).

We can definitely enable warnings in `ronn` too, I'll add that here :+1:.

**Comment by deivid-rodriguez** [comment]
I think the hyphenation discrepancy could be fixed by adding a line with `.nh` right after the `.TH` line on every man page. Could be added as a `ronn` feature or do it ourselves.

**Comment by deivid-rodriguez** [comment]
I _think_ I figured it out thanks to https://stackoverflow.com/questions/22712319/run-aspell-on-manpage#22713606.

With this, I think we might fully eliminate the discrepancies between `groff` versions?

Also, the new output is much better because hyphenation was also applied to actual shell commands, and that could confuse some people.

**Comment by deivid-rodriguez** [comment]
Let's do it! Hopefully this makes txt man pages more readable and eases documentation contributions.

**Pull request merged**
