### PR TITLE
Add support for `bundle gem --rust` command

### PR DESCRIPTION
**Pull request by ianks**
## What was the end-user or developer problem that led to this PR?

Despite the recent support of Rust/Cargo as a supported language for developing Ruby gems (#5175), it's still too hard to scaffold out a Rust gem. It should be as easy to scaffold a Rust extension as it is a C extension.

## What is your fix for the problem, implemented in this PR?

This PR adds the ability to scaffold a Rust gem by running: `bundle gem --rust`. A few key points about this integration are:

1. Works perfectly with `rake-compiler` via the `rb_sys` gem
2. Opted to use the [magnus](https://github.com/matsadler/magnus) crate, as I believe it offers the most correct and easy to use bindings for Ruby, plus it supports interop with [rb-sys](https://github.com/oxidize-rb/rb-sys). With magnus, gem authors can avoid writing unsafe code when authoring a new gem in Rust.
3. Scaffolded gems make use of the [rb-allocator](https://github.com/oxidize-rb/rb-sys/tree/main/crates/rb-allocator), so Rust memory usage is properly reported to the Ruby GC.
4. I prefer using the `--rust` flag over something like `--ext=rust`. It's much nicer to read and write.

Looking forward to everyone's feedback!

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by simi** [comment]
Damn, I have missed one. I have code prepared for `--ext=rust` (backwards compatible) which seems better to me. I tried to keep it as close as possible with C extension (using `ext` folder, ...). Would you mind to check that one (https://github.com/rubygems/rubygems/commit/548189dd018f2e1a66525c168ada9868f8100f2e) as well? It creates `"ext/<%= config[:name] %>.rs"`, but I wasn't sure how to keep it as close as possible to common Rust package.

Maybe we can just keep the standard Rust (Cargo) structure, but in `ext` or `ext-rust` subfolder. WDYT? That way for `bundle gem newgem --ext=rust` you'll find this structure (next to common gem one):

```
ext/src/newgem.rs
ext/Cargo.toml
```

So actual changing directory to `ext`, you'll get the original `Cargo` feeling. Also we need to add generated dummy tests for nice and smooth experience. Those were last 2 blockers for me to open PR, but due to lack of time and ideas I wasn't able to move it forward.

Btw. we can make `--rust` alias to `--ext=rust` if needed.

**Comment by simi** [comment]
@ianks do you plan to continue on this or should I take over? I would like to merge with my branch and test.

**Comment by simi** [comment]
@ianks friendly pingie. I'll have time this weekend, I can try to finish it if welcomed.

**Comment by ianks** [comment]
@simi can you take it from here? things got busy for me!!

**Comment by ianks** [comment]
@simi let me know if you run into any issues!

**Comment by ankane** [comment]
Hi, excited to see this included in Bundler!

I just tried moving [a project](https://github.com/ankane/tokenizers-ruby) to this directory structure and think there may be a potential issue.

From what I can tell, the Cargo builder always places the shared library in `lib`. However, the `rake-compiler` configuration places it in `lib/#{gem_name}` (which is what the `require_relative` expects).

This may be something worth changing or making configurable with the Cargo builder.

**Comment by ianks** [comment]
For others that stumble on this, check out the structure I setup for [`wasmtime-rb`](https://github.com/bytecodealliance/wasmtime-rb), I think it serves as a good standard

**Comment by ankane** [comment]
Hmm, it doesn't seem to install correctly when using `spec.extensions = ["ext/Cargo.toml"]` and Ruby 3.2.0-preview2.

On installation, it creates `lib/wasmtime-rb.bundle` on Mac, but `lib/wasmtime.rb` has `require "wasmtime/ext"`, so it fails with:

```text
cannot load such file -- wasmtime/ext (LoadError)
```

**Comment by ianks** [comment]
> Edit: require "wasmtime-rb" should work in this case, but for a gem name like hello, you'll end up with lib/hello.rb and lib/hello.bundle and have to use require "hello.#{RbConfig::CONFIG["DLEXT"]}" to require it.

Yeah you end up having to use a different name each. It's even a bit more entailed because for cross compiled gems you have to load based on the Ruby version.

**Comment by deivid-rodriguez** [comment]
This PR can be closed now, correct?

**Comment by simi** [comment]
Yes

Dne st 21. 12. 2022 18:45 uživatel David Rodríguez ***@***.***>
napsal:

**Comment by deivid-rodriguez** [comment]
Thanks for getting this started @ianks!

**Pull request closed without merging**
