### PR TITLE
Return a "rb" extension file when the same name file exists

### PR DESCRIPTION
**Pull request by y-yagi**
When a file of the same name exists, I think that should read a load of the "rb" extension, how about?

### CODE REVIEW

**Comment by kou** [comment]
The patch approach is right because the behavior is the same as Ruby's original `require`.

Here is a script that confirms the Ruby's original `require` behavior:

```ruby
require "fileutils"

tmp_dir = File.expand_path("tmp/require-test")
FileUtils.rm_rf(tmp_dir)

load_path1 = File.join(tmp_dir, "load-path1")
load_path2 = File.join(tmp_dir, "load-path2")

FileUtils.mkdir_p(load_path1)
FileUtils.mkdir_p(load_path2)

$LOAD_PATH.replace([load_path1, load_path2])

# .rb is placed at the latter load path.
FileUtils.touch(File.join(load_path1, "require-test1.so"))
FileUtils.touch(File.join(load_path2, "require-test1.rb"))

puts "require-test1"
require "require-test1"
puts $".last # => "/.../tmp/require-test/load-path2/require-test1.rb" not "require-test1.so"

# .rb is placed at the same load path.
FileUtils.touch(File.join(load_path1, "require-test2.so"))
FileUtils.touch(File.join(load_path1, "require-test2.rb"))

puts "require-test2"
require "require-test2"
puts $".last # => "/.../tmp/require-test/load-path1/require-test2.rb"
```

In Ruby's source code, suffixes are outer loop and load paths are inner loop.

https://github.com/ruby/ruby/blob/trunk/file.c#L5699-L5714 :

```c
    for (j=0; ext[j]; j++) {
        rb_str_cat2(fname, ext[j]);
        for (i = 0; i < RARRAY_LEN(load_path); i++) {
            VALUE str = RARRAY_AREF(load_path, i);

            RB_GC_GUARD(str) = rb_get_path_check(str, safe_level);
            if (RSTRING_LEN(str) == 0) continue;
            rb_file_expand_path_internal(fname, str, 0, 0, tmp);
            if (rb_file_load_ok(RSTRING_PTR(tmp))) {
                *filep = copy_path_class(tmp, *filep);
                return (int)(j+1);
            }
            FL_UNSET(tmp, FL_TAINT);
        }
        rb_str_set_len(fname, fnlen);
    }
```

@zzak Could you check this?

**Comment by drbrain** [comment]
Yep, this patch is correct

**Comment by y-yagi** [comment]
hi, is there something else needed for this pull request to be merged?

**Comment by kou** [comment]
Sorry for late response.
I've merged this pull request. Thanks!

**Comment by y-yagi** [comment]
Thanks!!

**Pull request merged**
