### PR TITLE
Use `bundler` version 1.17.1

### PR DESCRIPTION
**Pull request by springerigor**
# Description:

Bundler 1.17.1 was released on 2018-10-25 (https://github.com/bundler/bundler/blob/master/CHANGELOG.md). 

This PR updates the `bundler` submodule to use it.

______________

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
I think some people would prefer to stay with bundler 2.0.0.pre.1...

**Comment by springerigor** [comment]
@MSP-Greg Could you elaborate? Right now version `1.16.6` is used.

**Comment by MSP-Greg** [comment]
@springerigor 

Sorry, I'm mistaken.  I just looked at trunk, assuming it uses the same bundler version as here.  It does not.

**Comment by springerigor** [comment]
@MSP-Greg No problem, thanks for the input :)

**Comment by springerigor** [comment]
It looks like [the backport](https://github.com/bundler/bundler/pull/6752/files) is not a part of Bundler 1.17.1  :-(

**Comment by colby-swandale** [comment]
@hsbt updated the `1-17-stable` with the backport. If you update to the latest commit - it should pass.

**Comment by springerigor** [comment]
Thanks @colby-swandale. The builds are green now :-)

**Comment by segiddins** [comment]
Thanks!  @bundlerbot r+

**Comment by colby-swandale** [comment]
@bundlerbot r+

**Pull request merged**
