### PR TITLE
Fix parallel testing for ruby trunk

### PR DESCRIPTION
**Pull request by hsbt**
@tenderlove I tried to merge rubygems upstream to ruby/ruby trunk. It happened some issues when running with parallel.

I fixed these issues. Can you review this pull request?

### CODE REVIEW

**Comment by hsbt** [comment]
Working branch is here: https://github.com/ruby/ruby/pull/915

**Comment by tenderlove** [comment]
How do I reproduce the error on Ruby trunk?  It looks like Ruby is loading Rubygems code twice?  Is that expected?

**Comment by hsbt** [comment]
@tenderlove Use my working branch and run ```make test-all TESTS="-j4"```

**Comment by tenderlove** [comment]
@hsbt does the parallel tester use threads or processes? (I am curious).  The RubyGems tests are definitely not thread safe.

**Comment by hsbt** [comment]
use threads.

**Comment by indirect** [comment]
@tenderlove are you good with merging this? these particular changes seem like strictly an improvement, even if they don't make the entire test suite thread-safe.

**Comment by tenderlove** [comment]
I'm fine with merging this.  It doesn't actually change anything except to hide the fact that code is being loaded twice in the parallel environment.  I would not call that "strictly an improvement".  Ideally we should figure out why the code is being loaded twice and fix that.  This is addressing a symptom.

**Comment by hsbt** [comment]
@tenderlove I continue to investigate thread-safe issue on ruby trunk tests.

**Pull request merged**
