### PR TITLE
Little cleanup in test suite

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Just some cleanups in the test suite. I made this while working on #3131.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
This is currently introducing a flaky test failure, so I prefer to investigate that before merging, ok?

@bundlerbot r-

**Comment by deivid-rodriguez** [comment]
This PR should be ready now. The idea was to kill some complicated logic with `$LOADED_FEATURES` restoring.

Previously, the tests would assume that a "meaningful feature", like say `rubygems/gem_runner` could be loaded in he middle of a test. That means not all "dummy features" loaded by a test (like test gems and things like that) need to be removed from the `$LOADED_FEATURES` global variable after the test. These "meaningful features" need to be preserved because if they are not, other tests might load them, and since they are not in `$LOADED_FEATURES`, `require` will think they haven't yet been loaded and will load them again, causing redefinition warnings.

So we have code like:

https://github.com/rubygems/rubygems/blob/39fae05861bb71fb9d0aa12b50c16d9b0362fbbe/lib/rubygems/test_case.rb#L427-L439

This strategy is overcomplicated and also brittle. For example, under the ruby-core setup of tests as proposed in https://github.com/ruby/ruby/pull/3213, where `.` is in the `$LOAD_PATH`, and `tmp` is contained inside `.`, this logic fails to work properly and that's what's causing the failures there.

As an alternative, we make sure tests only load "dummy feaures" and every thing else is preloaded. And with that prerequisite, we can kill all this logic.

**Comment by deivid-rodriguez** [comment]
Most of the changes had been introduced separately. I rebased this and left the changes the still make sense to me, I removed the cleanup I mentioned in the previous message because it didn't seem worth it now.

**Pull request merged**
