### PR TITLE
Fix typo in `bundle pristine` warning message

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

s/overriden/overridden/

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
TIL `[ci skip]` [doesn't work with GitHub Actions](https://github.community/t/github-actions-does-not-respect-skip-ci/17325/12).

**Review by deivid-rodriguez — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Yeah, we prefer not to use `[ci skip]` in any case. See https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages.

**Comment by deivid-rodriguez** [comment]
@hsbt I edited the title because this is the wording `bundler`'s changelog will use, so we don't want `[ci skip]` in there either.

**Comment by deivid-rodriguez** [comment]
Also, isn't setting the `3.2.0` milestone a bit confusing here? Next bundler version is `2.2.0` even if we will release it in sync with rubygems `3.2.0` from this repository. I don't have a problem with it if it helps you, but I don't think there's any other bundler PR tagged with `3.2.0`.

**Comment by hsbt** [comment]
I thought that we would release bundler-2.2.0 and rubygems-3.2.0 from `3.2` branch. Because I set the `3.2.0` milestone to them. But I also okay to use `bundler-2.2.0` milestone for it separated with rubygems-3.2.0 milestone.

@deivid-rodriguez What way to useful for you?

**Comment by deivid-rodriguez** [comment]
> I thought that we would release bundler-2.2.0 and rubygems-3.2.0 from 3.2 branch

Yes, that's the plan :+1:.

Our current case is pretty unique, but normally milestones map to software versions, not to branch names, that's why when I saw the `3.2.0` milestone, I thought this PR was changing code in `rubygems`. So I personally find the `rubygems-3.2.0` and `bundler-2.2.0` convention for naming milestones more clear.

That said, you're currently the only one using milestones at the moment (I don't use them for anything), so whatever you prefer to use is fine to me.

**Comment by hsbt** [comment]
> Yes, that's the plan 👍.

👍 

I renamed https://github.com/rubygems/rubygems/milestone/31 to `RubyGems 3.2.0/Bundler 2.2.0` now. When we remains to confuse them, We will separate its milestone.

**Pull request merged**
