### PR TITLE
Remove hoe for test suite.

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

This is part of https://github.com/rubygems/rubygems/pull/2139/

______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
Why was this merged without review!?

**Comment by hsbt** [comment]
> Why was this merged without review!?

Because I'm a reviewer for #2139.

**Comment by colby-swandale** [comment]
ah, thanks pointing that out @hsbt

**Comment by indirect** [comment]
@hsbt thank you for doing this! the way Hoe was set up has also caused many new tickets to be opened by developers who want to contribute but don't already know how Hoe works and how to use it, so I think this will be an improvement there, too.

**Pull request merged**
