### PR TITLE
fixup #2441: `make` arguments as an array too

### PR DESCRIPTION
**Pull request by nobu**
# Description:

I forgot to modify `Gem::Ext::Builder.make` to call `run` with a command array at #2441.
______________

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Can you add a test for the issue this is fixing?

**Comment by nobu** [comment]
Seems current tests depend on the behaviors of `shellescape` too much.
I'll need to refactor those fragile tests first.

**Comment by bronzdoc** [comment]
ping @nobu

**Comment by deivid-rodriguez** [comment]
This is the same as #4190. I'll close this and add @nobu's attribution to my commit there.

**Pull request closed without merging**
