### PR TITLE
removing unused code from dependency_installer.rb

### PR DESCRIPTION
**Pull request by bronzdoc**

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by copiousfreetime** [comment]
:+1:

**Comment by copiousfreetime** [comment]
Question on this, the note says remove for Rubygems 3, Is this the plan here?

**Comment by bronzdoc** [comment]
I think it's part of that plan, there's alot more to remove...
```
lib/rubygems.rb:    # TODO remove with RubyGems 3.0
lib/rubygems/resolver/activation_request.rb:      when true then # TODO remove at RubyGems 3
lib/rubygems/resolver/activation_request.rb:      when false then # TODO remove at RubyGems 3
lib/rubygems/ext/ext_conf_builder.rb:          # TODO remove in RubyGems 3
lib/rubygems/validator.rb:    # TODO remove me? The code here only validate an MD5SUM that was
lib/rubygems/resolver.rb:# TODO remove in RubyGems 3
lib/rubygems/compatibility.rb:  # TODO remove at RubyGems 3
lib/rubygems/compatibility.rb:    ConfigMap = Hash.new do |cm, key| # TODO remove at RubyGems 3
```
haven't looked at those, but this one in specific was pretty obvious is not needed and it just make noise for someone new trying to undestand the codebase.

**Comment by drbrain** [comment]
Can we merge this before we start 3.x work?  This code was still live in 2.0

**Comment by drbrain** [comment]
… no, they were only marked `nodoc` in 2.1 so we can't remove them until 3.x: https://github.com/rubygems/rubygems/commit/f0097e209268baf8e9bd2a43a76b495caac51efa

**Comment by hsbt** [comment]
I've marked deprecated these methods. I will close this and remove at RubyGems 4.0.

**Pull request closed without merging**
