### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:
I recently closed [PR 2135](https://github.com/rubygems/rubygems/pull/2135) for test updates, since I knew I was missing something.

I was incorrectly assuming that default spec files were being loaded into `File.join(@gemhome, "specifications", "default")`, but they are loaded into another directory.  So, after realizing that, I proceeded with changes & testing.

I've tested it quite a few times, found one additional issue, along with the update to Minitest 5.11.

This PR does the following:

1. Seems to remove/fix all intermittent failures.  I assume most are due to test leaks, but I didn't set a goal of making sure I found the source of **all leaks**.    IOW, should test leaks be fixed in the source or the tests affected by them?  Some might say only the source, other more pragmatic types might say both.  Regardless, I believe I've run the tests often enough to know that a combination of cleaning leaking tests and cleaning affected tests has been done.

2. Removes hoe from Travis RG testing, matching Appveyor and ruby/ruby.

3. test_case.rb - Adds a method `util_clear_gemspecs`, which clears standard and default gemspec files.  Also, added clearing of default gemspec files to ``util_clear_gems`.

4. Cleans up some `$SAFE` issues, reset for now in `test_gem.rb`.

5. `@name` - Minitest v5.11 had a naming clash with `test_gem_source_git.rb`, so `@name` is renamed `@r_name`.

6. `Binding.source_location` warnings in head/trunk are fixed by [bundler PR #6237](https://github.com/bundler/bundler/pull/6237).  On my fork, I added a patch for this to my Appveyor testing, and all warnings disappeared.

7. For example results, see my fork's [Travis builds](https://travis-ci.org/MSP-Greg/rubygems/builds), note that I bypassed the bundler testing.

# Tasks:

- [X] Describe the problem / feature
- [ ] Write tests
- [X] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@MSP-Greg Can you separate a `File.open` changes? It is not scope of test fixes.

**Comment by MSP-Greg** [comment]
@hsbt

`File.open` changes are in:

1. `lib/rubygems/test_case.rb`
2. Several files in `test/rubygems/`

By separated, do you mean removed from this PR, or additional commit(s) to it?  Without them, all generated 'security warnings' in trunk with `$SAFE = 1`, which is in `test/rubygems/test_gem.rb` before this PR...

**Comment by MSP-Greg** [comment]
This PR has now run twelve times on my fork with no failures/errors.  Info is [here](https://travis-ci.org/MSP-Greg/rubygems/builds).

Since the intermittent issues have not seemed to be ruby version related, with twelve jobs per build, this represents 144 test runs...

FYI...  Thanks, Greg

**Comment by hsbt** [comment]
>do you mean removed from this PR

I mean Removing this pull request. (and can you submit another pull request?).

**Comment by MSP-Greg** [comment]
@hsbt

Yes, I can do that.  Just waiting for Appveyor to finish on my fork, Minitest released 5.11.1 (fixed the issue), so I removed that, along with all the `open` -> `File.open` changes...  Thanks.

**Comment by MSP-Greg** [comment]
@hsbt 

I haven't tried to diff them, are the ruby/ruby tests the same as these tests?  I haven't tried testing in ruby yet, but I might as well...

**Pull request closed without merging**
