### PR TITLE
Prepare rubygems 3.3.10 and bundler 2.3.10

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It's release day!

@simi two questions. Cool with releasing #5175 now, right? Also, may I also sneak #5416 into the release?

### CODE REVIEW

**Comment by simi** [comment]
I'm ok to release https://github.com/rubygems/rubygems/pull/5175, but I would not promote it for now unless `bundler gem` integration is done, which is going to introduce Rust extension gem structure. The gem structure in tests (which is the only reference implementation I'm aware of) is currently simplified and it will be changed as well in the `bundler gem` integration to follow the structure.

**Comment by deivid-rodriguez** [comment]
I see, so we can release it without a changelog entry? I think there's no rush to ship it, so we can also just delay it a little bit until we can tweak the `bundle gem` generated skeleton. What do you think?

**Comment by deivid-rodriguez** [comment]
Oh, ok, so we release it normally but don't further promote it for now 👍.

**Comment by deivid-rodriguez** [comment]
Actually, the ruby-core job seems broken due to #5175. Mind skipping it for this release and I'll work on making it green for 3.3.11?

**Comment by simi** [comment]
Feel free to skip it for now if needed.

_Btw. @hsbt planned to include it into Ruby 3.2.preview1 if I remember well. We need to fix the problems anyway soon._

**Comment by deivid-rodriguez** [comment]
Yes, I will address it for next release. But I think it won't block 3.2.preview1 anyways, because this issue seems specific to our stable branch, and I think 3.2.preview1 is cut from Ruby's master branch, which seems fine.

**Comment by simi** [comment]
There are some troubles already AFAIK - https://github.com/ruby/ruby/pull/5669.

**Pull request merged**
