### PR TITLE
Fix invalid links in documentation.

### PR DESCRIPTION
**Pull request by simi**
- wrap ENV variables in `<code>`
- fix rubygems.org link
- fix zenspider.com link

fixes https://github.com/rubygems/rubygems/issues/6986

### CODE REVIEW

**Review by deivid-rodriguez — APPROVED** [review]
:heart_eyes:

**Comment by nobu** [comment]
Please separate the subject line in the commit log from the rest by an empty line, as the `git`'s convention.

**Comment by simi** [comment]
> Please separate the subject line in the commit log from the rest by an empty line, as the `git`'s convention.

Is it? I have never seen that anywhere being convention. Any reference on that? I'll do next time. Sorry for troubles.

**Comment by deivid-rodriguez** [comment]
We could configure https://github.com/bkuhlmann/git-lint#github-actions if we wanted to enforce this. Particularly if it could cause some ruby-core scripts to break.

**Comment by nobu** [comment]
`git` treats the first paragraph (separated by an empty line) of commit logs as subjects, and concatenates all lines in the paragraph with a space.

I can't share the good pointer, but you can see the subject of the commit is one line:
```sh-session
$ git --no-pager log --pretty=%s -1 9eaac94a63
Fix invalid links in documentation. - wrap ENV variables in <code> - fix rubygems.org link - fix zenspider.com link
```

In this case, `%b` (body) is empty.

**Pull request merged**
