### PR TITLE
Removed bundled RDoc code

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

It's no longer used in 2018.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by colby-swandale** [comment]
Is this a maintenance burden or is there any particular reason why this should be removed beyond no one uses it? I would like other peoples opinions on this before we remove this feature.

**Comment by hsbt** [comment]
@colby-swandale Ruby 2.2 has RDoc 4.2.0 as the standard library. So, It code never use in the future. And this bundled code have no test, We can not maintain it.

**Comment by segiddins** [comment]
Ooooh this is exciting! 👍🏻

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by colby-swandale** [comment]
thanks for the explanation @hsbt

**Pull request merged**
