### PR TITLE
Raise error if the email is invalid when building cert

### PR DESCRIPTION
**Pull request by bronzdoc**
closes https://github.com/rubygems/rubygems/issues/1777

### CODE REVIEW

**Comment by segiddins** [comment]
(Don't worry about the test failures on CI, I'm fixing that on the bundler side ASAP)

**Comment by bronzdoc** [comment]
:+1:  @segiddins 
@homu r+

**Comment by bronzdoc** [comment]
@homu retry

**Comment by djberg96** [comment]
I think if we're going to go through the trouble of validating an email, we should be a little more rigorous. I'm not saying we need 100% compliance, but how about:

    /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

**Comment by drbrain** [comment]
I'd prefer less rather than more for email verification unless you can send an email with a verification link.

PS: `/.@./` should be sufficient.

**Comment by segiddins** [comment]
> PS: /.@./ should be sufficient.
actually the current regexp validates against newlines, so they're not equivalent

**Comment by drbrain** [comment]
Since we're being pedantic, newlines are allowed in email addresses.

**Pull request merged**
