### PR TITLE
Use bundler to manage bundler development dependencies

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

This is an experiment I made today to try use bundler to manage bundler development dependencies. Still WIP.

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by indirect** [comment]
I am very excited about this. Last time I tried, I eventually gave up. 😂 Hopefully it's easier to get working now!

**Comment by deivid-rodriguez** [comment]
Yeah, this is like the third time I try. The other times I gave up without even bothering to open a WIP PR :rofl:

**Comment by deivid-rodriguez** [comment]
Holy shit, had never managed to break some many specs at once before :rofl:

imagen

**Comment by deivid-rodriguez** [comment]
Seems to be working! :)

**Comment by deivid-rodriguez** [comment]
Great! :smile:

**Pull request merged**
