### PR TITLE
How we use LGTM.co

### PR DESCRIPTION
**Pull request by krainboltgreene**
At least two people need to :+1: or LGTM a PR before the status check passes the lgtm.co check.

### CODE REVIEW

**Comment by segiddins** [comment]
Why are we using this instead of `homu`?

**Comment by duckinator** [comment]
My thoughts on using this instead of homu is that the commands for LGTM are more intuitive than the ones for homu, but I don't object to using homu instead if that would be preferred.

**Comment by indirect** [comment]
I like the way that LGTM makes it easy, but I very strongly prefer the way that Homu builds the merge commit and automatically finalizes the merge if it passes. Maybe we can improve the interface to Homu instead of using LGTM?

**Comment by duckinator** [comment]
Yeah, I'm definitely down with that.

**Comment by krainboltgreene** [comment]
Yep, same here. I feel like maybe the documentation on homu didn't really sell it for me.

**Comment by duckinator** [comment]
Closing this since we're going with homu.io.

**Pull request closed without merging**
