### PR TITLE
Make Gem::Specification#ruby_code handle OpenSSL::PKey::RSA objects

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
closes https://github.com/rubygems/rubygems/issues/2776

@zenspider what you think?
______________
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by zenspider** [comment]
That seems fine to me, but I suspect this is used to serialize specs still. Skipping outright might be a better option... I'd want someone more in the know to weigh in on that. I haven't maintained rubygems in ages.

But for MY purposes, as long as it doesn't crash I'm happy.

**Comment by zenspider** [comment]
Also, thank you. That was very timely.

**Comment by deivid-rodriguez** [comment]
I would vote for completely skipping this field too. As far as I know, this is only used at `gem build` time, and it's no longer needed once the deserialized spec file is installed to the final user system?

**Comment by bronzdoc** [comment]
Removing the signing key trigger a couple of errors, and made me notice we are printing the `cert_chain` too but since it's an array it's handled by:

```ruby
when Array              then '[' + obj.map { |x| ruby_code x }.join(", ") + ']'¬
```

so kinda the output we want to avoid by not doing `to_s` or to `to_text` from a OpenSSL::PKey::RSA object, should we skip the `cert_chain` attribute too?

**Comment by bronzdoc** [comment]
Build failures are not related to this change, I don't understand why travis is having issues with bundler in this particular PR 🤔

**Comment by zenspider** [comment]
The tests know how much I hate bundler and are getting back at me. 🙁

**Comment by MSP-Greg** [comment]
I think this may be the result of the older version of bundler currently being used.

I believe the changes in https://github.com/bundler/bundler/commit/e742c3d5f458a4a59cf0eaab2567eca844f956d1 / https://github.com/bundler/bundler/pull/7100 will fix this.

But, it breaks Ruby master/trunk/ruby-head builds when they are used for CI testing. That fix is at https://github.com/bundler/bundler/pull/7248

**Comment by zenspider** [comment]
... status? There's been 4 releases since this came up...

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
