### PR TITLE
Support Keyword args with Pysch.

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

I picked commits related Kernel#warn feature with Ruby 2.5+ and keyword args support of Pysch-3.1.0.pre1 from ruby core repository.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Why are we adding in more redefinitions of methods in the stdlib?

**Comment by hsbt** [comment]
@nobu Can you describe it?

**Comment by nobu** [comment]
Please see https://github.com/rubygems/rubygems/pull/2442.

**Comment by nobu** [comment]
Please see https://github.com/rubygems/rubygems/pull/2442.

**Comment by nobu** [comment]
Please see https://github.com/rubygems/rubygems/pull/2442.

**Comment by nobu** [comment]
Please see https://github.com/rubygems/rubygems/pull/2442.

**Comment by nobu** [comment]
Please see https://github.com/rubygems/rubygems/pull/2442.

**Comment by segiddins** [comment]
Even after looking at that PR, I can't understand why we need to redefine a method in `Kernel` inside of rubygems

**Comment by duckinator** [comment]
@segiddins it looks like, due to how `require` is redefined by RubyGems, the warning shows the wrong file, so it's hard to find the true source of the warning.

**Comment by MSP-Greg** [comment]
@segiddins 

> Even after looking at that PR, I can't understand why we need to redefine a method in Kernel inside of rubygems

One might say that RubyGems is inserting itself into the 'callstack' by redefining `require`.  Since most Ruby reporting (errors, warning, etc), is 'callstack' based, and some of the reporting (warnings) only show the 'first' item in the 'callstack', an adjustment should be made somewhere...

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
