### PR TITLE
Do not use #quick_spec internally

### PR DESCRIPTION
**Pull request by maclover7**
# Description:

The method is slated to be removed in RG 3.0, so we might as well use
the replacement now.
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

The method is slated to be removed in RG 3.0, so we might as well use
the replacement now.

### CODE REVIEW

**Comment by hsbt** [comment]
Should we remove `TestCase#quick_spec` from test_case.rb?

I confirmed that It was only used rdoc-3.x in all of gems.

**Comment by segiddins** [comment]
@hsbt that's a backwards incompatible change that will have to wait until RG 3

**Comment by maclover7** [comment]
👍 just trying to remove internal usage of something that will be removed in the future

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
