### PR TITLE
Disable CmakeBuilder specs on Windows.

### PR DESCRIPTION
**Pull request by duckinator**
As per https://github.com/rubygems/rubygems/issues/1270#issuecomment-177393386.

cc @indirect

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:

**Comment by indirect** [comment]
Thanks! Can you rebase this? It looks ready to merge.

**Comment by duckinator** [comment]
Rebased.

**Comment by duckinator** [comment]
@indirect was I supposed to merge this after rebasing it? (I assumed that the general approach was for whoever okays it to merge it, as that's how it was on all of the other PRs I'd opened.)

**Comment by segiddins** [comment]
@duckinator in most projects I work on, the person who opens the PR merges after getting :+1: (to avoid prematurely merging PRs). So go ahead and merge this one ;)

**Comment by duckinator** [comment]
Okay. Rebased again; waiting for CI to finish.

**Pull request merged**
