### PR TITLE
Update cryptography for Gem::Security

### PR DESCRIPTION
**Pull request by sdaubert**
# Description:

Update cryptography for Gem::Security as proposed in #1688 :
- replace SHA-1 digest by SHA-256 for signing with RSA algorithm,
- update default RSA key length from 2048 to 3072 bits.

---
# Tasks:
- [X] Describe the problem / feature
- [X] Write tests
- [X] Write code to solve the problem
- [ ] Get code review from coworkers / friends
- [ ] [Squash commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by djberg96** [comment]
Looks good to me, though now I'm wondering why the digest algorithm is declared as a constant instead of something that could be configured. Perhaps that's for another time, though.

**Comment by sdaubert** [comment]
I don't understand why travis build failed for ruby 1.8.7.

**Comment by segiddins** [comment]
👍 presuming this doesn't break backwards compatibility

**Comment by djberg96** [comment]
I don't understand why it's failing for 1.8.7 either. I'd like to see this added.

**Comment by djberg96** [comment]
I can't even get 1.8.7 to build on my Mac or on a Fedora VM to test this. The only thing I can think of is that it doesn't like the key length. Otherwise, I'm at a loss.

**Comment by sdaubert** [comment]
@djberg96 the test raises on call to `File.read` with a `Errno::ENOENT`. It seems the key size is not the problem.

But there is something weird (see [build](https://travis-ci.org/rubygems/rubygems/jobs/153608281)). Private key path id built by:
```ruby
my_dir = File.expand_path(File.dirname(__FILE__))
...
s.signing_key = File.join(my_dir, 'private_key3072.pem')
```
In the failing test, the private key is read in `/tmp/test_rubygems_2461/test/rubygems/private_key3072.pem` but the git clone is made in `rubygems/rubygems`, which not appears in private key path.
So the question is: what is the path `/tmp/test_rubygems_2461/`?

**Comment by djberg96** [comment]
Considering 1.8.7 has been end of life'd, I'd like to see this PR merged anyway, and 1.8.7 removed from the test matrix.

**Comment by segiddins** [comment]
@djberg96 we can't remove 1.8.7 from the test matrix until we're ready to release 3.0

**Comment by segiddins** [comment]
```diff
diff --git a/test/rubygems/test_gem_commands_build_command.rb b/test/rubygems/test_gem_commands_build_command.rb
index 18f68b7c..99be84fa 100644
--- a/test/rubygems/test_gem_commands_build_command.rb
+++ b/test/rubygems/test_gem_commands_build_command.rb
@@ -118,12 +118,11 @@ class TestGemCommandsBuildCommand < Gem::TestCase
   end
 
   def test_build_signed_gem
-    my_dir = File.expand_path(File.dirname(__FILE__))
-    cert_file = File.join(my_dir, 'public_cert3072.pem')
+    cert_file = File.join(@current_dir, 'test', 'rubygems', 'public_cert3072.pem')
     trust_dir = Gem::Security.trust_dir
 
     spec = util_spec 'some_gem' do |s|
-      s.signing_key = File.join(my_dir, 'private_key3072.pem')
+      s.signing_key = File.join(@current_dir, 'test', 'rubygems', 'private_key3072.pem')
       s.cert_chain = [cert_file]
     end
 
@@ -143,4 +142,3 @@ class TestGemCommandsBuildCommand < Gem::TestCase
   end
 
 end
-
```

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
