### PR TITLE
Deprecate for rubygems3

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

I've marked deprecated methods without `Gem::Deprecate#deprecate`. We're going to remove it in RubyGems 4(not 3)
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by duckinator** [comment]
This all looks good to me. :+1: 

@segiddins @indirect: are we merging 3.0 stuff now, or do we still need to wait on other things?

**Comment by indirect** [comment]
I believe the idea is that `master` is now 3.0, and we will release as soon as we have the deprecations landed, based on this plan: https://github.com/rubygems/rubygems/issues/2191 👍

**Comment by duckinator** [comment]
So it's okay for me to merge this?

**Comment by indirect** [comment]
@duckinator dooo ittttt

**Comment by duckinator** [comment]
@bundlerbot r+

**Pull request merged**
