### PR TITLE
gem cleanup is trying to uninstall gems outside GEM_HOME and reporting an error after it tries

### PR DESCRIPTION
**Pull request by bronzdoc**
This error happens when there's the same gem in any path of the GEM_PATH and one in the GEM_HOME, but the GEM_HOME one has a newer version than the one found in a path of GEM_PATH, so cleanup tries to remove the GEM_PATH one and fails.

This closes https://github.com/rubygems/rubygems/issues/1119, let me know if this is the right path for fixing this, or if i'm missing something, thanks.

@djberg96

### CODE REVIEW

**Comment by krainboltgreene** [comment]
While this is a bug fix for unexpected behavior it's [been out in the wild long enough](https://xkcd.com/1172/) that I think we need to consider this a major version bump.

**Comment by indirect** [comment]
I'm honestly not even sure what expected behavior is for `cleanup`, since `gem list` shows both new and old versions—I would expect `gem cleanup` to uninstall the old version successfully, not silently remove the new version. :/

**Comment by bronzdoc** [comment]
@indirect I could implement the expected behavior, let me know if that's the final desire state of this to keep working at it, thanks.

**Comment by drbrain** [comment]
`cleanup` is tied to `install` and `uninstall` in my mind, so I feel it should operate on `GEM_HOME` the same way install/uninstall do

**Comment by drbrain** [comment]
Can we expand on the reasoning for the major version bump?

If it's failing to do something it wasn't supposed to do anyway, then a fix of "we don't do that thing that we didn't do anyway" doesn't seem like it needs a major version change.

**Comment by indirect** [comment]
@drbrain I'm personally okay with releasing this in a minor or tiny, since it's out of sync with install and uninstall. I maintain that it's weird to see `list` show versions that can't be `cleanup`ed though. :)

**Comment by krainboltgreene** [comment]
@drbrain As I explained [above](https://github.com/rubygems/rubygems/pull/1353#issuecomment-168248267) the major version label was due to how long people have had it, and that people may be depending on it. Even if it wasn't intentional behavior, it's expected.

**Comment by drbrain** [comment]
I don't think that user expectations alone are sufficient.

I don't think "it's been broken this way for a long time" combined with "it never worked the broken way in the first place" is sufficient to make a fix for this bug cause a major bump.

If, at some point in the past, `gem cleanup` removed gems from GEM_PATH then I would agree.

**Comment by copiousfreetime** [comment]
Is this ready to be merged? folks good with that? We can close #1119 if so.

**Pull request merged**
