### PR TITLE
Speed up fuzzy requirement comparison

### PR DESCRIPTION
**Pull request by mvz**
This change adds memoization to `Version#bump` and `Version#release`, which are used by `Requirement#satisfied_by?` with the `~>` operator. Bundler in particular uses this a lot.

### CODE REVIEW

**Comment by zzak** [comment]
Pinging @tenderlove <3 <3

**Comment by tenderlove** [comment]
@mvz do you know where in bundler that is used?  I'm hesitant to add caching because if version objects can be mutated we could end up having a Bad Time™.  It doesn't look like Version these objects can be mutated, so I'll merge this, but I'd really like to push the caching up to bundler if possible.  /cc @indirect

**Comment by mvz** [comment]
Bundler users `#satisfied_by?` directly in several places, and indirectly via `Gem::Dependency#matches_spec?`.

Bundler uses it to find the installed gem versions that match a given specification, and also to check if a specification is satisfied by the currently 'active' gem version.

**Comment by indirect** [comment]
Seems like this check is used a lot by any resolver, whether in Rubygems or Bundler. @tenderlove is there something about `satisfied_by?` that is particular to Bundler rather than Rubygems? if so, I would like to move that caching into Bundler instead.

**Comment by tenderlove** [comment]
@indirect I don't think so.  I mean, if RG is using it too, we probably should have the cache in RG.  I wasn't sure if bundler was doing something special. :)

**Pull request merged**
