### PR TITLE
Remove TODO comment about warning on setting instead of pushing

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Remove TODO comment about warning on setting instead of pushing.

This methods are heavily used across specs and i personally think those warning at this point will not add much value, thoughts?
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by simi** [comment]
If only specs are related to this, I think we should think about removing/deprecating those methods.

**Comment by bronzdoc** [comment]
@simi if we deprecate/remove those methods people will have to modify their gemspecs to use `<<` instead of `=` I'm not sure that change is something we want?

**Comment by duckinator** [comment]
This looks good to me, although I initially interpreted "specs" as referring to tests instead of gemspecs, which confused me for a moment.

Realistically, I don't think these can be deprecated at this point. It'd break a ton of gemspecs in the wild.

@bronzdoc is there a reason this is marked as wip, or is it good to go?

**Comment by simi** [comment]
@duckinator I did the same mistake, sorry.

**Comment by duckinator** [comment]
@simi it's all good. :slightly_smiling_face: 

@bronzdoc since it's still marked WIP, I'm leaving this alone. If you're done with it, go ahead and merge it. :+1:

**Comment by bronzdoc** [comment]
`specs` is used across the Rubygems codebase to denote `specifications`. Sorry for the confusion!

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
