### PR TITLE
Add support for TruffleRuby

### PR DESCRIPTION
**Pull request by eregon**
# Description:

This PR adds support for TruffleRuby.
So far, the code was patched in the truffleruby repository, but this obviously does not work very well when updating RubyGems (e.g., https://github.com/oracle/truffleruby/issues/1558).

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [x] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by chrisseaton** [comment]
Looks good to me.

**Comment by eregon** [comment]
Note: Please review this PR commit-by-commit, as the commit messages explain the reasons of the changes and the diff is easier to read that way.

**Comment by eregon** [comment]
@hsbt @colby-swandale @segiddins Could one of you review this PR?

**Comment by hsbt** [comment]
@eregon Seems okay to me. Thanks.

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by eregon** [comment]
@hsbt Thank you for merging!

Will this be backported to the 3.0 branch? That would be useful :)

What's the status of RubyGems 2.x? Only security fixes?

**Comment by eregon** [comment]
@hsbt Could you backport this fix to the 3.0 branch?
That would allow to update RubyGems in TruffleRuby, and avoid custom patches.

**Comment by hsbt** [comment]
I marked this to `3.0.4`. I'm going to backport when releasing 3.0.4.

**Comment by eregon** [comment]
@hsbt Thanks!

**Pull request merged**
