### PR TITLE
Support :windows platform versions + update manpage to reflect :windows platform

### PR DESCRIPTION
**Pull request by johnnyshields**
Follow up to #5650
Split out from #5883

- Document the new :windows platform options in manpage
- Add support for per-version variants like :windows_26

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Can you remove the deprecation notice? Let's leave that for the deprecation PR.

**Comment by johnnyshields** [comment]
@deivid-rodriguez deprecation notice removed.

**Comment by johnnyshields** [comment]
@deivid-rodriguez ready to merge

**Review by simi — APPROVED** [review]

**Comment by johnnyshields** [comment]
@deivid-rodriguez ready to merge this one?

**Pull request merged**
