### PR TITLE
Change some strings on the Rakefile to single-quoted strings

### PR DESCRIPTION
**Pull request by lucasprag**
when you don't need string interpolation of special symbols.

# Description:

Cleanup the Rakefile to use single-quoted strings when you don't need string interpolation of special symbols.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests (does not apply)
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Thank you

### CODE REVIEW

**Comment by bronzdoc** [comment]
Hey @lucasprag why this change is needed?

**Comment by lucasprag** [comment]
Hi @bronzdoc
It's not that relevant, but double-quoted strings are a little bit slower than single-quoted strings.
Ultimately this comes down to style.

**Comment by hsbt** [comment]
> a little bit slower than single-quoted strings.

No, It's very very small effect. see https://www.viget.com/articles/just-use-double-quoted-ruby-strings

**Comment by lucasprag** [comment]
@hsbt ok

**Pull request closed without merging**
