### PR TITLE
[Resolver] Fix platform sorting

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Fixes https://github.com/rubygems/rubygems/issues/1541.
Fixes https://github.com/jruby/jruby/issues/3718.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
(Also manually verified that this fixes installing nokogiri on jruby)

**Comment by segiddins** [comment]
@headius this fixes the issue :)

**Comment by segiddins** [comment]
(I can release a 2.6.2 once this is merged @indirect ?)

**Comment by headius** [comment]
Excellent. Unfortunately we have a few other issues to work out before we can move to 2.6.x. Thank you for your help!

**Comment by headius** [comment]
I pushed a build of JRuby based on this branch plus a modification to our `path_separator` URL to accommodate http(s): https://travis-ci.org/jruby/jruby/builds/114982074

The HEAD commit on that branch is needed because of the issue mentioned in #1534 as described here: https://github.com/rubygems/rubygems/pull/1534#issuecomment-193326739

The changes in #1534 will solve the URL problem for us, but there's still some debate going on.

**Comment by headius** [comment]
Sorry, that build was bad...this should be better: https://travis-ci.org/jruby/jruby/builds/114985673

**Comment by segiddins** [comment]
@indirect r?

**Comment by headius** [comment]
Successful build running with @segiddins patch for platform and mine for path splitting: https://travis-ci.org/jruby/jruby/builds/114985767

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
