### PR TITLE
Remove bors

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
Bors has been a great tool but in the past few months has been giving us some problems.
https://github.com/bors-ng/bors-ng/issues/783
https://github.com/bors-ng/bors-ng/issues/806

Currently it breaks regularly and slow us down and we don't have the time to be figuring out.

After this PR is merged we need to do a couple of things:
1. Remove the bors webhook
2. Require up-to-date PRs" check on github 
3. Put bundlerbot to sleep and shutdown the heroku app 😬 

______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
I'm +1 to this.

**Comment by simi** [comment]
:+1: 

_Bye Bors :wave: , you did a great service!_

**Comment by deivid-rodriguez** [comment]
Thanks @bronzdoc!

I had prepared a PR to do the same thing. I updated your commit with the extra changes I had included. Let me know how it looks.

**Comment by bronzdoc** [comment]
@deivid-rodriguez Thanks!

**Comment by deivid-rodriguez** [comment]
@bronzdoc Feel free to merge this and inaugurate the new "use the merge button" policy if you're happy with this :smiley:

**Pull request merged**
