### PR TITLE
Test with Ruby 3.3

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

As we approach final Ruby releases, make sure everything works with Ruby 3.3.

## What is your fix for the problem, implemented in this PR?

Start testing with Ruby 3.3 early. Will update this PR once the rc is released.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

JFYI, Actions Windows Ruby builds haven't been available for Ruby master preview releases.

For Windows, see:
https://github.com/ruby/setup-ruby/blob/master/windows-versions.json

For Ubuntu & macOS, see
https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.json

**Comment by deivid-rodriguez** [comment]
Cool, thanks! I just added it everywhere without thinking too much. Will undo those changes tomorrow.

**Comment by deivid-rodriguez** [comment]
I did it now in the end :)

**Comment by deivid-rodriguez** [comment]
Green with preview3, trying rc1 now!

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/7233/commits/95711846f093f6a0d5eada4234aa8e19741c7b3f is not particularly pretty. Other alternatives:

* Always auto-install our locked version when running `bin/rake`. I find this too surprising.
* Upgrade our locked rake to 13.1.0 (what Ruby 3.3 will provide) and move on.
* Keep using 3.2.2 for the unused cassettes job for now.

**Review by martinemde — APPROVED** [review]
Looks like this is passing and ready to merge. The fix for version of rake seems fine and we revisit if it ever causes any issues.

**Comment by martinemde** [comment]
I'm merging right away now that this is passing so all other PRs will need to stay passing on 3.3. We could update to use rake 3.1.0. I think that's also a good solution. There's unlikely to be a problem using the newest rake.

**Pull request merged**
