### PR TITLE
Revert "Add Github CI action to automatically label Bundler PRs"

### PR DESCRIPTION
**Pull request by colby-swandale**
Unfortunately the labeler doesn't work on forked repositories 😞

Reverts rubygems/rubygems#3420

### CODE REVIEW

**Comment by simi** [comment]
@colby-swandale can you elaborate a little? It doesn't label pull requests on forked repositories? Wasn't purpose of this to label original (this) rubygems repo pull requests?

**Comment by colby-swandale** [comment]
The action doesn't work on PRs from forked repos

**Comment by deivid-rodriguez** [comment]
@simi I had the same question myself and found the answer at the beginning of [the actions README](https://github.com/actions/labeler).

@colby-swandale Thanks for following up on this! :+1:

@bronzdoc We need your issue-triage app again :) You added support for this labelling recently, right? Is it working?

**Comment by hsbt** [comment]
FYI https://github.com/actions/labeler/issues/12

**Comment by hsbt** [comment]
I enabled auto-labeler by @bronzdoc again. 

@bronzdoc Can you provide the code of it? I couldn't access its application on heroku. We may add the new feature related bundler/rubygems label to it.

**Comment by deivid-rodriguez** [comment]
The code is here, I think: https://github.com/rubygems/issue-triage

**Comment by bronzdoc** [comment]
> @bronzdoc We need your issue-triage app again :) You added support for this labelling recently, right? Is it working?

Yes, it's working

**Pull request merged**
