### PR TITLE
To use bundler-1.16.1

### PR DESCRIPTION
**Pull request by hsbt**
Update vendored bundler to 1.16.1.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by hsbt** [comment]
I try to resolve Ruby 1.9.2 to 2.1 failures... 🐛

**Comment by MSP-Greg** [comment]
@hsbt  I'll try what I haven't commited yet (Appveyor changes)

**Comment by MSP-Greg** [comment]
@hsbt

All is passing on Appveyor with a PR I haven't done.

Please have a look at my fork's Appveyor.  I came to the conclusion that the Travis rake file was a bit more than required for Windows testing, and I also wanted to see if Appveyor would pass using the gems included in the respective ruby builds.  No changes to Travis, so it's still testing as before.

So, test build before bundler 1.16.1 is [here](https://ci.appveyor.com/project/MSP-Greg/rubygems/build/4), test build using bundler 1.16.1 is [here](https://ci.appveyor.com/project/MSP-Greg/rubygems/build/5).

In the Appveyor file I manually moved the bundler submodule to the head of 1-16-stable.

Thanks, Greg

**Comment by hsbt** [comment]
@MSP-Greg Thanks. Can we invoke test suite on appveyor without submodule renaming?

**Comment by MSP-Greg** [comment]
@hsbt

Sorry, not quite sure what you mean by 'submodule renaming'...

The following Appveyor commands exist only because I had to switch my fork remote's submodule to 1.16.1, otherwise, there are no git commands in the appveyor.yml file.

```
cd bundler
git checkout 1-16-stable
git pull origin
git log -1
```

In my fork, I did change something in `.gitmodules`, but I don't think it was needed, and it won't be once you set the bundler submodule's new head in this repo.  Does that answer your question?

The PR I haven't done does not touch any files that will affect the Travis CI.  BTW, I'm -0600, so I'll do the PR tomorrow AM...

Thanks, Greg

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@MSP-Greg https://github.com/MSP-Greg/rubygems/commit/81717c7290d3e1ffd29a13a213a200eb2ae6cc7d modified a name of git submodule. Can you show the minimum patch of appveyor fixes?

**Comment by MSP-Greg** [comment]
@hsbt

See #2122

**Pull request merged**
