### PR TITLE
Allow failure with Ruby 2.5.0 for rubygems test.

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

It caused by travis environment.

see https://travis-ci.org/rubygems/rubygems/jobs/333599954

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@bundlerbot retry

**Comment by segiddins** [comment]
I don't think disabling this is the right approach... we really want to make sure RubyGems continues to work on the latest version of Ruby.

**Comment by hsbt** [comment]
@segiddins I agreed with you. But it's deeply Travis problem. I contacted Travis with https://github.com/travis-ci/travis-ci/issues/8974, And I heard that it was an issue of https://github.com/travis-ci/travis-rubies or RVM maybe from @BanzaiMan. 

We continue to resolve its problem. Maybe, RG 2.7.5 with Bundler 1.16.1 resolve its problem. I try to it at this weekend.

**Pull request merged**
