### PR TITLE
Fix flaky

### LINKED ISSUE #2717: Order dependent test failure
My current problem is that I have found an order dependent test failure. It is reproducible with

    rake TESTOPTS="--name=/TestGemCommandsSourcesCommand#test_initialize_proxy\|test_no_proxy/ --seed=5961"

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

Fixes #2717 by undoing the side effects of the test that was causing the failure.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@deivid-rodriguez i'm still getting the error with this patch:
```
  1) Error:
TestGemRemoteFetcher#test_no_proxy:
Gem::RemoteFetcher::UnknownHostError: no such name (http://localhost:61173/yaml)
    /Users/bronzdoc/projects/ruby/rubygems/lib/rubygems/remote_fetcher.rb:280:in `rescue in fetch_path'
    /Users/bronzdoc/projects/ruby/rubygems/lib/rubygems/remote_fetcher.rb:253:in `fetch_path'
    /Users/bronzdoc/projects/ruby/rubygems/test/rubygems/test_gem_remote_fetcher.rb:185:in `block in test_no_proxy'
    /Users/bronzdoc/projects/ruby/rubygems/lib/rubygems/user_interaction.rb:47:in `use_ui'
    /Users/bronzdoc/projects/ruby/rubygems/lib/rubygems/user_interaction.rb:70:in `use_ui'
    /Users/bronzdoc/projects/ruby/rubygems/test/rubygems/test_gem_remote_fetcher.rb:184:in `test_no_proxy'
```

**Comment by deivid-rodriguez** [comment]
That's weird, it fixes it for me... :grimacing:

```
(master) deivid@pantani ~/Code/rubygems $ rake TESTOPTS="--name=/TestGemCommandsSourcesCommand#test_initialize_proxy\|test_no_proxy/ --seed=5961"
Run options: "--name=/TestGemCommandsSourcesCommand#test_initialize_proxy|test_no_proxy/" --seed=5961

# Running:

.E

Finished in 0.084610s, 23.6378 runs/s, 11.8189 assertions/s.

  1) Error:
TestGemRemoteFetcher#test_no_proxy:
Gem::RemoteFetcher::UnknownHostError: no such name (http://localhost:41525/yaml)
    /home/deivid/Code/rubygems/lib/rubygems/remote_fetcher.rb:280:in `rescue in fetch_path'
    /home/deivid/Code/rubygems/lib/rubygems/remote_fetcher.rb:253:in `fetch_path'
    /home/deivid/Code/rubygems/test/rubygems/test_gem_remote_fetcher.rb:184:in `block in test_no_proxy'
    /home/deivid/Code/rubygems/lib/rubygems/user_interaction.rb:47:in `use_ui'
    /home/deivid/Code/rubygems/lib/rubygems/user_interaction.rb:70:in `use_ui'
    /home/deivid/Code/rubygems/test/rubygems/test_gem_remote_fetcher.rb:183:in `test_no_proxy'

2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
Coverage report generated for Unit Tests to /home/deivid/Code/rubygems/coverage. 2704 / 8751 LOC (30.9%) covered.
rake aborted!
Command failed with status (1)

Tasks: TOP => default => test
(See full trace by running task with --trace)

(master) deivid@pantani ~/Code/rubygems $ git checkout fix_flaky 
Switched to branch 'fix_flaky'

(fix_flaky) deivid@pantani ~/Code/rubygems $ rake TESTOPTS="--name=/TestGemCommandsSourcesCommand#test_initialize_proxy\|test_no_proxy/ --seed=5961"
Run options: "--name=/TestGemCommandsSourcesCommand#test_initialize_proxy|test_no_proxy/" --seed=5961

# Running:

..

Finished in 0.094397s, 21.1872 runs/s, 42.3743 assertions/s.

2 runs, 4 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/deivid/Code/rubygems/coverage. 2680 / 8751 LOC (30.63%) covered.
(fix_flaky) deivid@pantani ~/Code/rubygems $
```

**Comment by deivid-rodriguez** [comment]
@bronzdoc Maybe you have something interfering in your `~/.gemrc`? :thinking:

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
I just tested this again and it worked thanks @deivid-rodriguez!, maybe i was doing something wrong yesterday 🤔

**Pull request merged**
