### PR TITLE
Write test for GH-6444

### PR DESCRIPTION
**Pull request by hsbt**
## What was the end-user or developer problem that led to this PR?

https://github.com/rubygems/rubygems/pull/6444 has no test because my laziness.

## What is your fix for the problem, implemented in this PR?

Write a test-case for simple scenario. I'm working this issue with `rake-compiler` until next stable version of RubyGems.

## Make sure the following tasks are checked

- [ ] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [ ] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Test looks good @hsbt.

I think I understand the problem better now. 

Something I don't like is that in #6444 we are adding logic that will run for every single `require` call, just to fix a very small warning edge case (running `bundle exec` in the context of developing a gem with extensions).

I think it'd be better to:

* Fix `Bundler::Source::Path` to return a correct `Specification#extension_dir` so that we don't need to loop through all `full_require_paths` and can look at `Specification#extension_dir` directly.
* Once the above is fixed, change `rake-compiler` to drop a sentinel `gem_build.complete` file at `Specification#extension_dir` and thus be compatible with the current mechanism.

**Comment by hsbt** [comment]
@deivid-rodriguez Are you say about https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/source/path.rb#L171 ?

**Comment by deivid-rodriguez** [comment]
I mean something similar to what we do to "fix" `Specification#full_gem_path` for `Bundler::Source::Path` sources:

https://github.com/rubygems/rubygems/blob/6a62e461cd648285c10c4c9b3b07fcfb2708f9ad/bundler/lib/bundler/rubygems_ext.rb#L47-L53

**Comment by hsbt** [comment]
I see. It's reasonable for me too. I'll move #6444 to bundler side.

Just I merge this test until I finish to move your suggestion.

**Pull request merged**
