### PR TITLE
Fix resolver edge cases and speed up bundler

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

It all started with https://github.com/rubygems/rubygems/issues/4275. Recent versions of bundler have caused a heavy `bundle install` performance regression, even in cases when there's a lockfile and all gems are already installed :grimacing:.

## What is your fix for the problem, implemented in this PR?

After an initial investigation of the problem, I noticed that reverting https://github.com/rubygems/bundler/pull/6495 fixed the issue. That gave me the idea that this PR fixed a resolution problem, but at an incorrect place (note how the platform filtering happens on top of the resolve (independently of whether resolution actually happened, or it was read from the lockfile).

So, the challenge was to fix that same problem inside the resolver, so that no overhead is needed in any case. The result of doing this (other than fixing this regression) is speeding up all `bundler/setup` requires. In the case of a generated default Rails application, the speed up is ~5-10% of boot time.

My first solution worked, but created an overhead on most resolutions, that would be a bit slower. The reason is that spec groups need to be modified dynamically depending on the currently activated platforms, so that whole `search_for` result for each dependency can no longer be fully memoized.

So I did a series on refactorings on the resolution process to not hurt performance. To measure results, I compiled a series of Gemfiles that have proven to be problematic in the past, and run the resolver before an after this PR. The results on my machine are as follows:

#### Before this PR

```
+-------------------------------+---------+---------------------+
|  Gemfile                      |  Steps  |  Seconds            |
+-------------------------------+---------+---------------------+
|  depfu                        |  242    |  0.985466332        |
|  solidus_shipwire             |  148    |  1.175150116        |
|  active_model_as_json_filter  |  948    |  1.262431201        |
|  simply_bussines              |  2061   |  1.623000041        |
|  tricky_groups                |  889    |  3.18565573         |
|  network_executive            |  2179   |  3.354704401        |
|  nix                          |  1087   |  4.492709607        |
|  fury-bug                     |  2471   |  4.693998945        |
|  doorkeeper-couchbase         |  8880   |  4.740346119        |
|  big                          |  1005   |  5.792436901        |
|  spree_pag_seguro             |  2192   |  8.232739329        |
|  refinerycms-photo-gallery    |  4814   |  9.35598295         |
|  activeadmin-redactor         |  4191   |  19.830266492       |
|  staple                       |  7330   |  22.273399876       |
|  mongoid_session_store_json   |  14497  |  29.598622289       |
+-------------------------------+---------+---------------------+
|  MEAN                         |  3528   |  8.039794021933334  |
+-------------------------------+---------+---------------------+
```

#### After this PR

```
+-------------------------------+---------+---------------------+
|  Gemfile                      |  Steps  |  Seconds            |
+-------------------------------+---------+---------------------+
|  depfu                        |  242    |  1.063837602        |
|  solidus_shipwire             |  148    |  1.187392968        |
|  active_model_as_json_filter  |  948    |  1.246154535        |
|  simply_bussines              |  2061   |  1.684438742        |
|  tricky_groups                |  889    |  2.785258354        |
|  doorkeeper-couchbase         |  8880   |  3.874559521        |
|  network_executive            |  2179   |  4.095082296        |
|  nix                          |  1087   |  4.098752359        |
|  big                          |  1005   |  4.958331229        |
|  fury-bug                     |  2471   |  5.048921037        |
|  spree_pag_seguro             |  2192   |  7.822267305        |
|  refinerycms-photo-gallery    |  4814   |  9.147989796        |
|  activeadmin-redactor         |  4191   |  9.24378089         |
|  staple                       |  7330   |  20.014836546       |
|  mongoid_session_store_json   |  14497  |  27.500409567       |
+-------------------------------+---------+---------------------+
|  MEAN                         |  3528   |  6.918134183133334  |
+-------------------------------+---------+---------------------+
 ```

Fixes https://github.com/rubygems/rubygems/issues/4275.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by bquorning** [comment]
> I haven't yet figured out the regression

In relation to my simple benchmarks posted at https://github.com/rubygems/rubygems/issues/4275#issuecomment-767511273: The commit that brings the performance benefit (in my `bundle check` case) was actually e76a68979881c3ae96cc878b21ebf46ff2f8faa1, not 9c12e5f8c4da1089ecdf4b9ea8bbce9385c053c9. Not sure if this is useful feedback, but there it is 😄

**Comment by deivid-rodriguez** [comment]
Thanks @bquorning!

I'll be going with the approach in 9c12e5f, because it provides noticiable performance benefits for all `bundler/setup` requires, not just for this particular regression.

I have it almost ready locally, hope to be finished during the day.

**Comment by deivid-rodriguez** [comment]
@haines @bquorning This should be now ready, in case you want to try it! Sorry for the delay.

**Review by indirect — APPROVED** [review]
wow, nice work! this is very impressive 😁

**Comment by bquorning** [comment]
Thank you @deivid-rodriguez 👍🏼 Here are my performance numbers from a project with ~250 gems.

Using tag `bundler-v2.2.7` / 7bc7ecb660c907180cf569b55654c8163c72375e:

```
bundle exec ruby -e ""  6.79s user 0.14s system 99% cpu 6.939 total
bundle check > /dev/null  6.71s user 0.11s system 99% cpu 6.829 total
```

Using branch `origin/refactor_platform_spec_groups` / 473babb3a1430853169a0029c71d4eef8cb76ad6:

```
bundle exec ruby -e ""  0.58s user 0.12s system 99% cpu 0.702 total
bundle check > /dev/null  0.48s user 0.09s system 99% cpu 0.569 total
```

**Comment by haines** [comment]
Yep, it's a big improvement over 2.2.7 for us, although not quite back to 2.1.4:

| Bundler version | Install time |
|---|---|
| 2.1.4 | 0.83s |
| 2.2.7 | 36.36s |
| 473babb | 1.67s |

**Comment by deivid-rodriguez** [comment]
Thanks for reporting @haines! I think you're still getting the same performance regression, it's just that the slow code path is now triggered many many less times with this refactoring. Even if more minor after this PR, I'll try to look into your case :+1:.

**Comment by haines** [comment]
Thanks @deivid-rodriguez, we're back to usable though, so definitely happy with that! I really appreciate the work you've put into this 👏

**Review by simi — APPROVED** [review]

**Pull request merged**
