### PR TITLE
Improve deprecations

### LINKED ISSUE #3008: `gem list` and `gem info` are being unintentionally deprecated
I'm having a problem or would like to suggest a feature.

My current problem is that running `gem list` or `gem info` against current rubygems master at 99bca8e80c7d7136d62623913b794d313e3bceaf, I get

```
NOTE: info command is deprecated. It will be removed on or after 2019-12-01
```

(or the same with `list`).

These two commands inherit from the `query` command, which will be _intentionally_ deprecated.

It sounds like a bug in #2974.

/cc @bronzdoc

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

#2967 deprecated `gem query` but it also deprecated `gem list`, `gem search`, and `gem info`, because they inherit from `gem query`.

This PR undeprecates these commands by no longer inheriting from `QueryCommand`.

It also adds tests to ensure that `gem query` is deprecated, but `gem list`, `gem search`, and `gem info` are not.

Fixes #3008.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
Something's wrong against ruby-master, I'll investigate.

**Comment by deivid-rodriguez** [comment]
It's now ready @bronzdoc

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
