### PR TITLE
Fix windows specific executables generated by `gem install`

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

This is a rework of #2615. While reviewing that PR I took care of splitting each change into its own commit, and added some comments in the commit messages to explain why I think the change is useful / needed / correct.

First commits are just simplifications and refactorings; the last commit, 961b514, is a bug fix.

Stuff I didn't include from #2615 are stylistic changes, inconsistent stuff, and DRY ups that I consider that harm readability instead of adding to it (for example, moving the umask stuff inside the already complicated method `assert_self_install_permissions`).

I didn't push directly to #2615 because I don't have permissions, but I did keep @MSP-Greg's authorship.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
@deivid-rodriguez thanks for taking the time to explain in detail in each commit

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
@deivid-rodriguez I removed to mark a milestone for 3.0.x. I'm afraid to merge this with tiny version release Because this change affects many of users.

**Comment by deivid-rodriguez** [comment]
Ok! As far as I know nobody has requested this fix to be backported, so :+1:.

**Pull request merged**
