### PR TITLE
[Request] Handle Net::HTTPFatalError

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bundler/bundler/issues/3830

### CODE REVIEW

**Comment by segiddins** [comment]
\c @indirect  ?

**Comment by indirect** [comment]
Yeah, it seem bad for the RubyGems request to throw a raw Net::HTTP error. We'll still need to catch the raw error in Bundler for every version of RubyGems before 2.5, though. Also, can you add a test for this? :pray: :raised_hands:

**Comment by bf4** [comment]
Any thoughts about handling all of the following somewhere?

```ruby
 Errno::EINVAL, Errno::ECONNRESET, Errno::ETIMEDOUT,
         Net::HTTPBadResponse, Net::HTTPHeaderSyntaxError, Net::ProtocolError,
          Net::HTTPMethodNotAllowed,  SocketError, Errno::ENETDOWN, URI::InvalidURIError
```

or see [Faraday](https://github.com/lostisland/faraday/blob/c69813cfae43b06c4ebb47d5d23dbbb1a071f43b/lib/faraday/adapter/net_http.rb#L12-L28)

**Comment by segiddins** [comment]
Iirc most of those are handled on the next line, but fatal error wasn't being rescued at all.

**Comment by segiddins** [comment]
@indirect there aren't any tests for those error conditions, so I'm unsure where the best place to add them would be

**Comment by segiddins** [comment]
Ping @indirect ?

**Pull request merged**
