### PR TITLE
Added option to search command to output in JSON

### PR DESCRIPTION
**Pull request by anuccio1**
# Description:
I added an option to query_command to output results as JSON.

Why?

I am spawning a child process in my code, and needed the output from `gem search` to stdout to be JSON parsable.

______________

# Tasks:

- [x ] Describe the problem / feature
- [ x] Write tests
- [ x] Write code to solve the problem
- [x ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by drbrain** [comment]
Why not use the API directly?

**Comment by anuccio1** [comment]
@drbrain I'm calling this from a node js code base... wrote this little hack, wanted to share it

**Comment by djberg96** [comment]
I seem to recall that zenspider wanted json output as an option for all commands. The ones that send stuff to stdout, anyway. Should we revisit a universal option?

**Comment by segiddins** [comment]
I'm not a huge fan of the number of conditionals we needed to touch in this

**Comment by drbrain** [comment]
The query command implementation has always been messy due to the number of things it supports.

I don't think adding one more thing to RubyGens for a one-off use case for one person is best for our future maintenance.

Since you're already shelling out you can use the API from a one-liner or a ruby script if one line is too cumbersome.

**Comment by anuccio1** [comment]
@djberg96 Would be open to helping out with that if you guys decide to move forward with this! I think having the output of the CLI in a JSON format could definitely be beneficial to some people

**Comment by drbrain** [comment]
Absent a broader plan I'm going to close this feature request.

If you need help using the RubyGems API to get the data you need from a ruby one-liner or small script we can help, though.  Here is a getting-started one-liner:

```
$ ruby -rjson -e 'puts JSON.pretty_generate Gem::SpecFetcher.fetcher.detect(:latest) { |nt| nt.name == "rake" }.map { |nt, source| source.fetch_spec nt }.map { |spec| { name: spec.name, version: spec.version, platform: spec.platform, summary: spec.summary } }'
[
  {
    "name": "rake",
    "version": "12.0.0",
    "platform": "ruby",
    "summary": "Rake is a Make-like program implemented in Ruby"
  }
]
```

**Pull request closed without merging**
