### PR TITLE
expand tests

### PR DESCRIPTION
**Pull request by soda92**
## Make sure the following tasks are checked

- [ ] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [ ] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by soda92** [comment]
https://github.com/rubygems/rubygems/issues/8249

**Comment by hsbt** [comment]
Don't do that. `let` is the basic technic of RSpec.

**Comment by soda92** [comment]
That was good to hear.

@hsbt please take other's issues and contributions seriously. A simple close was not a good reaction.

It also possibly violates the Code of Conduct.

See also https://github.com/rubygems/rubygems/issues/8237.

**Comment by simi** [comment]
> That was good to hear.
> 
> @hsbt please take others' issues and contributions seriously. A simple close was not a good reaction.
> 
> It also possibly violates the Code of Conduct.
> 
> See also #8237.

It doesn't violate anything in CoC and it is your responsibility to explain on your changes. Submitting pull request with empty PR template and no explanation is not the way forward here.

**Comment by deivid-rodriguez** [comment]
@soda92 Your PRs being closed does not mean they don't have merit or that they should not be discussed further. @hsbt closed your PR in good faith because he believes we should not be merging it. A maintainer closing a PR because he thinks it's not appropriate to merge it does not violate the code of conduct in any way.

**Comment by deivid-rodriguez** [comment]
Also stepping into a project with statements like "Since when did ruby become such a clumsy language?" or "Also, there are too many links on README.md that I don't want to click any." that I see you leaving in other places are not examples in my opinion of "Giving constructive feedback", which is explicitly mentioned in the CoC as something we appreciate. And wrongly accusing a maintainer of not following the CoC is not appropriate either.

We do appreciate your contributions, but please be respectful.

**Pull request closed without merging**
