### PR TITLE
Add Rubocop

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

This PR introduces Rubocop to help with fixing outdated styles being used in the project and help developers stick to a style that can be tested against.

Initially, Rubocop is only checking `lib/rubygems.rb` but i plan to work on adding more files for Rubocop to check and eventually have Rubocop covering the rest of the repository.

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
I'm only okay to add rubocop rule with `DisabledByDefault: true`. We should add cop rule step by step.

**Comment by segiddins** [comment]
What if we just ran `—auto-gen-config` ?

**Comment by colby-swandale** [comment]
@segiddins i looked into doing that first but there is an internal limit on the number of rules it can skip which the rubygems repo is easily exceeding.

**Comment by tiagoefmoraes** [comment]
@colby-swandale you can run `rubocop --auto-gen-config --exclude-limit 0` and it will remove the limit.

It may be a good idea to `Exclude` the bundler submodule before doing this.

Also bundler has some configurations worth considering.

I used this [post](https://joanswork.com/rails-rubocop-update/) as a reference on a project recently.

**Comment by colby-swandale** [comment]
I'm going to disable all cops by default and then make separate PRs that will enable/fix rubocop rules.

**Comment by duckinator** [comment]
@colby-swandale do you have anything else you need to do on this PR?

your idea of gradually adding rubocop rules sounds good to me, and this PR looks okay assuming you're done with it.

**Comment by colby-swandale** [comment]
@duckinator Yep, this is ready to merge.

**Pull request merged**
