### PR TITLE
Notify ruby-head build in slack

### PR DESCRIPTION
**Pull request by bronzdoc**
https://github.com/rubygems/rubygems/issues/3557

-----
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
My idea here would be to save the status of the previous head build to an artifact, and use that to only send notifications when the status has changed.

The rationale is that we don't want to get overwhelmed with useless notifications. We only want to know when the build gets broken, and if someone fixes it, when it starts being green again. Once it's broken we don't need daily notifications to remind us the same thing, and once it's green we don't need daily notifications to remind us that it's green.

Completely untested, but the gist would be something like:

```yaml
- uses: actions/download-artifact@v2
  with:
    name: status
    path: previous_status.txt

- name: Save fail status
  if: failure()
  run: echo "FAIL" > status.txt

- name: Save pass status
  if: success()
  run: echo "PASS" > status.txt

- name: Compare with previous run
  run: echo "::set-env name=STATUS_CHANGED::$(diff status.txt previous_status.txt; echo $?)"

- uses: 8398a7/action-slack@v3
  with:
    status: ${{ job.status }}
    fields: repo,message,commit,author,action,eventName,ref,workflow
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    if: env.STATUS_CHANGED != '0'

- uses: actions/upload-artifact@v2
  with:
    name: status
    path: status.txt
```

**Comment by deivid-rodriguez** [comment]
This is awesome. We should add the same kind of thing to `daily-bundler.yml` as well.

**Comment by bronzdoc** [comment]
@deivid-rodriguez 👀

**Comment by bronzdoc** [comment]
@deivid-rodriguez yeah, I was going to ask that. Let's merge it then :shipit:

**Comment by deivid-rodriguez** [comment]
Actually, I just realized that unless there's a way to manually upload an artifact, we're going to need to do this in two steps.

First change the workflow to only upload the artifact with the build status, and then add the rest of the stuff. Because otherwise the initial artifact download is going to fail because there will be no such artifact, right?

**Comment by deivid-rodriguez** [comment]
Ok, so there should be a "fun" but easy fix:

* Push a branch named "foo" that modifies the relevant workflows to run on `push` events on branch "foo", and remove the all the changes you added here except for the final "upload_artifact" part.

That should result in the current status properly uploaded as an artifact and should make the future scheduled run work I believe.

**Pull request merged**
