### PR TITLE
Show RSpec filter annoucements when running plain rspec

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I think never showing them was unintentional.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by simi** [comment]
:information_source: seems it was introduced by @hsbt at https://github.com/rubygems/bundler/commit/faccc522d11f633ba402082ccc220fa0fd89b78f

**Comment by deivid-rodriguez** [comment]
Indeed.

The explicit introduction of `require 'support/parallel.rb'` inside `.rspec_parallel` inside that commit seems to confirm that it was unintentional. At that point in time we had the following code inside `spec/spec_helper.rb`, which made the helper file also be picked up by regular RSpec runs:

https://github.com/rubygems/bundler/blob/faccc522d11f633ba402082ccc220fa0fd89b78f/spec/spec_helper.rb#L18-L22

```ruby
Dir["#{File.expand_path("../support", __FILE__)}/*.rb"].each do |file|
  file = file.gsub(%r{\A#{Regexp.escape File.expand_path("..", __FILE__)}/}, "")
  require file unless file.end_with?("hax.rb")
end
```

**Comment by hsbt** [comment]
I forgot why I enabled this configuration. Maybe, I faced the some of issues of parallel tests.

**Comment by deivid-rodriguez** [comment]
Yes, it makes sense for parallel tests because the filter announcements get printed one time per thread making them pretty annoying. But for regular RSpec they are ok.

**Pull request merged**
