### PR TITLE
[OLD] Rubygems does not terminate on failed file lock when not superuser

### PR DESCRIPTION
**Pull request by sploadie**
Closes https://github.com/rubygems/rubygems/issues/1535

### CODE REVIEW

**Comment by segiddins** [comment]
Could you please add test coverage for this?

**Comment by segiddins** [comment]
This fails on 1.8.7: https://travis-ci.org/rubygems/rubygems/jobs/114318329#L443

**Comment by sploadie** [comment]
Will do. I am unaware of the correct manner in which to 'initialize' the error constant `Errno::ENOTSUP`, however.

**Comment by segiddins** [comment]
You could put it in a local variable of its defined and rescue that?

**Comment by sploadie** [comment]
`ENOTSUP` is a constant of the `Errno` module. Is it correct to assign it's elsewhere simply to call it?

**Comment by indirect** [comment]
The pattern of adding errors to an array if they exist and then splitting the array is already in use in fetcher.rb. Please do that.

**Comment by indirect** [comment]
Whoops, thought I was looking at a Bundler ticket. :) If you look in Bundler at `lib/bundler/fetcher.rb` you can find an example there!

**Comment by duckinator** [comment]
@indirect unless I'm misunderstanding what you mean, I don't see an example in https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb

You mean something like this, right?:

```ruby
enotsup = Errno::ENOTSUP if Errno.const_defined?(:ENOTSUP)

begin
  # ...
rescue Errno::EACCES, enotsup
  # ...
end
```

**Comment by indirect** [comment]
@duckinator it's on [FAIL_ERRORS](https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L63-L67)

**Comment by duckinator** [comment]
ah, gotcha. not used in an actual `rescue`, but the same general idea. (https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L63-L67 , for everyone else.)

**Comment by indirect** [comment]
`FAIL_ERRORS` is used in an internal rescue supplied by `Bundler::Retry`, [over here](https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L108). The idea is that if it's an array of errors, they get used like this: `rescue *error_array`

**Comment by duckinator** [comment]
So something like this, then?:

```ruby
READ_BINARY_ERRORS = begin
  read_binary_errors = [Errno::EACCES]
  read_binary_errors << Errno::ENOTSUP if Errno.const_defined?(:ENOTSUP)
end.freeze

def self.read_binary(path)
  # ...
rescue *read_binary_errors
  # ...
end
```

**Comment by segiddins** [comment]
@sploadie if you could make the change Ellen suggested, this would be ready to merge. Thanks!

**Comment by sploadie** [comment]
Sorry for my response time; in which file should I initialize `read_binary_errors`?
I would be using it in both `lib/rubygems.rb` and `lib/rubygems/remote_fetcher.rb`, so should I just initialize it in `lib/rubygems.rb`?

**Comment by segiddins** [comment]
> so should I just initialize it in lib/rubygems.rb?

yup! while you're at it, you might just want to move the writing to `Gem.write_binary` ?

**Comment by sploadie** [comment]
> move the writing to `Gem.write_binary` ?

I admit you lost me there. `self.read_binary` aka `Gem.read_binary` exists, but not `write_binary`.

**Comment by segiddins** [comment]
right, I'm saying we might want to move the binary writing that's currently in remote_fetcher.rb

**Comment by duckinator** [comment]
Since this has been idle for nearly two weeks, and we've already figured out what changes need to be made, I'm going to go ahead make a new PR containing @sploadie's commit as well as making the changes @indirect and @segiddins suggested. @sploadie will still be marked as the author of their commits. I'll close this PR once the other one is ready.

Thanks for getting it started, @sploadie!

**Comment by duckinator** [comment]
Closing in favor of #1582.

**Pull request closed without merging**
