### PR TITLE
Prefer `__dir__` to `__FILE__`

### LINKED ISSUE #5411: The test/rubygems/test_gem_ext_cargo_builder trigger the errors when cargo is not installed
I'm having a problem.

My current problem is the `test/rubygems/test_gem_ext_cargo_builder.rb` finishes with error when the `cargo` command is not installed. I think the pending is ok, but the error is problem.

```
$ git clean -fdx

$ rake setup

$ rake test
...
some errors and pendings for cargo.
...

$ ruby -Ilib:test:bundler/lib test/rubygems/test_gem_ext_cargo_builder.rb -n /test_build_staticlib/
Loaded suite test/rubygems/test_gem_ext_cargo_builder
Started
P 
===============================================================================================================================
Pending: test_build_staticlib(TestGemExtCargoBuilder): cargo not present
test/rubygems/test_gem_ext_cargo_builder.rb:15:in `setup'
===============================================================================================================================
E
===============================================================================================================================
Error: test_build_staticlib(TestGemExtCargoBuilder): TypeError: no implicit conversion of nil into String
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:460:in `chdir'
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:460:in `teardown'
===============================================================================================================================

Finished in 0.013538263 seconds.
-------------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 0 failures, 1 errors, 1 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------------------------------------------------------
73.86 tests/s, 0.00 assertions/s
```

This error doesn't happen when the `cargo` is installed and running the following commands.

```
$ git clean -fdx
$ rake setup
$ rake test
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

Fedora, Ruby 3.1.1, the latest upstream fe96fb6e2ac5a8b6df5e852470d11fa854301eca .

```
$ ruby -Ilib bin/gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.0.dev
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /home/jaruga/.gem/ruby/3.1.0
  - RUBYGEMS PREFIX: /home/jaruga/var/git/rubygems
  - RUBY EXECUTABLE: /home/jaruga/local/ruby-3.1.1-test-rubygems/bin/ruby
  - GIT EXECUTABLE: /bin/git
  - EXECUTABLE DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/bin
  - SPEC CACHE DIRECTORY: /home/jaruga/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/jaruga/local/ruby-3.1.1-test-rubygems/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/jaruga/local/ruby-3.1.1-test-rubygems/lib/ruby/gems/3.1.0
     - /home/jaruga/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/jaruga/.go/bin
     - /home/root/local/mongodb-4.2/bin
     - /home/root/local/samtools-1.9/bin
     - /home/root/local/bowtie2-dev-580a859/bin
     - /home/root/local/kallisto-dev/bin
     - /home/jaruga/git/gem2rpm/bin
     - /home/jaruga/git/rpmlint/dist/usr/bin
     - /usr/local/valgrind-3.11.0/bin
     - /usr/local/docker-compose-1.8.0/bin
     - /home/jaruga/.local/bin/
     - /home/jaruga/.gem/ruby/3.1.0/bin
     - /home/jaruga/local/ruby-3.1.1-test-rubygems/bin
     - /bin
     - /usr/bin
     - /usr/sbin
     - /usr/local/bin
     - /usr/local/sbin
     - /home/jaruga/bin
     - /var/lib/snapd/snap/bin
     - /home/root/local/miniconda3-py38-4.8.3/bin
     - /usr/local/mongodb-linux-x86_64-rhel80-4.4.1/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

OS packagers are having trouble when running some recently added tests in isolation. Turns out the problem is `__FILE__` not being expanded by default.

## What is your fix for the problem, implemented in this PR?

Prefer `__dir__` whenever possible.

This PR also fixes other small issues to make sure all RubyGems test files can be run in isolation.

Closes #5437.
Fixes #5411.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by hsbt** [comment]
👍

**Comment by simi** [comment]
Big thanks to @junaruga as well for finding the root cause and preparing initial fix. :muscle:

**Comment by deivid-rodriguez** [comment]
Sorry I pushed a couple of extra tweaks after approval, it should be good to go now assuming CI is fine.

**Comment by junaruga** [comment]
Thanks for fixing it! I have been a little sick latest days.

**Comment by deivid-rodriguez** [comment]
No problem, as @simi said, thanks to you for your work and investigation.

**Pull request merged**
