### PR TITLE
Fix Gem::Version.correct?

### PR DESCRIPTION
**Pull request by m-nakamura145**
# Description:

in ruby 2.5.0. 
```
irb(main):001:0> Gem::Version.correct?(nil)
=> true
```

I think that it was wrong.  I think that I should behave as follows.
```
irb(main):001:0> Gem::Version.correct?(nil)
=> false
```
______________

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
Looks reasonable. Thanks!

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by m-nakamura145** [comment]
Thanks!! 👍

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/issues/7765 This change has caused issues for several CocoaPods users

**Pull request merged**
