### PR TITLE
Vendor Bundler 2.1.0 take 2

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

https://github.com/rubygems/rubygems/pull/3028 did point the wrong commit that is https://github.com/bundler/bundler/commit/4045ba4bb1b19c8c43178daae1918f38d11c6af6 . Bundler 2.1.0 was released at https://github.com/bundler/bundler/commit/683fe9799e37bff81e53f1a7e97d3a19896b8fc9

I update commit of submodule.
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot merge

**Comment by magni-** [comment]
@hsbt could this get released as 3.1.1? 🙇

**Comment by hsbt** [comment]
@magni- Yes, I'm working it now.

**Comment by hsbt** [comment]
Released https://blog.rubygems.org/2019/12/16/3.1.1-released.html

**Comment by deivid-rodriguez** [comment]
Thanks so much @hsbt, and sorry for the mistake.

**Comment by hsbt** [comment]
No problem! I appreciate your hard work.

**Pull request merged**
