### PR TITLE
Support for The Update Framework (TUF)

### PR DESCRIPTION
**Pull request by tarcieri**
This PR contains an implementation of a client for [The Update Framework (TUF)](https://updateframework.com/projects/project) which provides a complementary/supplemental security system for the existing metadata used by RubyGems.

We've documented our plans here:

https://docs.google.com/document/d/1o68vVLAgqyK--u0sfJx8ORlDSjc3oyMtD8dj7kNuOa0/

Similar work is being done in Python to integrate TUF with PyPI:

https://github.com/theupdateframework/pep-on-pypi-with-tuf

TUF provides a security model for software update systems which uses a "least authority" approach with multiple roles with limited power and a combination of online and offline keys:

TUF Trust Model

We (by which I mean @xaviershay ;) have also implemented server support for RubyGems.org which we'll be submitting in a separate PR.

There are a number of roles in TUF and the existing work doesn't implement all of them. Here's a checklist of what's been accomplished and what's needed:
- [x] Gem::TUF::PublicKey
- [ ] Gem::TUF::PrivateKey/KeyStore?
- [x] Gem::TUF::Signer/Verifier
- [x] Gem::TUF::Root
- [ ] Gem::TUF::Targets
- [ ] Gem::TUF::Targets::Claimed (offline delegation to offline developer keys)
- [ ] Gem::TUF::Targets::RecentlyClaimed (online delegation to offline developer keys)
- [ ] Gem::TUF::Targets::Unclaimed (grandfather in old gems)
- [ ] Gem::TUF::Releases
- [ ] Gem::TUF::Timestamp
- [ ] Gem::RemoteFetcher support for TUF
- [ ] Ruby 1.8 support for JSON
- [ ] Move CanonicalJSON to the Gem::TUF namespace

### CODE REVIEW

**Comment by copiousfreetime** [comment]
Is TUF still on the roadmap? @drbrain @indirect

**Comment by indirect** [comment]
Yes, it's on the list after we launch the new index and get RubyGems a bit more maintained.

**Comment by bbraga** [comment]
With the recent disclosure of [multiple vulnerabilities in RubyGems](https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/) shouldn't this be more of a focus now?
paging @drbrain @indirect @lynncyrin

**Comment by segiddins** [comment]
If someone would like to dedicate the time to its development, both on the client and server side, we'd be happy to see that, but as André posted above, the RubyGems team does not have the bandwidth to tackle a project this large at the moment.

**Comment by duckinator** [comment]
This PR is over 4 years old and still has unresolved problems, so I'm going to close it.

**Me closing this PR is not a rejection of the idea. It is simply being done for the sake of cleaning up inactive pull requests.**

If you would like this functionality, please open an issue about it!

**Comment by djberg96** [comment]
After what happened with rest-client, it might be time to revisit this.

**Pull request closed without merging**
