### PR TITLE
Update Molinillo 0.6.6 same as bundler-1.16.4

### PR DESCRIPTION
**Pull request by hsbt**
I hope to use the same version of Molinillo on rubygems and bundler on ruby core. In my plan, Ruby 2.5.0 is going to bundle rubygems 2.7.x and bundler 1.16.x.

### CODE REVIEW

**Comment by segiddins** [comment]
RubyGems doesn’t work with Molinillo 0.6.x because it implements equality for dependencies/specifications (I forget which) weirdly, and it didn’t hurt it to stay on 0.5

**Comment by hsbt** [comment]
I see. I want to resolve duplicated vendor files for my motivation.

**Comment by segiddins** [comment]
They’re namespaced differently anyways, so I’m not sure how you could de-duplicate them

**Comment by hsbt** [comment]
I can dedupe on ruby core repository when their molinillo is same versions.

https://github.com/ruby/ruby/pull/1712/files

**Comment by segiddins** [comment]
That won’t work if the user updates RubyGems to a version that uses a different version of Molinillo

**Comment by hsbt** [comment]
It's known issue for me too.

**Comment by simi** [comment]
@segiddins can you explain more on this problem? I can try to fix this if welcomed.

**Comment by deivid-rodriguez** [comment]
Closing in favor of #3388!

**Pull request closed without merging**
