### PR TITLE
Add the most recent licenses from spdx.org

### PR DESCRIPTION
**Pull request by nobu**
The lists in `lib/rubygems/util/licenses.rb` seem outdated.

## What was the end-user or developer problem that led to this PR?

Cannot select licenses which are recently added to SPDX.

## What is your fix for the problem, implemented in this PR?

Achieve the list from SPDX repository.
As I don't guess  the list will update frequently, added the rake task to do it but not run automatically.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by hsbt — APPROVED** [review]

**Review by deivid-rodriguez — COMMENTED** [review]
@nobu Thanks for updating the list.

We do already have an automated way of generating this file through `ruby util/generate_spdx_license_list.rb`. I don't mind adding a rake task for it since it will make it more discoverable, but we should keep the current way of generating the file.

**Comment by deivid-rodriguez** [comment]
Our current script actually needs some tweaking to avoid style changes on the generated file:

```diff
diff --git a/util/generate_spdx_license_list.rb b/util/generate_spdx_license_list.rb
index a9df542952..3803808880 100644
--- a/util/generate_spdx_license_list.rb
+++ b/util/generate_spdx_license_list.rb
@@ -18,21 +18,20 @@
 require 'rubygems/text'
 
 class Gem::Licenses
-
   extend Gem::Text
 
   NONSTANDARD = 'Nonstandard'.freeze
 
   # Software Package Data Exchange (SPDX) standard open-source software
   # license identifiers
-  LICENSE_IDENTIFIERS = %w(
+  LICENSE_IDENTIFIERS = %w[
     #{licenses.sort.join "\n    "}
-  ).freeze
+  ].freeze
 
   # exception identifiers
-  EXCEPTION_IDENTIFIERS = %w(
+  EXCEPTION_IDENTIFIERS = %w[
     #{exceptions.sort.join "\n    "}
-  ).freeze
+  ].freeze
 
   REGEXP = %r{
     \\A
@@ -57,7 +56,6 @@ def self.suggestions(license)
     return unless lowest < license.size
     by_distance[lowest]
   end
-
 end
   RUBY
 end
```

**Comment by deivid-rodriguez** [comment]
I updated the PR with my suggestions, thanks @nobu!

**Comment by nobu** [comment]
Thank you, I've missed the script.
What about adding a comment about the autogeneration? for example:
```diff
diff --git a/util/generate_spdx_license_list.rb b/util/generate_spdx_license_list.rb
index 0bdac314fc..a38f4939d2 100644
--- a/util/generate_spdx_license_list.rb
+++ b/util/generate_spdx_license_list.rb
@@ -15,6 +15,7 @@
 open 'lib/rubygems/util/licenses.rb', 'w' do |io|
   io.write <<-RUBY
 # frozen_string_literal: true
+# generated by #{File.basename(__FILE__)}, don't edit this file.
 require 'rubygems/text'
 
 class Gem::Licenses
```

**Comment by deivid-rodriguez** [comment]
That's a good idea :+1:.

**Pull request merged**
