### PR TITLE
Set $0 to exe when running `gem exec` to fix name in CLI output

### PR DESCRIPTION
**Pull request by adam12**
The $0 value is used in many CLI libraries to determine the name of the application, when displaying help and error messages.

Without setting this value, it defaults to `gem` which can be confusing.

Before:

```
$ gem exec kamal help
Commands:
  gem accessory           # Manage accessories (db/redis/search)
  gem app                 # Manage application
  gem audit               # Show audit log from servers
  gem build               # Build application image
  gem config              # Show combined config (including secrets!)
  gem deploy              # Deploy app to servers
  gem details             # Show details about all containers
  gem docs [SECTION]      # Show Kamal configuration documentation
  gem help [COMMAND]      # Describe available commands or one specific command
  gem init                # Create config stub in config/deploy.yml and secrets stub in .kamal
  gem lock                # Manage the deploy lock
  gem proxy               # Manage kamal-proxy
  gem prune               # Prune old application images and containers
  gem redeploy            # Deploy app to servers without bootstrapping servers, starting kamal-proxy, pruning, and registry login
  gem registry            # Login and -out of the image registry
  gem remove              # Remove kamal-proxy, app, accessories, and registry session from servers
  gem rollback [VERSION]  # Rollback app to VERSION
  gem secrets             # Helpers for extracting secrets
  gem server              # Bootstrap servers with curl and Docker
  gem setup               # Setup all accessories, push the env, and deploy app to servers
  gem upgrade             # Upgrade from Kamal 1.x to 2.0
  gem version             # Show Kamal version
```

After:

```
$ gem exec kamal help
Commands:
  kamal accessory           # Manage accessories (db/redis/search)
  kamal app                 # Manage application
  kamal audit               # Show audit log from servers
  kamal build               # Build application image
  kamal config              # Show combined config (including secrets!)
  kamal deploy              # Deploy app to servers
  kamal details             # Show details about all containers
  kamal docs [SECTION]      # Show Kamal configuration documentation
  kamal help [COMMAND]      # Describe available commands or one specific command
  kamal init                # Create config stub in config/deploy.yml and secrets stub in .kamal
  kamal lock                # Manage the deploy lock
  kamal proxy               # Manage kamal-proxy
  kamal prune               # Prune old application images and containers
  kamal redeploy            # Deploy app to servers without bootstrapping servers, starting kamal-proxy, pruning, and registry login
  kamal registry            # Login and -out of the image registry
  kamal remove              # Remove kamal-proxy, app, accessories, and registry session from servers
  kamal rollback [VERSION]  # Rollback app to VERSION
  kamal secrets             # Helpers for extracting secrets
  kamal server              # Bootstrap servers with curl and Docker
  kamal setup               # Setup all accessories, push the env, and deploy app to servers
  kamal upgrade             # Upgrade from Kamal 1.x to 2.0
  kamal version             # Show Kamal version
```

## What was the end-user or developer problem that led to this PR?

Some commands would output `gem` in their help, causing confusion if you didn't look closely. Did the command run? Why are you getting gem help?

## What is your fix for the problem, implemented in this PR?

$0 is the program name, and is often used by CLI tools to determine currently running exe. We can override this value for the duration of the exec all, and reset it when complete.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/doc/bundler/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by soda92** [comment]
I don't know gem have `exec` too...😀 That seems reasonable

**Comment by deivid-rodriguez** [comment]
Yeah, although tests are complaining so that needs investigation. But the whole idea seems reasonable!

**Comment by adam12** [comment]
Let me see if I can get the tests passing. It was hard to tell if some of those were transient failures and unrelated, but I just noticed some mention the exec command.

**Comment by deivid-rodriguez** [comment]
Yeah, all failures happen with tests for the `exec` command.

**Comment by adam12** [comment]
I believe I found the issue. Please run the test workflow.

**Comment by adam12** [comment]
Fixed lint error, but I am not sure why a couple of the tests never finished after ~ 60 minutes or so.

**Comment by deivid-rodriguez** [comment]
> Fixed lint error, but I am not sure why a couple of the tests never finished after ~ 60 minutes or so.

That's strange, we haven't seen any timeouts lately. Maybe it was the Bundler-Windows jobs (yes, they are that slow 😢).

**Comment by adam12** [comment]
> I think the easiest way to get this covered is to add a simple realworld spec to `.github/workflows/install-rubygems.yml` that runs `gem exec kamal help` and greps for the corrected `kamal help` string in the output.

This sounds good to me. Let me add this.

**Comment by deivid-rodriguez** [comment]
Yeah, like that, although I intended to put it in `.github/workflows/install-rubygems.yml`, next to another similar `gem exec` that we already have to make sure that a Rails app can be generated with `gem exec`.

**Comment by adam12** [comment]
> put it in `.github/workflows/install-rubygems.yml`

That makes more sense! My brain reads what it wants to read, apparently.

**Review by deivid-rodriguez — COMMENTED** [review]
Forgot to mention a small thing about the command.

**Comment by adam12** [comment]
You're right. I should have caught it too. Juggling too many things :( All fixed up.

**Review by deivid-rodriguez — APPROVED** [review]
Looks great, thanks so much!

**Pull request merged**
