### PR TITLE
Add Github CI action to automatically label Bundler PRs

### PR DESCRIPTION
**Pull request by colby-swandale**
Per the title, something we can easily automate.

### CODE REVIEW

**Comment by hsbt** [comment]
Can we replace @bronzdoc's labeler to this for the issues too?

**Comment by colby-swandale** [comment]
@hsbt do we still want the triage label? We don't seem to be using it all that much.

**Comment by deivid-rodriguez** [comment]
Nice! :heart_eyes:

In my opinion, @bronzdoc's labeler in its current form is not very useful because it blindly tags every single PR or issue, so essentially the "triage" label is equivalent to no label at all. In fact, I feel it even gets in the middle a bit because once you do the triaging for a PR or issue, you have to remove the label.

So, my vote would go to stop using it.

**Comment by hsbt** [comment]
I'm also +1 to remove/stop it. We should re-arrange to label guideline in this repo.

**Comment by colby-swandale** [comment]
I will merge this now, but raise a new issue to propose dropping the automated triage label.

**Comment by bronzdoc** [comment]
This is nice! I don't think we use the labeler in PR's that much. I recently added functionality to label PR's with the bundler label based on the files modified but I think this is better.

**Pull request merged**
