### PR TITLE
Move find_home to PathSupport

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:

Move `find_home` to `PathSupport`
______________
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by simi** [comment]
What is the reason for this? Thanks to this it must be public and I'm not sure this is something we need public.

**Comment by bronzdoc** [comment]
@simi well... the reason was that it made sense to me that a class named `PathSupport` would be responsible of a path related method like `find_home`. But you have a point... maybe we can get rid of `find_home` completely? and add the logic into `user_home` since **A**.  `find_home` is not public and **B.** the only place used is in `user_home`.

**Comment by simi** [comment]
I think we can leave it as is just remove the `FIXME` comment.

**Comment by bronzdoc** [comment]
Will close this then @simi

**Pull request closed without merging**
