### PR TITLE
Update required_ruby_version to 3.1

### PR DESCRIPTION
**Pull request by segiddins**
This updates both rubygems and bundler to require Ruby 3.1+ (and bundler to require rubygems 3.3.3, which was released with Ruby 3.1)

3.0 has been EOL since march, drop support for it before the 3.4 release is cut

Signed-off-by: Samuel Giddins <segiddins@segiddins.me>

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by martinemde — APPROVED** [review]

**Comment by simi** [comment]
@eregon @enebo please can you confirm this is ok for other Ruby engines? It will be good to ensure all main implementations can use latest ecosystem tools.

**Comment by simi** [comment]
@segiddins according to CI, https://github.com/rubygems/rubygems/blob/3fce0ac70cb4dd41dd9a6084b2c07aa81f91a93d/.rubocop.yml#L5 needs also update

**Comment by deivid-rodriguez** [comment]
Also, we can do a pass over `bundler/lib/bundler/rubygems_ext.rb` and `bundler/lib/bundler/rubygems_integration.rb`. In particular, there's [a patch](https://github.com/rubygems/rubygems/blob/3fce0ac70cb4dd41dd9a6084b2c07aa81f91a93d/bundler/lib/bundler/rubygems_ext.rb#L267-L283) to `Gem::Requirement` that can be removed, and `Bundler.rubygems.supports_bundler_trampolining?` can be removed too.

**Comment by deivid-rodriguez** [comment]
Also grep for `Gem.rubygems_version` and we should be able to remove a few things from Bundler's test suite too!

**Comment by eregon** [comment]
Is this for both RubyGems and for Bundler? It looks like it given the changes to the two gemspecs, but I wasn't sure from the description.
Yes, I think it's fine to require RUBY_VERSION >= 3.1 for RubyGems & Bundler (for TruffleRuby).

**Comment by simi** [comment]
> Is this for both RubyGems and for Bundler? It looks like it given the changes to the two gemspecs, but I wasn't sure from the description. Yes, I think it's fine to require RUBY_VERSION >= 3.1 for RubyGems & Bundler (for TruffleRuby).

Yes, for both.

**Comment by deivid-rodriguez** [comment]
> +57 −13,375

👏👏👏👏

There's also a couple of `RUBY_VERSION` checks that can be removed/changed in `bundler/spec/support/rubygems_ext.rb` and also the "doesn't hang on nix gemfile" spec can be removed now (I think that no longer being run is responsible from all the removed cassettes).

Regarding that "nix" realworld spec, it was introduced by https://github.com/rubygems/rubygems/pull/4289. At the time, I was not able to reduce the fix to a simpler isolated spec and I had to cover it with a "realworld Gemfile" spec that was also dependent on the version of Ruby.

At this point, our resolver is very stable (I don't recall the last pure resolver issue we got), and things have changed so much there since the migration to Pub Grub, so I think it's fine to lose this coverage.

**Comment by segiddins** [comment]
@deivid-rodriguez @hsbt I believe this should be mergeable now!

**Review by deivid-rodriguez — APPROVED** [review]

**Comment by segiddins** [comment]
@deivid-rodriguez you'll need to change the required checks for `master` since the 3.0 jobs are now deleted

**Comment by deivid-rodriguez** [comment]
Done!

**Comment by simi** [comment]
@deivid-rodriguez what's release plan? Minor bump?

**Comment by deivid-rodriguez** [comment]
Yeah, I think minor bump like we've done the previous two years has worked just fine recently.

**Pull request merged**
