### PR TITLE
Remove duplicate cases

### PR DESCRIPTION
**Pull request by knqyf263**
## What is your fix for the problem, implemented in this PR?
Remove duplicate cases

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by hsbt** [comment]
@knqyf263 Thanks. I did submit to fix the failing tests related parallel gems at https://github.com/rubygems/rubygems/pull/4054

**Comment by hsbt** [comment]
@knqyf263 Can you rebase this from the current master branch?

**Comment by knqyf263** [comment]
@hsbt Thanks. Rebased.

**Comment by hsbt** [comment]
👍 Thanks!

**Pull request merged**
