### PR TITLE
Vendor bundler 2.1

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

We should release bundler 2.1 and include it in rubygems before releasing rubygems 3.1

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
👍

**Comment by hsbt** [comment]
I will merge after releasing Bundler 2.1.0 and backport to `3.1` branch.

**Comment by deivid-rodriguez** [comment]
Bundler 2.1.0 is out, and this PR is now ready to include it with the next version of rubygems. :+1:

**Comment by hsbt** [comment]
@bundlerbot merge

**Comment by hsbt** [comment]
@bundlerbot retry

**Pull request merged**
