### PR TITLE
Make `bundler config --local` docs clearer

### LINKED ISSUE #3385: "bundle config --local path 'vendor/bundle'" takes no action
As of version 2.0 running `bundle install --path vendor/bundle` suggests that the `--path` variable is deprecated.

The [documentation for bundler v2.0 suggests](https://bundler.io/man/bundle-config.1.html):

> Executing bundle config --local <name> <value> will set that configuration to the local application. The configuration will be stored in app/.bundle/config.

At the top level of my Rails application ("myserver"), I run `bundle config --local path 'vendor/bundle'`. 

I expect that this will install contents to `myserver/app/.bundle/config`, but instead, nothing happens.

```
$ ls -al app
total 0
drwxr-xr-x 10 kevin staff  320 Mar  4 14:36 .
drwxr-xr-x 32 kevin staff 1024 Mar 14 19:53 ..
drwxr-xr-x  7 kevin staff  224 Mar  4 14:36 assets
drwxr-xr-x  3 kevin staff   96 Mar  4 14:36 channels
drwxr-xr-x 11 kevin staff  352 Mar  4 16:33 controllers
drwxr-xr-x  5 kevin staff  160 Mar  4 14:36 helpers
drwxr-xr-x  3 kevin staff   96 Mar  4 14:36 jobs
drwxr-xr-x  3 kevin staff   96 Mar  4 14:36 mailers
drwxr-xr-x  6 kevin staff  192 Mar  4 15:54 models
drwxr-xr-x  7 kevin staff  224 Mar  4 14:36 views
```

### PR DESCRIPTION
**Pull request by kevinburkemeter**
The previous references to "app" could easily be confused with the
"app" directory of a Rails project, leading people to look in the
wrong place for Bundler configuration. Instead use a variable that
should make it clearer that we mean the top level of the project.

Fixes #3385.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by kevinburkemeter** [comment]
Grepping the source code, `bundler/man` seems to be the only place that has these words; I assume the website content gets generated from the manpages. If that's not correct let me know and I can make changes elsewhere.

**Comment by kevinburkemeter** [comment]
Ah, just saw the test failure, investigating.

**Comment by kevinburkemeter** [comment]
Running into https://github.com/rubygems/rubygems/issues/3284 while trying to get my dev environment set up

**Comment by kevinburkemeter** [comment]
I don't understand why a diff is still being generated, and the tests are failing, so I would appreciate some guidance here. I have ronn 0.7.3 installed and I put $PWD/bundler/bin first on my $PATH.

**Comment by deivid-rodriguez** [comment]
Thank you @kevinburkemeter!

I think I've seen this before and it was due to a difference in the `groff-base` version being used in the underlying OS. Sorry, I need to sort this out. It should work with the version provided by default in ubuntu, in case that helps. 

Anyways, I don't see that actual change here (you'll need to edit the corresponding `.ronn` file).

I can refresh the man pages for you later.

**Comment by kevinburkemeter** [comment]
Whoops, accidentally lost the changes here... reopened as #3408.

**Pull request closed without merging**
