### PR TITLE
appveyor.yml update

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

1. Updated appveyor.yml to correct casing issue in PATH.
2. Converted download of trunk to PowerShell code instead of Appveyor specific code.  Easier to port to local use if desired.
3. Moved GIT env variable to install section.
______________

# Tasks:

- [X] Describe the problem / feature
- [ ] Write tests
- [X] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
As mentioned elsewhere, this passes when a fix is added to appveyor.yml (see below).  Build is at  https://ci.appveyor.com/project/MSP-Greg/rubygems/build/75.  It was a second commit to this branch, I ran the AV test, then deleted it before creating the PR.

Thanks, Greg

```powershell
# Temporary fix until Appveyor installs RubyGems 2.7.7
- ps: >-
    if ($env:ruby_version -lt '25') {
      gem uninstall bundler -x
      Push-Location C:\
      gem fetch rubygems-update -v 2.7.7
      gem unpack  rubygems-update-2.7.7.gem
      Push-Location C:\rubygems-update-2.7.7
      ruby setup.rb
      Pop-Location
      Pop-Location
    }
```

**Comment by hsbt** [comment]
@MSP-Greg Can you add the your temporary fix into this branch?

**Comment by MSP-Greg** [comment]
Done & green on Appveyor.  Once #2297 is in, hopefully false 'fails' should happen a lot less often.

When Appveyor (AV) is updated, should I do a PR or ping back?  I suspect I'll find out very soon after it's fixed...  Thanks.

**Comment by hsbt** [comment]
Awesome. When you found a root problem for this, Please share with me. 

Thanks.

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by MSP-Greg** [comment]
@hsbt

> When you found a root problem for this, Please share with me.

I've got the issue to repo locally.  I started with 2.4.4, updated to 2.7.6, and it stops with same error as shown in the Appveyor log.  It (obviously) works fine once 2.7.7 is loaded.

I've got to go AFK, but I'll get to it this weekend.  Thanks, Greg

**Comment by MSP-Greg** [comment]
@hsbt,

> When you found a root problem for this, please share with me.

Might have found it.  See #2309.

Thanks, Greg

**Pull request merged**
