### PR TITLE
Backport ruby core repository

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Backport https://github.com/ruby/ruby/commit/f7e94df0d66aff47745d189ab5a7858a92233d57 and https://github.com/ruby/ruby/commit/0edc36b9f25e7b92c40d91858dfe4ef2bd06f796

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
These changes should both have tests

**Comment by MSP-Greg** [comment]
@segiddins

Travis trunk/head is failing on RuboCop, so it doesn't show the issue.

Please see Appveyor trunk here:
https://ci.appveyor.com/project/rubygems/rubygems/builds/20554189/job/eps17uxd7mchl6g0

**Comment by segiddins** [comment]
That doesn’t mean new tests can’t be added that catch the issue on all platforms

**Comment by MSP-Greg** [comment]
Sorry.  The reason they're not visible on Travis is because the RuboCop test is failing.  Got trunk?  You'll see the warnings with `rake test`...

Run the tests with some output for the objects, and you'll see a lot are not strings.  Hence, with the removal of `Object=~`, it causes a mess.

The fact that the method currently exists just allows sloppy code like [1,2] =~ /bad/ to not generate an error/exception.

**Pull request merged**
