### PR TITLE
Mask the file mode when extracting files

### PR DESCRIPTION
**Pull request by kddnewton**
When extracting files from the tarball, a mode is retrieved from
the header. Occasionally you'll encounter a gem that was packaged
on a system whose permission bits result in a value that is larger
than the value that File.chmod will allow (anything >= 2^16). In
that case the extraction fails with a RangeError, which is pretty
esoteric.

If you extract the tarball with the tar and gunzip utilities, the
file permissions end up being just the bottom 16 bits masked off
from the original value. I've mirrored that behavior here. Per the
tar spec:

> Modes which are not supported by the operating system restoring
> files from the archive will be ignored.

I think that basically means what I've done here.

You can test this by trying to extract the files for `Bluebie-legs-0.6.2`,
which was the first gem that I found (alphabetically) that had this
issue. `cameroncox-slicehost-tools-0.0.3` also had this issue, with
a slightly different set of permissions.

## What was the end-user or developer problem that led to this PR?

Cannot extract gems files with permissions too large for an unsigned
short.

## What is your fix for the problem, implemented in this PR?

Mask out the bottom 16 bits only.

## Make sure the following tasks are checked

I did not end up writing tests for this because I'm not entirely sure how I would. The existing tests all pass, which is good. I suppose I could attempt to package a gem such as the failure cases and vendor it into the test files, but I'm not sure it's worth the trouble.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Nice!

We do vendor some problematic gem packages for the shake of testing:

```
$ fd gem$ test
test/rubygems/packages/ascii_binder-0.1.10.1.gem
test/rubygems/packages/ill-formatted-platform-1.0.0.10.gem
```

`ascii_bindir-0.1.10.1.gem` is actually a realworld gem. I don't think it'd be a big deal to vendor one of these too.

**Comment by kddnewton** [comment]
@deivid-rodriguez alright I've vendored one of the problematic gems 👍

**Comment by deivid-rodriguez** [comment]
The failures mean you need to run ' rake manifest` and commit the result.

**Comment by deivid-rodriguez** [comment]
The new test seems to be failing in TruffleRuby, can you have a look?

**Comment by kddnewton** [comment]
@deivid-rodriguez I've updated the commit message with the fix. Basically there was an issue with buffered writes happening to the filesystem and CRuby and TruffleRuby had differing behavior. It should be consistent now.

**Comment by kddnewton** [comment]
For context, here's the issue where this behavior was introduced: https://github.com/rubygems/rubygems/issues/1161.

**Review by deivid-rodriguez — APPROVED** [review]
Wow, thanks for the fix and the thorough investigation!

**Comment by kddnewton** [comment]
Oh gosh now it's failing on windows... okay I'll keep looking.

**Comment by kddnewton** [comment]
Oh wait it looks like maybe I should be skipping this test on windows. @deivid-rodriguez does that sound right? I'm seeing a lot of pending "chmod not supported" stuff in the test file?

**Comment by deivid-rodriguez** [comment]
I think file permissions in Windows are not very well defined, I think it's fine to skip 👍.

**Comment by kddnewton** [comment]
Nice I think this is finally good to go

**Comment by deivid-rodriguez** [comment]
Thank you! ❤️

**Pull request merged**
