### PR TITLE
Add documentation section to README and fix a few documentation related issues

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

* Add a new section in the README covering the RubyGems documentation and
RubyGems guides.
* Update link to the RubyGems API to rubydoc.info since rubyforce.org
has been shutdown
* Add link to homepage of the referenced graph gem
* fix few small syntax issues

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by indirect** [comment]
awesome, thanks @colby-swandale!

@bundlerbot r+

**Comment by segiddins** [comment]
I'll update bundler so this goes 🍏 when I get a chance

**Comment by colby-swandale** [comment]
Thanks! @segiddins

**Comment by segiddins** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
@bundlerbot retry

**Pull request merged**
