### PR TITLE
Use binstubs provided by the bundler repo

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

With this PR I hope to fix the CI.

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
This needs this PR in bundler. I tried it against it and it works! :+1:

**Comment by hsbt** [comment]
👍 Thanks! I will update this after merging https://github.com/bundler/bundler/pull/7364

**Comment by deivid-rodriguez** [comment]
@hsbt Turns out this PR is no longer necessary after bundler/bundler#7364. Still it has some interesting changes, let me update what I think we can keep.

**Comment by hsbt** [comment]
ah, I see. Should we close this?

**Comment by deivid-rodriguez** [comment]
I updated the PR with the changes I think we can still include.

**Comment by deivid-rodriguez** [comment]
The first commit in here is good and I created [a separate PR for it](https://github.com/rubygems/rubygems/pull/2926). For the second one we'll need until we vendor the next version of bundler, so I'll rebase this PR once that happens.

**Comment by deivid-rodriguez** [comment]
Closing since these changes were incorporated with #2981.

**Pull request closed without merging**
