### PR TITLE
Fixed to warn with shadowing outer local variable.

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Maybe, Fixed https://travis-ci.org/rubygems/rubygems/jobs/565498010
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by hsbt** [comment]
We should resolve this pull-request into master directly. Because of bundler examples uses rubygems master branch without this branch.

@indirect Can I merge this directory without bundlerbot? /cc @bronzdoc

**Comment by bronzdoc** [comment]
Maybe we should make `TEST_TOOL=bundler RGV=master` to run agains the current PR instead of master.

**Comment by hsbt** [comment]
@bronzdoc Right. We need to add $TRAVIS_COMMIT to build task and handle it on bundler side.

**Comment by hsbt** [comment]
I confirmed to remove a warning in my local machine with rubocop.

```
~/D/g/r/rubygems (master) > rubocop --only Lint/ShadowingOuterLocalVariable lib/rubygems/ext/ext_conf_builder.rb
Inspecting 1 file
W

Offenses:

lib/rubygems/ext/ext_conf_builder.rb:48:41: W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable - results.
          run(cmd, results) do |status, results|
                                        ^^^^^^^

1 file inspected, 1 offense detected
~/D/g/r/rubygems (master) > g co ignore-shadowing-val
Switched to branch 'ignore-shadowing-val'
~/D/g/r/rubygems (ignore-shadowing-val) > rubocop --only Lint/ShadowingOuterLocalVariable lib/rubygems/ext/ext_conf_builder.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

**Pull request merged**
