### PR TITLE
Make `#to_lock` consistent between `Gem::Dependency` and `Bundler::Dependency`

### PR DESCRIPTION
**Pull request by cmrd-senya**
## What was the end-user or developer problem that led to this PR?

We're extending Bundler for our custom purposes, specifically we're buidling a monorepo support on top of Bundler.

There are two classes `Gem::Dependency` and `Bundler::Dependency`. The latter is inherited from the former. Also Bundler extends `Gem::Dependency`.

`Bundler::Dependency` provides `to_lock` method and Bundler extends `Gem::Dependency` to have one either.

https://github.com/rubygems/rubygems/blob/6ec214feb51102dfbfd94d685a43f8945addeb2e/bundler/lib/bundler/dependency.rb#L151-L155

https://github.com/rubygems/rubygems/blob/6ec214feb51102dfbfd94d685a43f8945addeb2e/bundler/lib/bundler/rubygems_ext.rb#L174-L181

There is an inconsistency between how `to_lock` method works for these two classes.

In `Gem::Dependency` it returns a string without a newline `\n` while in `Bundler::Dependency` it returns a string with a newline.

It doesn't hurt Bundler implementation because these classes are used in different places. But in our extensions in manifested itself because we started seeing extra newlines added when we used `to_lock` of `Bundler::Dependency`.

## What is your fix for the problem, implemented in this PR?

I removed the extra newline from the `to_lock` method of `Bundler::Dependency` and added the newline in `Bundler::LockfileGenerator#add_dependencies` where the `Bundler::Dependency` instances are used.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] ~~Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes~~ I don't think additional tests are needed, this is a refactoring and the existing tests make sure it works fine
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Review by deivid-rodriguez — COMMENTED** [review]
Nice, thanks!

Could you add a unit spec showing that `Gem::Dependency#to_lock` format is now compatible with `Bundler::Dependency#to_lock`?

**Comment by cmrd-senya** [comment]
@deivid-rodriguez updated, added the spec

**Review by deivid-rodriguez — APPROVED** [review]

**Comment by cmrd-senya** [comment]
Thanks for reviewing and merging my PR @deivid-rodriguez @simi !

**Comment by simi** [comment]
@cmrd-senya it was a pleasure.

> We're extending Bundler for our custom purposes, specifically we're buidling a monorepo support on top of Bundler.

Btw. are there any plans to open-source this project? It sounds interesting.

**Comment by cmrd-senya** [comment]
@simi actually yes! We are discussing open sourcing it and the team seems to be in favor of doing so. This is going to take a little time to prepare everything. But I'll let you know in this thread when there are news.

**Pull request merged**
