### PR TITLE
Warn when no files are set

### PR DESCRIPTION
**Pull request by packrat386**
# Description:

While it's not impossible that somebody could want a gem with no files
in it, I feel like this is fair game for a warning.
______________

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [x] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by packrat386** [comment]
@bronzdoc any chance I could get this reviewed?

**Comment by djberg96** [comment]
I think it's highly unlikely, but I don't have a problem with this PR.

**Comment by packrat386** [comment]
You're saying it's highly unlikely that somebody would have a gemspec with no files? I made this PR because I accidentally did that recently 😛

**Comment by bronzdoc** [comment]
@homu r+

**Pull request merged**
