### PR TITLE
[StubSpecification] Don’t iterate through all loaded specs in #to_spec

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

@indirect in your test case, this gave a real improvement in `-rbundler/setup` time

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+
@segiddins any ideas about how we can prevent these kind of regressions in the future? benchmark tests, maybe?

**Comment by segiddins** [comment]
@indirect benchmark tests are useless unless you're running on consistent metal

**Comment by indirect** [comment]
@segiddins yes, correct. uh, what's your point?

**Comment by segiddins** [comment]
We don't have bare metal servers at our disposal to run PRs against

**Comment by indirect** [comment]
@segiddins yes we do, Ruby Together pays for the bare metal servers that run rubybench.org. And we could easily afford more.

**Comment by segiddins** [comment]
If we could get benchmarks to optionally run against PRs, I'd be in favor of that. But only benchmarking releases means we end up accidentally shipping regressions (which I've done in resolver code for bundler)

**Comment by indirect** [comment]
I am super in favor of setting up a performance benchmarking server that tests the speed of common operations and reports back to the PR in a comment if they are a change bigger than ~5% or something like that 👍

**Pull request merged**
