### PR TITLE
Normalize comment indentations

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

This is a minor follow up to #2350, that fixes another style inconsistency that showed up in #2348.
______________

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by colby-swandale** [comment]
Thanks @bundlerbot r+

**Comment by colby-swandale** [comment]
Oh, I need to add Molinillo to the ignore list and set some options. I can fix that.

**Comment by deivid-rodriguez** [comment]
I can't reproduce locally :disappointed:, looks related to rubocop's compatibiliy setting (`TargetRubyVersion`), maybe explicitly setting it fixes it.

**Comment by deivid-rodriguez** [comment]
Rebased, it's ready now!

**Comment by colby-swandale** [comment]
Thanks! @bundlerbot r+

**Pull request merged**
