### PR TITLE
Lazy require stringio

### PR DESCRIPTION
**Pull request by bronzdoc**
# Description:
close https://github.com/rubygems/rubygems/issues/2772
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Nice! Perhaps we should have a test that boots rubygems and makes sure `stringio` (and with time other unnecessary default gems) are not required?

**Comment by bronzdoc** [comment]
> Perhaps we should have a test that boots rubygems and makes sure stringio
What would be your approach to such test @deivid-rodriguez ?

**Comment by deivid-rodriguez** [comment]
Perhaps running something like `ruby --disable-gems -Ilib -rrubygems -e 'exit require("stringio")'` in TravisCI would be enough for now?

**Comment by bronzdoc** [comment]
> Perhaps running something like ruby --disable-gems -Ilib -rrubygems -e 'exit require("stringio")' in TravisCI would be enough for now?

@deivid-rodriguez you mean as part of our `util/ci` script?

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez you mean as part of our util/ci script?

Yeah, that's what I meant. But your PR was good I agree with @hsbt, we can add the check on a separate PR. Thanks for doing this!

**Pull request merged**
