### PR TITLE
Cleanup base test case

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
# Description:

I was working on adding a proper performance test for #2741, and since I needed a separate base test class, I noticed that the current base test class is a bit of a mess. In this PR I tried to improve it a bit.

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Re `Remove references to old minitest', that may still be needed for use in Ruby Core testing, which does not use the bundled gems for testing.

**Comment by deivid-rodriguez** [comment]
Good point, I'll wait for @hsbt to confirm and also take the chance to actually run specs from ruby-core :+1:.

**Comment by MSP-Greg** [comment]
> actually run specs from ruby-core

That might be tricky.  I've got patches in ruby-loco to allow tests to run from the install directory (without the build directory).  Things like loading cert files break...  I did the patches a long time ago, so I'd have to look thru them to see all the issues...

**Comment by deivid-rodriguez** [comment]
I checked ruby-core. It has a strange situation where minitest 5 is a bundled gem, but they use sort of a fork of minitest 4 internally. I could see where bundler specs are run, but I could find where rubygems tests are run. Anyways, I removed the commit just to be sure it's all good.

**Comment by deivid-rodriguez** [comment]
I run rubygems tests from ruby-core and it's all good :+1:

**Comment by deivid-rodriguez** [comment]
@hsbt Thoughts about this?

**Comment by hsbt** [comment]
I confirmed to work this on ruby-core repo. Thanks!

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
Thanks @hsbt!

**Pull request merged**
