### PR TITLE
added include_dir attribute to Gem::Specificification

### PR DESCRIPTION
**Pull request by v0dro**
Patch for https://github.com/rubygems/rubygems/issues/2408

### CODE REVIEW

**Comment by bronzdoc** [comment]
Build failing because of rubocop
```
test/rubygems/test_gem_specification.rb:1408:1: C: Layout/TrailingWhitespace: Trailing whitespace detected.
```

**Comment by v0dro** [comment]
Fixing. Its strange because I did not touch that part of the code.

**Comment by segiddins** [comment]
I think you'll need to add a default value for the new ivar, probably name it `include_dirs` since its a plural value, and maybe even bump the specification version?

**Comment by v0dro** [comment]
@segiddins I did not set a default value since this variable is closely linked to `@gem_dir` and `@gem_dir` is initialized in the constructor (which is where `include_dir` is also initialized). I think this is reasonable. I agree on your choice of plural name and will change accordingly.

What do you mean by gem specification version?

**Comment by segiddins** [comment]
You’re adding new attributes to the gemspec, so the file format of the gemspec is changing

**Comment by bronzdoc** [comment]
Hi @v0dro do you still plan to work on this? thanks!

**Comment by bronzdoc** [comment]
Closing for lack of response

**Pull request closed without merging**
