### PR TITLE
Misc doc fixes [ci skip]

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

Fixes a few doc issues with YARD and http://www.rubydoc.info/github/rubygems/rubygems/

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Please remove the `[ci skip]`, all PRs must pass CI

**Comment by segiddins** [comment]
Also please don't directly modify vendored code

**Comment by MSP-Greg** [comment]
1. Most 'ruby' doc sites are using RDoc, so rubygems doesn't parse well.  I'm using YARD, so [ruby/rubygems](https://msp-greg.github.io/ruby_trunk/rubygems/Gem.html) shows a good representation of rubygems.  I've applied the patches here to the doc.  This is also the trunk, and I've show **all** classes, modules, and children.  Any API private or nodoc: items are tagged in red.

2. These patches fix [Gem at rubydoc.info](http://www.rubydoc.info/github/rubygems/rubygems/Gem) and the other files.

3. I've noticed several places where collections are only spec'd with <Object> members, I'll start a list and collect changes for those.  In a few weeks, I'll post another doc update.

Thanks everyone for their work.

**Comment by MSP-Greg** [comment]
> Also please don't directly modify vendored code

Sorry, what are you referring to? The Molinillo code?  That's actually where a lot of the parameter and return tags need the updates.

**Comment by segiddins** [comment]
> Sorry, what are you referring to? The Molinillo code? That's actually where a lot of the parameter and return tags need the updates.

Molinillo is developed at https://github.com/CocoaPods/Molinillo and releases are vendored into RubyGems, so any changes should be directed there

**Comment by MSP-Greg** [comment]
Since removing the Molinillo changes leaves this with one change, I'll just close this.

**Pull request closed without merging**
