### PR TITLE
Bump vendored connection_pool to 2.2.5

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Nothing but I think we should try to benefit from upstream's work.

## What is your fix for the problem, implemented in this PR?

Bump vendored version to 2.2.5. I also included a copy of patches that we were using directly and proposed them upstream:
* https://github.com/mperham/connection_pool/pull/152
* https://github.com/mperham/connection_pool/pull/153.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [ ] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Both upstream patches have been merged, so now we're in sync with current `connection_pool`'s master branch.

**Comment by deivid-rodriguez** [comment]
MacOS is very flaky. I think it's Github Actions environments fault.

I don't want to lose the coverage, but I would further reduce the matrix to only run against the oldest and the newest ruby supported. The cases were ruby version specific issues are found are very few, and when it happens it's always because of using newer ruby features not present in older versions. I don't recall any other cases at the moment. So I believe on Windows and MacOS maybe oldest+newest is fine.

**Comment by deivid-rodriguez** [comment]
@simi Let me know if the proposal seems ok to you. I think it should further reduce flakyness, and also make CI feedback faster.

**Comment by deivid-rodriguez** [comment]
Proposed at https://github.com/rubygems/rubygems/pull/4741.

**Comment by simi** [comment]
@deivid-rodriguez makes sense. :+1:

**Pull request merged**
