### PR TITLE
Switch from DES-CBC to AES-256-CBC.

### PR DESCRIPTION
**Pull request by voxik**
DES-CBS is considered legacy and disabled in OpenSSL 3.x+ [[1], [2]]. This cause causes Ruby (with patches from https://github.com/ruby/openssl/pull/399) test failures:

~~~
ruby -v: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
/builddir/build/BUILD/ruby-3.0.2/lib/rubygems/test_case.rb:1542:in `initialize': Neither PUB key nor PRIV key (OpenSSL::PKey::RSAError)
	from /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/test_case.rb:1542:in `new'
	from /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/test_case.rb:1542:in `load_key'
	from /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/test_case.rb:1562:in `<class:TestCase>'
	from /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/test_case.rb:105:in `<top (required)>'
	from <internal:/builddir/build/BUILD/ruby-3.0.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/builddir/build/BUILD/ruby-3.0.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/ruby-3.0.2/test/rdoc/test_rdoc_rubygems_hook.rb:2:in `<top (required)>'
	from <internal:/builddir/build/BUILD/ruby-3.0.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/builddir/build/BUILD/ruby-3.0.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1049:in `block in non_options'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1043:in `each'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1043:in `non_options'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:65:in `process_args'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:143:in `process_args'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1237:in `process_args'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1242:in `run'
	from /builddir/build/BUILD/ruby-3.0.2/tool/lib/test/unit.rb:1249:in `run'
	from /builddir/build/BUILD/ruby-3.0.2/tool/test/runner.rb:23:in `<top (required)>'
	from ./test/runner.rb:11:in `require_relative'
	from ./test/runner.rb:11:in `<main>'
~~~

Therefore use AES-256-CBC instead. This is essentially revert of ca228b76b, which was fixing https://github.com/jruby/jruby/issues/919

@headius any idea if something changed on this front, because the link referenced in [this comment](https://github.com/jruby/jruby/issues/919#issuecomment-24596727) does not work anymore.

[1]: https://github.com/openssl/openssl/blob/master/doc/man7/migration_guide.pod#legacy-algorithms
[2]: https://github.com/openssl/openssl/blob/master/doc/man7/OSSL_PROVIDER-legacy.pod

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
> Even the CI is green as far as I can tell. I just wonder how old JRuby is supported, if there might be some compatibility concern.

I think 9.2 and 9.3 is more than enough, and both seem fine.

> It would probably make sense to keep this PR open to cover all OpenSSL 3.x related issues and merge them at once

👍

**Comment by deivid-rodriguez** [comment]
@simi Do you prefer to merge this particular patch now?

**Comment by voxik** [comment]
#5040 is fixing the `TestGemRequest#test_verify_certificate_extra_message`. So I am down to these two:

~~~
TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection
TestGemRemoteFetcher#test_ssl_client_cert_auth_connection
~~~

So far it seems that those are related and the reason is that OpenSSL cant parse some certificate (client.pem), but I still don't understand where the problem lies, since these can be parsed by the cmd line utilities as far as I can tell.

**Comment by voxik** [comment]
> #5040 is fixing the `TestGemRequest#test_verify_certificate_extra_message`. So I am down to these two:
> 
> ```
> TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection
> TestGemRemoteFetcher#test_ssl_client_cert_auth_connection
> ```
> 
> So far it seems that those are related and the reason is that OpenSSL cant parse some certificate (client.pem), but I still don't understand where the problem lies, since these can be parsed by the cmd line utilities as far as I can tell.

It seems that this might be the [ruby/openssl](https://github.com/ruby/openssl/pull/399#issuecomment-957998744) issue after all, but I might be completely wrong, waiting for confirmation.

Nevertheless, this might also be something to chang on RubyGems side, because it is not clear to me if there is any compelling reason to combine the key and certificate in the same file:

https://github.com/rubygems/rubygems/blob/3f92e9e060a1628f4c71f814fde52580a7f7b07f/lib/rubygems/request.rb#L54-L58

**Comment by deivid-rodriguez** [comment]
Since we have already merged a separate improvement to get a green test suite against openssl 3.0, I propose to merge this one too.

**Comment by voxik** [comment]
> Since we have already merged a separate improvement to get a green test suite against openssl 3.0, I propose to merge this one too.

Yes, right. That would be nice. I'll happily open separate ticket if needed

**Pull request merged**
