### PR TITLE
Unifying Fixnum and Bignum into Integer at Ruby 2.4

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

ruby core team unified `Fixnum` and `Bignum` into Integer on current master.  I backport these code from our repository.

ref. https://github.com/ruby/ruby/commit/f9727c12cc8fbc5f752f5983be1f14bb976e5a13
______________

# Tasks:

- [*] Describe the problem / feature
- [*] Write tests
- [*] Write code to solve the problem

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Is this backwards compatible?

**Comment by hsbt** [comment]
Yes. https://travis-ci.org/rubygems/rubygems/builds/131017557

**Comment by segiddins** [comment]
@homu r+

**Comment by hsbt** [comment]
Thank you for your review :octocat:

**Comment by tonytonyjan** [comment]
ruby kaigi 2016 "Unifying Fixnum and Bignum into Integer" brought me here 👍

**Pull request merged**
