### PR TITLE
Update Rubies to latest version in .travis.yml

### PR DESCRIPTION
**Pull request by junaruga**
# Description:
I want to update Rubies to latest version in `.travis.yml`.

______________

# Tasks:

- [X] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by junaruga** [comment]
It is weird.

Only Ruby 1.9.2 tests were failed due to "no rubies are available to download".
https://travis-ci.org/rubygems/rubygems/builds/230738953?utm_source=github_status&utm_medium=notification

> $ rvm use 1.9.2 --install --binary --fuzzy
> ruby-1.9.2 is not installed - installing.
> Searching for binary rubies, this might take some time.
> Requested binary installation but no rubies are available to download, consider skipping --binary flag.
> Gemset '' does not exist, 'rvm ruby-1.9.2 do rvm gemset create ' first, or append '--create'.

**Comment by simi** [comment]
@junaruga it was spotted already in https://github.com/rubygems/rubygems/pull/1916#issuecomment-299878216.

**Comment by junaruga** [comment]
@simi ok thanks for the information.

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Pull request merged**
