### PR TITLE
Include gem name in native extension build directory path

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Migrated from https://github.com/rubygems/bundler/pull/6934
______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by joelnordell** [comment]
Bundler is part of rubygems now? Nice.

This change is an important fix for when a Gemfile specifies multiple gems that are contained in one git repository (where each gem is in a subdirectory within the repo) and they all have native extensions.

Without this change, bundler would only build one of the native extensions but not the others.

It would be good for this to have a test case.

**Comment by deivid-rodriguez** [comment]
Still two separate libraries (hopefully will merge them in the future), but we have a monorepo now :)

This fix looks good in principle, but I'd really like a test for it.

**Comment by joelnordell** [comment]
@deivid-rodriguez - Since I don't have push access to this repo, I'll do the following:

* Make a fork of `rubygems`
* Add a test case in a branch on my fork
* Open a new pull request targeting _this_ branch so you can merge/rebase the test case in here

**Comment by deivid-rodriguez** [comment]
Sure, or feel free to open a separate PR and we'll close this one. Whatever is simpler for you.

**Comment by joelnordell** [comment]
@deivid-rodriguez -- I went ahead and opened a new PR which targets `master` and replaces this one. Does seem a little cleaner that way.

https://github.com/rubygems/rubygems/pull/3475

**Comment by deivid-rodriguez** [comment]
Thank you! :heart:

**Pull request closed without merging**
