### PR TITLE
Travis - add 2.6.1, change to Xenial

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description:

Add Ruby 2.6.1 to Travis matrix, update to Xenial from Trusty

# Tasks:

- [X] Describe the problem / feature
- [ ] Write tests
- [X] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Re the intermittent in test_gem.rb, I've run many times locally (Windows) with a script, from Ruby 2.3 thru trunk.  Never failed/errored....

**Comment by hsbt** [comment]
@MSP-Greg Can you split https://github.com/rubygems/rubygems/pull/2614/commits/464678115adf8e2b00d9e27b04e7f44631c77a3c from this pull request?

**Comment by MSP-Greg** [comment]
This is now failing on Ruby 2.6.1/Bundler.  I haven't had a chance to investigate.  I can add it 'allow failure'?

**Comment by hsbt** [comment]
@MSP-Greg Can you add `2.6.1` to allow_failures. I think it's a known issue.

**Comment by MSP-Greg** [comment]
@hsbt Done & green...

**Comment by hsbt** [comment]
Thanks a lot ❤️

**Comment by hsbt** [comment]
@bundlerbot r+

**Pull request merged**
