### PR TITLE
Backport ruby core changes and pick missing commits

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

I tried to pick the original commits to the ruby core repository from rubygems/rubygems.

https://github.com/ruby/ruby/pull/2301

I picked some of the commits from the ruby core repository and added workarounds for ruby repository.

But I found the following missing commits:

* https://github.com/rubygems/rubygems/commit/30ed32c06fe0854e4a7cae2bbaa15b4720610932
* https://github.com/rubygems/rubygems/commit/564efbfa2e680eb70390c0b70f585f07df85e2b6
* https://github.com/rubygems/rubygems/commit/ff2d1d7749ecfb41886566b74877bdab5cfaf873

@deivid-rodriguez Do you know why these commits was lost in master branch? I found them with `git log 97b264f0fa..3644e130ad`.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by hsbt** [comment]
@bronzdoc I partly reverted be962ca0c411f3b4bcfebfb6e714c78cbad12775

We can remove `compatibility.rb` from rubygems after removing `Gem::ConfigMap` from bundler.

**Comment by bronzdoc** [comment]
Alright @hsbt 👍

**Comment by hsbt** [comment]
I think https://github.com/rubygems/rubygems/commit/ff2d1d7749ecfb41886566b74877bdab5cfaf873 broke the windows environment. ref. https://ci.appveyor.com/project/rubygems/rubygems/builds/26290250/job/1opiwfgqtv9r64y6

https://github.com/rubygems/rubygems/commit/30ed32c06fe0854e4a7cae2bbaa15b4720610932 and https://github.com/rubygems/rubygems/commit/564efbfa2e680eb70390c0b70f585f07df85e2b6 are okay.

**Comment by hsbt** [comment]
I try to invoke test with reverting ff2d1d7749ecfb41886566b74877bdab5cfaf873. But appveyor is still failing. https://ci.appveyor.com/project/rubygems/rubygems/builds/26294598

**Comment by hsbt** [comment]
The failing of appveyor was caused by https://github.com/rubygems/rubygems/commit/564efbfa2e680eb70390c0b70f585f07df85e2b6 . I will squash the commits on this pull request, and merge this.

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
@hsbt Sorry for the delay, I'm not sure why the commits were not present in the master branch. Do you want me to investigate or did you figure it out?

**Comment by hsbt** [comment]
@deivid-rodriguez Not need now. Because all of the tests are passed. We should file it when some of the issues happened.

**Pull request merged**
