### PR TITLE
Update manifest

### PR DESCRIPTION
**Pull request by colby-swandale**
# Description:

This PR is 2 parts. The first part is that there has been a few PRs recently that have added some new files, but didn't update `Manifest.txt`.

The second part is that there is an bug in the Regex that is excluding files in `Manifest.txt` that it shouldn't be. If you run `rake update_manifest` in `master`, files that contain `doc` will be removed. I've update the regex to make sure it does not remove those files.

______________

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
One question @colby-swandale and @bronzdoc. Should we actually ship `util/*` with rubygems? It seems to be only rubygems development scripts, so maybe that folder should be actually excluded as well?

**Comment by bronzdoc** [comment]
> Should we actually ship util/* with rubygems? It seems to be only rubygems development scripts, so maybe that folder should be actually excluded as well?

@deivid-rodriguez  my opinion is that it shouldn't

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
@bronzdoc So you think we shouldn't ship the files in the `utils` folder? In that case, should we create a PR to remove the files from the manifest?

**Pull request merged**
