### PR TITLE
Use File.expand_path for certification and key location.

### PR DESCRIPTION
**Pull request by hsbt**
# Description:

Because directory structure of ruby core needs to a relative path.

It fixed https://travis-ci.org/ruby/ruby/builds/257589943#L7002 .
______________

# Tasks:

- [x] Describe the problem / feature
- [ ] Write tests
- [x] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Looks good, but it's failing on CI: https://travis-ci.org/rubygems/rubygems/jobs/262584466#L938

**Comment by hsbt** [comment]
I see. It's a strange result. I investigate it.

**Comment by hsbt** [comment]
I rewrite a test case used `Gem::TestCase.cert_path` and ``Gem::TestCase.key_path`

**Comment by hsbt** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
Awesome, thanks!

**Pull request merged**
