### PR TITLE
Add modern rubies as valid platform values in Gemfile DSL

### PR DESCRIPTION
**Pull request by BobbyMcWho**
## What was the end-user or developer problem that led to this PR?

Attempting to limit a gem version to a specific version on ruby 3.0, realized that :ruby_30 was not a supported platform. 

## What is your fix for the problem, implemented in this PR?

Add modern rubies to the platforms and known Major versions.

## Make sure the following tasks are checked

- [X] Describe the problem / feature
- [X] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [X] Write code to solve the problem
- [X] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by simi** [comment]
Hello, thanks for keeping this list updated. It seems super easy to get this list out-of-date. Any plans @deivid-rodriguez on keeping this updated? Maybe we can use some CI mojo and ensure all CI versions have proper entry in those lists at least.

**Comment by deivid-rodriguez** [comment]
It seems easy enough to add an extra test (in addition to the hardcode list of platforms that we check to be defined) to check that also the running ruby has a corresponding platform value defined?

**Comment by simi** [comment]
@deivid-rodriguez ok to merge this first?

**Comment by deivid-rodriguez** [comment]
Sure!

**Pull request merged**
