### PR TITLE
Fix regression when installing native extensions on universal rubies

### PR DESCRIPTION
**Pull request by hanyang-tony**
Since #6945 the extension dir changed to Gem::BasicSpecification's implementation, we didn't hook that in rubygems_ext.rb. So for universal rubies, we ended up using the universal platform name when installing, but arch replaced platform name when checking. This lead to native extensions can never be correctly installed on universal rubies.

Hook Gem::BasicSpecifications so the behavior is consistent on installing and checking.

## What was the end-user or developer problem that led to this PR?
For universal rubies, the change from #6945 to def gem_build_complete_path is incorrect. Previously, extension_dir is invoked on the Bundler::StubSpecification, which is a child class of Specification. After the change to stub.gem_build_complete_path, @Stub is actually an instance of Gem::StubSpecification, thus gem_build_complete_path is from Gem::BasicSpecification.

The problem arise when in bundler, we replace the 'universal' part of Gem::Platform with the arch. But we still use the universal name for Gem::Specification, this is defined in 'rubygems_ext.rb'. Now the stub is using extension_dir defined in Gem::BasicSpecification, so the 'universal' part ended up being swapped by arch.

So, we install native extensions to 'extensions/universal-darwin-22/', but finding them in 'extensions/x86_64-darwin-22/'. Leading to native extension gems can never be installed on universal ruby.

## What is your fix for the problem, implemented in this PR?
Hook Gem::BasicSpecifications so the behavior is consistent on installing and checking.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [x] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by segiddins** [comment]
Looks good, mind adding a spec for the scenario that this addresses?

**Comment by hanyang-tony** [comment]
I realized we can avoid code duplication by change `class Specification` to `class BasicSpecification`, since the former is a subclass of the latter. Also added a spec to test if `StubSpecification`'s `extensions_dir` equals `Specification`s.

**Comment by hanyang-tony** [comment]
> Looks good, mind adding a spec for the scenario that this addresses?

Done :)

**Comment by deivid-rodriguez** [comment]
@hanyang-tony I tried reverting the fix here, and the spec still passes. Can you have a look?

**Comment by hanyang-tony** [comment]
> @hanyang-tony I tried reverting the fix here, and the spec still passes. Can you have a look?

Sorry, I was testing the wrong method. I've fixed it now. Due to the nature of how the `Gem::StubSpecification::StubLine` is loaded, I have to include a separate gemspec file instead of inline it in spec test. Please check it out.

**Comment by deivid-rodriguez** [comment]
Maybe I'm crazy but the new spec is still passing without this fix?

**Comment by hanyang-tony** [comment]
> Maybe I'm crazy but the new spec is still passing without this fix?

This is a fix for 'universal ruby', `Gem::Platform.local.cpu` should be 'universal'. Other versions of ruby don't have this issue.

**Comment by deivid-rodriguez** [comment]
Ideally we'd fine a way to test this in our CI, to avoid regressions, even if by mocking the platform somehow. Let's ship the bug fix though for now.

**Comment by hanyang-tony** [comment]
> Ideally we'd find a way to test this in our CI, to avoid regressions, even if by mocking the platform somehow. Let's ship the bug fix though for now.

It's possible to hook `Platform.local` into universal ruby in this spec. Or add a workflow that hook it first then run the specs.

**Comment by hanyang-tony** [comment]
I've fixed the linting error, can we re-run the actions?

**Comment by hanyang-tony** [comment]
Can we re-run the failed test? Seems like it was not caused by the changes in this PR.

**Comment by deivid-rodriguez** [comment]
Ok, let's ship this as is.

> It's possible to hook Platform.local into universal ruby in this spec. Or add a workflow that hook it first then run the specs.

Would happily accept such a test to cover this 👍.

**Comment by Bo98** [comment]
> It's possible to hook `Platform.local` into universal ruby in this spec

You could take inspiration from https://github.com/rubygems/rubygems/commit/11229b16c3bd400c70294855d7e9de7bdd84a2c5 which uses `simulate_platform` and `simulate_ruby_platform`.

**Comment by hanyang-tony** [comment]
> > It's possible to hook `Platform.local` into universal ruby in this spec
> 
> You could take inspiration from [11229b1](https://github.com/rubygems/rubygems/commit/11229b16c3bd400c70294855d7e9de7bdd84a2c5) which uses `simulate_platform` and `simulate_ruby_platform`.

I tried to use `simulate_ruby_platform`, but it doesn't work in this case. Because the RUBY_PLATFORM isn't used directly by this spec, it's the hook in `rubygems_ext.rb` that make use of it. The hook only run once, before the spec is run, so change the platform in spec doesn't do anything.

**Comment by Bo98** [comment]
Yeah it's designed to work when running a Bundle process (`install_gemfile`) rather than direct method calls. So if the problem can be translated to a real world steps to reproduce then we could test that. Was the problem revealed from doing a `bundle exec` after an install? The existing tests only tested the install.

**Comment by hanyang-tony** [comment]
The regression caused bundler to search gem extension in a different directory than the one which it was installed. The existing tests could work if the tested gem has native extension.

**Pull request merged**
