### PR TITLE
[Source] Autoload fileutils

### PR DESCRIPTION
**Pull request by segiddins**
# Description:

Since fileutils is now a gem

# Tasks:

- [ ] Describe the problem / feature
- [ ] Write tests
- [ ] Write code to solve the problem
- [ ] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by segiddins** [comment]
Any objection to this?

**Comment by hsbt** [comment]
I wonder why we use autoload for default gem.

PS. Matz is against to use `autoload`. https://bugs.ruby-lang.org/issues/5653. We have the plan to deprecate or remove on long term (at Ruby 3.0?)

**Comment by segiddins** [comment]
The removal of autoload would make bundler and rubygems setup much much slower, and I think autoload is far preferable to manually adding `require "foo"` to every place `foo` is used to lazy-load the code (in addition to being faster, because of the way RubyGem's require is implemented)

**Comment by djberg96** [comment]
@hsbt Generally true that it should be avoid because of threading issues from what I've read. But, rubygems isn't typically used as a library, so I'm not sure how much real risk there is.

**Comment by matthewd** [comment]
@djberg96 FYI autoload has officially been threadsafe since 2.0 (https://github.com/ruby/ruby/commit/1e7f99dddf1877f5fb7a4dd5759dddff8ba17154)... though I've seen hints of bugs, so whether that's informative may depend on how recent your existing information is. 😅

(Since that change, I'm not sure why it would still be removed, tbh.. but that's a discussion for elsewhere.)

**Comment by djberg96** [comment]
@matthewd Ok, thanks. Alright, then I say merge.

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
